alphagov/signon

- app/views/admin/users/_form_fields.html.erb
- lib/abilities/admin.rb
- test/integration/inviting_users_test.rb
In its current state, the app backend doesn't allow admins to set the role (because for admins, attr_accessible doesn't include the `role` attribute),
so presenting this option in the frontend leads to confusion. This change hides the role dropdown for admins, for now.
This PR also fixes a bug relating to generation of the "role" dropdown (where there was a mismatch between the label and the actual role). Because admin's can't create non-admins, there isn't currently an end-to-end test that verifies this fix.
/cc @vinayvinay this might clash with your Pundit work...
> Admins can no longer select roles

- app/controllers/admin/users_controller.rb
- app/controllers/confirmations_controller.rb
- app/controllers/users_controller.rb
- app/mailers/user_mailer.rb
- app/models/event_log.rb
- app/views/user_mailer/email_changed_by_admin_notification.html.erb
- app/views/user_mailer/email_changed_by_admin_notification.text.erb
- test/functional/admin/users_controller_test.rb
- test/functional/confirmations_controller_test.rb
- test/functional/users_controller_test.rb
- test/integration/email_change_test.rb
www.agileplannerapp.com/boards/173808/cards/6192
for users who have moved from one organisation to another, and consequently have an updated email in Signon, resetting their password is confusing.
they won't receive password reset instructions on their new email if they've not confirmed it yet. sending reset instructions to their old address works, but on most occasions they would have lost access to the old address by then.
hence, we're skipping re-confirmation when an admin updates a user's email address and instead we send a notification to a user's old and new email address informing them about the update.
also adding events to the users access log when email is changed and the change is accepted.
notification email text:
> Hello Louisa Lockwood,
> A Signon administrator has changed …
> Admin email change flow

- app/controllers/admin/suspensions_controller.rb
- app/controllers/admin/users_controller.rb
- app/controllers/superadmin/api_users_controller.rb
- app/controllers/superadmin/authorisations_controller.rb
- app/controllers/users_controller.rb
- app/helpers/users_helper.rb
- app/models/event_log.rb
- app/views/admin/event_logs/index.html.erb
- db/migrate/20150107063935_add_trailing_message_to_event_logs.rb
- db/schema.rb
- test/functional/admin/users_controller_test.rb
- test/functional/superadmin/api_users_controller_test.rb
- test/functional/users_controller_test.rb
- test/integration/email_change_test.rb
- test/unit/event_log_test.rb
This makes `EventLog` flexible to addition of parameters and removes the need to pass `nil` as a parameter on occasions when trailing parameters need to be passed.
Adds a new attribute on `EventLog`: `trailing_message`, which allows us to record additional attributes about the event as a free-form string. Includes the first use of `trailing_message` in order to record old and new email address when the email is changed.
> Allow passing options to EventLog

- jenkins.sh
To ensure we have a clean state, and to prevent logfiles etc from
growing without bounds etc.
> Do a git clean before jenkins build.

- app/controllers/users_controller.rb
- app/mailers/user_mailer.rb
- app/views/user_mailer/email_changed_notification.html.erb
- app/views/user_mailer/email_changed_notification.text.erb
- test/functional/admin/users_controller_test.rb
- test/functional/users_controller_test.rb
- test/integration/email_change_test.rb
following-up on these changes: https://github.com/alphagov/signonotron2/pull/302
When a user updates their own email address:
1. they should be sent a confirmation email at their new email address (exisiting behaviour), and
2. they should be notified about that change being initiated at their old emails address (new).
There's no corresponding story for this change, is an outcome of discussions in Slack.
/cc: @fofr, @marksheldonGDS
> User email change should be notified at old email

- config/locales/devise.en.yml
- test/integration/passphrase_reset_test.rb
- I reset my passphrase earlier and thought that the wording was a bit weird.
With Paul's help, here's an attempt at changing it.
> Reword the passphrase reset "email sent" flash message

- db/schema.rb
Matches the latest migration here: https://github.com/alphagov/signonotron2/commit/a5950eb98f855988f9cff31e40f27219a49ab28b
> Correct the schema number.

- Gemfile
- Gemfile.lock
- app/controllers/passwords_controller.rb
- config/environments/test.rb
- test/helpers/email_helpers.rb
- test/helpers/passphrase_support.rb
- test/integration/batch_inviting_users_test.rb
- test/integration/passphrase_reset_test.rb
- test/test_helper.rb
This partially reverts a044b79 (PR #65).
It would seem that some of our users have virus-scanning systems that
follow links in emails to check for anything malicious.  This was
breaking the passphrase reset flow because the token was being reset the
first time the page was accessed.  The root of this problem is that we
have a GET route in the application that has side-effects.
This removes this functionality so that a password reset token will
continue to work until the passphrase has been reset, at which point
it's cleared (this is standard devise behaviour).
Note: This branch has been based on `release_498` so that it can be deployed as a hotfix without having to deploy #298 at the same time.
> Fix password reset flow

- app/policies/user_policy.rb
- test/functional/invitations_controller_test.rb
when an admin tries to resend an invitation, the page blows-up because there is no policy defined for that action.
fixes: [errbit](https://errbit.preview.alphagov.co.uk/apps/52e678360da1158195000002/problems/54c6800e0da1159ab2008c60)
> Add resend? to UserPolicy

- app/controllers/invitations_controller.rb
- test/functional/invitations_controller_test.rb
was raising an Pundit::AuthorizationNotPerformedError
fixes: [errbit](https://errbit.preview.alphagov.co.uk/apps/52e678360da1158195000002/problems/54c8daed0da115b9d6009d05)
> Authorise an unauthorised action using Pundit

- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
- test/integration/user_link_test.rb
It's quite a common use case, at least for GOV.UK developers, to want to change their own permissions to test some permission-based feature in an app, which involves going to the user section and searching for their user record. If they have to do this multiple times, it's tedious and introduces the risk that they'll change permissions for someone else by mistake.
The original destination for this link was to the Signon root page: this is consistent with other apps, where it makes sense to link through to Signon; when you're in Signon already, this isn't particularly useful, especially when the "GOV.UK Signon" link in the header takes you there already.
The logic to determine the link target depends on whether the user has permission to edit themselves. As the logic currently stands, …
> Make the user's name a link to edit themselves

- app/controllers/users_controller.rb
- app/presenters/user_export_presenter.rb
- test/unit/user_export_presenter_test.rb
The remodelled permissions branch didn't include this feature due to
them being created in parallel, so when it was merged, things broke.
> Fix CSV export to work with remodelled permissions.

- Gemfile
- Gemfile.lock
- README.md
- app/controllers/doorkeeper_applications_controller.rb
- app/controllers/supported_permissions_controller.rb
- app/controllers/users_controller.rb
- app/models/enhancements/application.rb
- app/views/doorkeeper_applications/edit.html.erb
- app/views/doorkeeper_applications/index.html.erb
- app/views/layouts/application.html.erb
- app/views/supported_permissions/edit.html.erb
- app/views/supported_permissions/index.html.erb
- app/views/supported_permissions/new.html.erb
- config/routes.rb
- test/functional/doorkeeper_applications_controller_test.rb
- test/functional/supported_permissions_controller_test.rb
- test/unit/sso_push_client_test.rb
- test/unit/sso_push_error_test.rb
- test/unit/workers/permission_updater_test.rb
there have been many enhancements and performance improvements to this gem:
https://github.com/doorkeeper-gem/doorkeeper/blob/master/CHANGELOG.md
many changes are to make it compatible with newer versions of Rails, so these are first steps to prepare for upgrading Signon to Rails 4.
some noteworthy backward incompatible changes:
- removing `doorkeeper_for` in favour of a `before_filter`
- forcing usage of SSL in redirect uri
> Upgrade doorkeeper

- app/helpers/users_helper.rb
- test/unit/helpers/users_helper_test.rb
unsynced permissions raised method missing on nil errors. fixes: [errbit](https://errbit.preview.alphagov.co.uk/apps/52e678360da1158195000002/problems/54cf857f0da115411000159a)
> Make sync_needed? work with unsynced permissions

- app/models/enhancements/application.rb
- app/models/supported_permission.rb
- app/views/shared/_user_permissions.html.erb
- app/views/supported_permissions/index.html.erb
- db/migrate/20150204115922_add_grantable_from_ui_to_supported_permissions.rb
- db/migrate/20150204132812_add_user_update_supported_permission_to_applications.rb
- db/schema.rb
- test/factories/oauth_applications.rb
- test/integration/granting_permissions_test.rb
- test/unit/doorkeeper_application_test.rb
- test/unit/workers/push_user_updates_worker_test.rb
we need a way to hide supported permissions from the admin ui, which should only be granted through code. as of now the only such supported permission is 'user_update_permission', which is granted to users accessing the user API in gds-sso: https://github.com/alphagov/signonotron2/blob/master/lib/sso_push_credential.rb
gds-sso checks for presence of this permission while authorising user API access: https://github.com/alphagov/gds-sso/blob/6c37cfe4e8c74b9d530bac5ea9c7cb73b768c193/app/controllers/api/user_controller.rb#L44-L46
we need to add a 'user_update_permission' supported permission to apps that support push updates. earlier this worked because permissions were stored as strings, and there wasn't a 1-1 correspondence between granted permissions and an application's supported …
> Supported permissions can be hidden from admin UI

- app/models/enhancements/application.rb
- db/migrate/20150212133251_fix_user_update_permission.rb
- db/schema.rb
- test/unit/doorkeeper_application_test.rb
after saving an application that supports push updates, we create a supported permission 'user_update_permission' for it. this was being created such that it was visible on the Signon interface, whereas it shouldn't have been. this permission is used internally by the system and does not mean anything to the users. this is due to a bug left-over from implementing grantable_from_ui: #326 
there's a migration to fix any invalid data that's been created in the meantime.
> Hide supported permission "user_update_permission"

- db/migrate/20150211091009_drop_permissions_table.rb
- db/schema.rb
- test/factories/permission.rb
- test/factories/users.rb
- test/functional/authorisations_controller_test.rb
- test/functional/users_controller_test.rb
following this change: #311, user's application permissions are migrated join table instead of being stored as a serialised attribute in the permissions table.
dropping the permissions table which was kept as a backup. now that we've been running with remodelled permissions for a week and nothing's broken we should be good to clean that up.
> Drop permissions table

- app/views/shared/_user_permissions.html.erb
In some circumstances a crash could occur when viewing a user with unsynced
permissions. The precise scenario in which this could occur is if the first
permission in the users permission list was unsynced, and later ones were
synced.
In theory this should never occur because all permissions are synced at
the same time. However the association from user to application_permissions is
unordered, so the order in which the records are returned from mysql when
reading them could change arbitrarily.
The fix here is to make the display code more robust to this possible scenario.
I've also refactored the view slightly so that it's clear that only the
`<span>` label class changes according to the `sync_needed?` status.
https://www.pivotaltracker.com/story/show/88500338
> Bugfix - viewing user with unsynced permissions

- app/controllers/sessions_controller.rb
- test/integration/session_timeout_test.rb
There is a security hole in versions of Devise prior to 3.2.0, in which a logged-in user sending a `GET` request to `/users/sign_in` would have their session extended, even if it had already expired; this also doesn't record anything in the event log, as the user hasn't technically signed in again. As a side-effect of this, people who have ended up using that URL as their bookmark for Signon get sent suspension warnings, as we don't have a record of them having logged into Signon.
Given the number of Devise plugins we use, and the customisations we've made on top of them, upgrading to a patched version of Devise is sufficiently complicated that it's worth patching this version in place in the meantime, so we aren't vulnerable while working on the upgrade.
The [commit in Devise that fixes …
> Fix the Devise session extension bug in place

- lib/roles/admin.rb
- lib/roles/organisation_admin.rb
- lib/roles/superadmin.rb
These roles used to need to have `application_permissions_attributes` set
as `attr_accessible` on `User` so that they could update users' permissions
for applications. It hasn't been needed since d0df5b1b0569ffc08f04cace7e8665102188e138,
when `accepts_nested_attributes_for :application_permissions` was removed
from `User`. `:supported_permission_ids` is used instead now for updating
users' application permissions.
> Remove application_permissions_attributes from roles

- .gitignore
- Gemfile
- Gemfile.lock
This was removed in 0c1748821932755ef146f68796c270044d84ff36 because it
appeared to be unused. However the tests for gds-sso spin up signon using
an SQLite database to test against, so this gem needs to stay in the
Gemfile here. Signon itself doesn't use SQLite otherwise.
/cc @alext
> Re-add SQLite development dependency for GDS SSO build

- app/presenters/user_o_auth_presenter.rb
- test/unit/user_o_auth_presenter_test.rb
We want to move away from using slugs as they can change. content_ids are
stable.  Successfully tested in development.
> Expose the org content_id in user.json

- test/functional/passwords_controller_test.rb
- test/integration/passphrase_reset_test.rb
These tests started failing today without any changes. This seems to be because
the tests were setting the password to have expired `3.months.ago` and Devise
`expire_password_after` is set to `90.days`, which is usually but not always
the same.
Today, this is what Rails returned:
```
Loading development environment (Rails 3.2.18)
irb(main):001:0> 3.months.ago
=> Sun, 01 Feb 2015 14:24:23 GMT +00:00
irb(main):002:0> 90.days.ago
=> Sat, 31 Jan 2015 14:24:26 GMT +00:00
```
We think that the intention was for it to set the password_changed_at to be
further in the past than the expiry time, so we changed it to 91 to make it
clearer.
> Make password expiry tests more robust

- app/models/organisation.rb
- db/migrate/20150501101146_add_closed_to_organisation.rb
- db/schema.rb
- lib/organisations_fetcher.rb
- test/unit/organisation_test.rb
- test/unit/organisations_fetcher_test.rb
This makes it clearer when choosing organisations to assign to a user which
ones are plausible. An example of this is Highways Agency which has become a
different organisation called Highways England.
This could happen more when the new government is formed and organisations are
closed and created with potentially similar/confusing names.
> Display when organisations have closed

- config/initializers/devise.rb
- jenkins.sh
Part of upgrading devise.
Previous `secret_key` was auto-generated. Load the key from an environment variable instead.
> Store devise secret_key in an environment variable

- config/application.rb
- config/initializers/airbrake.rb
We already have this `params_filters` config in the Airbrake initializer in
production environments, so it should be here too for consistency. Including
`password-strength-score` in the Airbrake filter is done for consistency with
the Rails parameter filtering.
Also add a comment documenting the fact that our existing parameter
filtering for Rails logging already matches all the sensitive password
params.
> Update Airbrake params filtering to match Production

- config/locales/devise.en.yml
- test/integration/sign_in_test.rb
In order to avoid username enumeration attacks on Signon, make all error
messages on the login screen the same.
The keys were gotten from:
https://github.com/plataformatec/devise/blob/4acb5043249d6fb5636d9f066aafcb0a11ba2765/config/locales/en.yml#L12-L15
but we had previously only overridden one of them.
> Make invalid and missing error messages the same

- app/models/user.rb
- test/integration/granting_permissions_test.rb
- test/models/workers/permission_updater_test.rb
These were accidentally broken in e96e674 - see commit messages for full details.
> Fix queries using application.id on User model

- config/initializers/devise.rb
- jenkins.sh
We only really care about the secret key being an environment variable in production. Set to a default dummy value in development and test.
> Simplify setting devise secret key

- Gemfile
- Gemfile.lock
Originally Signon used this in development, but this was removed some years ago: 7b55f8dcd9c0368370738a77104d85fc1dd2fbb3. gds-sso has been using sqlite to run Signon in its integration tests, but this has now been switched to MySQL: https://github.com/alphagov/gds-sso/pull/73
The build is currently failing because the gds-sso build is failing because of a bug relating to Doorkeeper. This change is housekeeping, so can happily wait until everything else has settled before being merged.
> Remove sqlite dependency

- test/integration/authorise_application_test.rb
This test is mainly about making sure that the flow works, but we should make
sure that the authorisation isn't given when the user isn't signed in.
> Improve app authorisation test

- app/helpers/application_helper.rb
- app/policies/user_policy.rb
- spec/policies/user_policy_spec.rb
- test/controllers/users_controller_test.rb
- test/integration/email_change_test.rb
- test/integration/password_expiry_test.rb
Normal users shouldn't be able to directly change their own email address - they have to confirm the change via a link sent to the new email address (a notification is also sent to their old address).
Admins have been able to make email changes without requiring the user to confirm for some time. 
We accidentally gave normal users access to/a link to the admin-style page for themselves, which allows them to change their own email without confirmation.
By preventing their access to the full fledged edit page, we also mitigate some usability problems for normal users - it included various fields and links which would lead to the user seeing errors.
cc @jennyd @bishboria
> Prevent unverified email changes

- config/initializers/session_store.rb
This means that cookies will only be sent over encrypted connections, thus
making it harder for an attacker to read/replay someone else's session.
The secure option was accidentally removed in 0ad105f.
> Explicitly mark session cookies as "Secure"

- test/models/batch_invitation_test.rb
This was added in a385374dd4357521325dc36ae436505956a94a80 before being
commented out in c8d21b5c4828d9aa2696c6202c24e9c41636debf
> Remove some commented out code

- config/environments/production.rb
When this was removed, we stopped creating our JSON logs.
This config was accidentally deleted in 0ad105f7d7e7e692899e1f7d07cc197c903c9bbe.
> Restore logstasher config

- lib/tasks/users.rake
This rake task adds permissions to the "Content
Preview" aka authentication-proxy application for
all users who a) are not suspended and b) do not
already have it.
It also triggers a push to the application in
question to sync the permissions.
https://trello.com/c/LKNZT6qZ/185-content-preview-permissions-are-a-default-permission-in-signon
> Add rake task for granting content preview permission.

- app/views/devise/passwords/reset_error.html.erb
The previous message was also displayed if you reused the previous
password. This commit updates it to also include this possible solution
to the error.
> Clearer password reset error message

- test/controllers/users_controller_test.rb
This seems to have been accidentally introduced in:
b730700d82e5de79bc0b3004d74c7e547e7eb362
This triggered a warning in Ruby 2.2, which is where I noticed it.
> Remove duplicate hash parameters

- lib/tasks/applications.rake
As part of our migration to Carrenza we are taking
the opportunity to sort out some of our domains,
namely kill alphagov. We need to have a way to
update all signon apps redirect_uri and home_ui.
For a domain currently set to `bar.co.uk`
```
~/govuk/signonotron2(branch:add_rake_task_to_migrate_domain*) » export OLD_DOMAIN="bar.co.uk"
------------------------------------------------------------
~/govuk/signonotron2(branch:add_rake_task_to_migrate_domain*) » export NEW_DOMAIN="foobarbaz"
------------------------------------------------------------
~/govuk/signonotron2(branch:add_rake_task_to_migrate_domain*) » bundle exec rake applications:migrate_domain
Migrating Publisher - redirect_uri to new domain: https://publisher.foobarbaz/auth/gds/callback
Migrating Publisher - home_uri to new …
```
> Add rake task to migrate apps to new domain.

- config/initializers/doorkeeper.rb
- test/integration/authorise_application_test.rb
Trello: https://trello.com/c/wQufRA6Z/65-signon-client-apps-don-t-respect-passphrase-expiry
When Doorkeeper performs authentication and authorization of a user in
order to allow them access to an application, it doesn’t check whether
the user’s password is expired.
This change adds a check to the configuration of Doorkeeper, where it
will redirect the user to the passphrase expiry screen when they
attempt to access an application if required.
/cc @jamiecobbett @bradleywright
> Ensure oauth authorisation respects password expiry

- lib/tasks/applications.rake
We need a way to skip certain apps i.e. licensify 
as that is staying at the old domain name. The 
argument to skip apps is optional. If want
to skip an application the arguments are passed in
as so: 
rake applications:migrate_domain['licensify, foo']
> Add optional argument for apps not to update domain.

- db/schema.rb
There have been significant changes in the format of schema.rb since the
version of Rails (3.2.18) we were using when we last had a migration. I want to
add a migration in a branch but want to keep the changes separate.
> Re-dump schema.rb with Rails 4

- app/controllers/passwords_controller.rb
- app/models/event_log.rb
- test/integration/event_log_test.rb
Log when a user displays a password reset page and when they fail to
reset their password. This will help us diagnose if a user is indeed
attempting to reset their password and if they are failing to reset
their password. Currently we were only getting the happy case giving us
no visibility if anything had gone wrong.
> Add some more logging on password reset flows

- app/controllers/devise/two_step_verification_controller.rb
- config/initializers/instance_name.rb
- test/controllers/batch_invitations_controller_test.rb
- test/controllers/two_step_verification_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/email_change_test.rb
- test/integration/user_locking_test.rb
- test/models/noisy_batch_invitation_test.rb
- test/models/user_mailer_test.rb
For non-production environments, prefix "GOV.UK Signon" with the instance name in the issuer field of the QR code. This will show up in the description label in mobile Authenticator apps:
> Show the deployment instance name in the 2SV issuer

- app/controllers/devise/two_step_verification_controller.rb
- app/helpers/bootstrap_flash_helper.rb
- app/views/devise/two_factor_authentication/max_login_attempts_reached.html.erb
- app/views/devise/two_factor_authentication/show.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_bootstrap_flash_messages.html.erb
- config/initializers/devise.rb
- config/locales/en.yml
- test/helpers/user_helpers.rb
- test/integration/authorise_application_test.rb
- test/integration/sign_in_test.rb
- test/integration/two_step_verification_test.rb
* Tweak copy to use 2-step consistently
* Override default 2-step verification form and max requests views
* Increase max login attempt to 10 for now
* Display `flash[:error]` messages from the two_factor_authentication gem
* Track all flash messages in analytics to see how often error states happen
https://trello.com/c/eAU9Z46p/90-front-end-work-for-mvp-2sv-medium
> Improve styles of 2-step code entry and locked account pages

- config/initializers/devise.rb
- test/integration/passphrase_reset_test.rb
This reverts commit 41c1e1edf410f46b8239bf89e9c3156a974c33b2 as per https://trello.com/c/0WvaVtE6/109-undo-adding-sign-in-screen-after-successful-passphrase-reset.
This is being reverted because as part of the wider 2SV story, we will be requiring 2SV for users before they can reset their password. Thus, forcing them to be logged out on a successful password reset would mean they'd have to enter a 2SV code twice.
/cc @fofr
> Revert "Don't automatically log users in after password reset"

- app/controllers/users_controller.rb
- app/models/user.rb
- app/presenters/user_export_presenter.rb
- lib/devise/models/password_expirable.rb
- test/models/user_export_presenter_test.rb
- test/models/user_test.rb
Trello: https://trello.com/c/AbFXHJ5u/104-504-timeout-when-trying-to-download-a-csv-of-signon-users-medium
The "Export as CSV" button in signon will generally result in a 504 in production due to it taking over 15 seconds to generate the CSV (actually around 10 minutes on a VM). This is mostly avoidable by fetching data in more optimised ways rather than relying on ActiveRecord's association magic.
CSVs with no filtering are now returned in around 4 seconds on a VM, which should be quick enough.
This pull request best reviewed commit by commit.
Possible future refactoring would be to pass a scope of users into the presenter and have it generate the CSV itself.
> Speed up slow user export functionality

- app/controllers/devise/two_step_verification_controller.rb
- lib/devise/hooks/two_step_verification.rb
- test/integration/sign_in_test.rb
This was missed in the removal of the two_factor_authentication gem
from this repo.
This also improves upon the security of the original implementation by
verifying user id and expiration, making it impossible to copy the
value of the signed gem and re-use it later, extend the expiration
period, or use your cookie for another user.
/cc @jamiecobbett
> Add 2SV session memory

- config/initializers/sidekiq.rb
This change replaces the development sidekiq initialiser with the production one.
Taking the redis URL from the environment will allow to have one common
config and not replace the initializer in 'alphagov-deployment'.
This can be safely merged now because for the time being, `config/initializers/sidekiq.rb` is still being replaced during deployment.
> Consolidate the Sidekiq config with production

- app/controllers/suspensions_controller.rb
- app/helpers/bootstrap_flash_helper.rb
- app/views/shared/_bootstrap_flash_messages.html.erb
- test/integration/manage_api_users_test.rb
https://trello.com/c/kEt8UXfz/129-personally-identifiable-information-in-google-analytics-medium
Don’t pass user email address to Google Analytics. Replace with “[email]”. This is the same pattern as used by the Support app.
Update a single flash message to use emails rather than names to
* be consistent with other flash messages
* allow personal information to be redaction
* make it easier for a user to follow up with a message to the suspended/unsuspended user
> Redact email addresses from analytics

- config/initializers/restrict_parsers.rb
This app is on Rails 4, which doesn't configure the XML parser by default.
The JSON parser is deemed safe, and having it configured is the Rails 4 default.
There's no obvious reason to deviate from the default for this app.
Also see: https://github.gds/gds/alphagov-deployment/pull/1080
> Don't remove default parsers

- app/controllers/devise/two_step_verification_controller.rb
- app/controllers/sessions_controller.rb
- app/mailers/user_mailer.rb
- app/models/event_log.rb
- app/models/user.rb
- app/views/devise/_links.erb
- app/views/devise/two_step_verification/max_2sv_login_attempts_reached.html.erb
- app/views/user_mailer/unlock_instructions.html.erb
- app/views/user_mailer/unlock_instructions.text.erb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- db/migrate/20151001095709_add_unlock_token_to_users.rb
- db/schema.rb
- test/integration/event_log_test.rb
- test/integration/sign_in_test.rb
- test/models/user_mailer_test.rb
https://trello.com/c/LYxVsMEb/114-unlocking-after-too-many-2sv-attempts-medium-ish
This is an implementation of the locking/unlocking requirement which piggy-backs on the devise locakble module. Instead of maintaining a separate locking behaviour for 2SV, we re-use the `User#lock_access!` and `User#unlock_access!` methods. 
This also refactors the locked account email to use the Devise unlock instructions built in email, reducing app-specific complexity. This requires setting up an unlock token for a user, but this isn't currently exposed in the email, so isn't usable by the user.
The potential downside to this method is that the user is locked out completely from logging in, if they enter 2SV incorrectly too many times, they are sent back to the email / passphrase screen. When they enter …
> Unlocking after too many 2SV attempts

- Gemfile
- app/controllers/application_controller.rb
- app/controllers/devise/two_step_verification_controller.rb
- app/controllers/passwords_controller.rb
- app/controllers/sessions_controller.rb
- app/models/event_log.rb
- app/models/user.rb
- app/policies/user_policy.rb
- app/views/devise/two_step_verification/prompt.html.erb
- app/views/users/_form_fields.html.erb
- config/initializers/doorkeeper.rb
- config/routes.rb
- db/migrate/20150928115351_add_requires2sv_to_users.rb
- db/migrate/20150929135437_rename_users_requires2sv.rb
- db/migrate/20151006091244_add_deferred2sv_at_to_users.rb
- db/schema.rb
- lib/roles/superadmin.rb
- spec/policies/user_policy_spec.rb
- test/factories/users.rb
- test/integration/authorise_application_test.rb
- test/integration/inviting_users_test.rb
- test/integration/two_step_verification_prompt_test.rb
- test/integration/two_step_verification_test.rb
- test/models/user_test.rb
Provides the ability for super admins to flag users as requiring 2SV. Once they've been flagged they will be prompted to complete 2SV enrolment and cannot do much until they enrol or defer.
> Flag for 2SV

- app/views/devise/two_step_verification_session/new.html.erb
The hint about where to find your verification code should be linked to the input.
> Add aria-described-by for 2-step code input

- app/controllers/devise/two_step_verification_controller.rb
- app/models/event_log.rb
- app/models/user.rb
- app/views/devise/two_step_verification/show.html.erb
- app/views/root/index.html.erb
- config/locales/en.yml
- config/routes.rb
- test/controllers/two_step_verification_controller_test.rb
- test/integration/two_step_verification_test.rb
This merges the existing create flow with the update flow, as it’s not
currently possible to add 2SV devices, only replace them. The result is
the update of the user’s OTP key, either from nil to a valid key thus
setting up 2SV, or from an old key to a new one, thus changing the
device they’ve got set up.
The same form is displayed for both cases, the differences are in the
text of the logged event, and the flash messages on success. The flows
are differentiated by the presence of the `otp_secret_key` on the user.
This commit also refactors the controller action responsible for
updating the secret by extracting the logic to verify the entered code
and update the secret.
/cc @fofr @jamiecobbett @benlovell
> Add ability for users to change the device used for 2SV

- app/controllers/devise/two_step_verification_session_controller.rb
- lib/devise/hooks/two_step_verification.rb
- test/integration/two_step_verification_test.rb
Adding a hash of the secret key into the signed 2SV session cookie
means that if a user changes their 2SV device, they will need to enter
their new code on subsequent logins on all devices.
/cc @benlovell @jamiecobbett @benilovj
> Key the 2SV session cookie on a hash of the secret

- lib/devise/hooks/two_step_verification.rb
- test/integration/sign_in_test.rb
Actually check the result of `user.need_two_step_verification?` instead
of checking if we have the method on the user. This was left over from
the `two_factor_authentication` gem’s implementation of the hook, and
wasn’t replaced.
This was causing errors when users had a 2SV session cookie but then
had their secret key reset. Hashing `nil` causes an error. If we check
`need_two_step_verification?` first, we can bypass this.
/cc @jamiecobbett
> Don't try to validate 2SV session cookie if 2SV not enabled

- lib/tasks/applications.rake
If this job is run multiple times then redirects risk ending up
incorrect:
```
Migrating Specialist publisher - redirect_uri to new domain:
https://specialist-publisher.staging.staging.publishing.service.gov.uk/auth/gds/callback
```
Note the inclusion of `staging` twice in the URL.
This change seeks to fix that even if the job is run multiple times.
> Bugfix: data-sync-complete job

- README.md
We call the app “Signon” (one word, no hyphens at the moment).
> Remove `o-tron` references from readme

- app/controllers/devise/two_step_verification_session_controller.rb
- test/integration/sign_in_test.rb
This controller wasn’t protected from unauthenticated users, meaning
that if a user landed on the page without a session their
`current_user.authenticate_otp` call would fail, causing an error. The
correct behaviour is to redirect the user to the login path.
We have to use `force: true` in this call because the controller is a
Devise controller, which are excluded from authentication by default.
> Protect the 2SV session controller from unauthed users

- app/helpers/analytics_helper.rb
- app/views/devise/password_expired/show.html.erb
- app/views/devise/passwords/_change_password_errors.html.erb
- app/views/devise/passwords/_change_password_panel.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/two_step_verification/show.html.erb
- app/views/shared/_bootstrap_flash_messages.html.erb
- app/views/users/_form_errors.html.erb
- app/views/users/edit_email_or_passphrase.html.erb
- test/helpers/passphrase_support.rb
- test/integration/event_log_test.rb
Collect anonymous metrics on the different types of user error when they’re changing their email or passphrase, or when setting up 2-step verification.
* Add a helper for tracking messages in analytics
* Start tracking the error messages in analytics
This also includes some improvements to the passphrase change forms:
* Avoid using the default devise error message. The default includes a poor heading and old markup. The default can be found here: https://github.com/plataformatec/devise/blob/7df57d5081f9884849ca15e4fde179ef164a575f/app/helpers/devise_helper.rb
* Consolidate errors into a new partial
* DRY up form by moving submit button into partial
cc @boffbowsh @jamiecobbett
> Improve error messaging and track user errors on forms to Google Analytics

- app/controllers/passwords_controller.rb
- test/integration/event_log_test.rb
Currently on 2nd line, there's a Zendesk ticket from someone who is having trouble resetting their password:
> it just comes up with the message that I may of used the password before (which I definitely haven’t) or that the link is old even though I have just received the link
We'd like to investigate, but the account access log just displays:
`11:56am, 28 Oct 2015	 Passphrase reset attempt failure`
Which isn't very helpful, as there can be multiple different causes for the user to not be `valid?` ([see the controller](https://github.com/alphagov/signonotron2/blob/c581c8afc4cb09058a3c653c9aa49f604dec2fb6/app/controllers/passwords_controller.rb#L17)). 
By adding the activerecord error messages to `trailing_message` we can get a lot more information and can help users better.
Discuss:
> Add password reset error to event log

- app/controllers/devise/two_step_verification_controller.rb
- test/controllers/two_step_verification_controller_test.rb
This change resolves issues seen in the production environment over the past
few days when a user attempts to defer 2SV, but after their session has
expired.
> Resolve attempted unauthenticated access

- app/models/user.rb
- test/models/user_test.rb
Rather than rely on `require_2sv_changed?` (rails' standard dirty
checking for the `require_2sv` attribute) and `two_step_flag_changed?`
(based on `require_2sv_changed?` but can survive persistence
round-tripping) to determine whether to send the flagging notification,
we can simply check - has the user actually been flagged and was the
flag toggled just now?
> Fix 2SV flag notification logic

- app/models/user.rb
- test/helpers/user_helpers.rb
- test/integration/admin_user_index_test.rb
- test/integration/authorise_application_test.rb
- test/integration/batch_inviting_users_test.rb
- test/integration/dashboard_test.rb
- test/integration/email_change_test.rb
- test/integration/event_log_test.rb
- test/integration/granting_permissions_test.rb
- test/integration/inviting_users_test.rb
- test/integration/manage_api_users_test.rb
- test/integration/passphrase_change_test.rb
- test/integration/passphrase_expiry_test.rb
- test/integration/passphrase_reset_test.rb
- test/integration/session_timeout_test.rb
- test/integration/sign_in_test.rb
- test/integration/sign_out_test.rb
- test/integration/super_admin_flagging_two_step_verification_test.rb
- test/integration/super_admin_reset_two_step_verification_test.rb
- test/integration/superadmin_application_edit_test.rb
- test/integration/two_step_verification_prompt_test.rb
- test/integration/two_step_verification_test.rb
- test/integration/user_link_test.rb
- test/integration/user_locking_test.rb
- test/integration/user_status_test.rb
- test/integration/user_suspension_test.rb
- test/models/user_test.rb
- test/test_helper.rb
https://trello.com/c/Xh7kLY4z/150-prompting-all-current-and-future-admins-and-super-admins-to-set-up-2sv-in-production-only-small
When a user is promoted to an admin or superadmin, they should have the `require_2sv` flag set.
This new behaviour caused a lot of tests to break, so first the test authentication helpers were refactored to make this transition easier.
Best reviewed commit-by-commit.
> Prompt future admins and superadmins to set up 2SV

- app/models/user.rb
- app/views/devise/two_step_verification/prompt.html.erb
- test/models/user_test.rb
The trigger for sending an email is the `require_2sv` flag turning
true, captured by the `mark_two_step_flag_changed` callback. Setting
`require_2sv` first for admin and superadmin promotion means the
notification flag is set correctly.
> Ensure users are emailed about 2SV on promotion

- app/controllers/devise/two_step_verification_controller.rb
- test/integration/two_step_verification_test.rb
When you sign in, we allow codes from devices which have a time which lags
behind the time on the server. This is because user devices are frequently
not automatically updated with the correct time.
This fixes a bug where we didn't allow codes from such devices at setup time.
> Allow time drift when setting up 2SV

- Gemfile
- Gemfile.lock
- app/controllers/users_controller.rb
- app/models/event_log.rb
- app/models/user.rb
These validations were being silently ignored. To workaround the broken
behaviour we generate the `uid` earlier in the lifecycle, ensure
validations fail loudly via `create!` and move the event logging for
'successful passphrase change' to the correct place.
Once the `uid` was being set (thus passing validation) this event was being
logged continually, whereas before it would fail silently.
> Run `EventLog` validations

- app/models/event_log.rb
- app/models/log_entry.rb
- db/migrate/20151112110911_add_event_id_to_event_logs.rb
- db/schema.rb
- test/controllers/confirmations_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/event_log_test.rb
- test/integration/sign_in_test.rb
- test/integration/two_step_verification_test.rb
- test/models/event_log_test.rb
- test/models/user_test.rb
Trello: https://trello.com/c/zjBz0vTu
Declare and persist events by identifiers, rather than by their string
representations.
These changes will allow the `event_id` and `event` attributes/columns
to coexist until such time a migration is ran to convert the existing
`event` column values to their respective `event_id`s.
Some of the changes to support this:
* Override `event` reader and attempt to map message via `EVENTS`
* Add the `event_id` attribute for persistence
* Default `event` to an empty string so it is no longer mandatory
* Don't validate `event` when an `event_id` is provided
* Fixup broken specs that referred to the `event` directly
* Removed a redundant spec that was well covered elsewhere
* Validate presence of `event_id`
* Ensure `event_id` corresponds with `EVENTS` entry
A …
> Log and persist events by ID

- lib/event_id_populator.rb
- lib/tasks/event_logs.rake
- test/integration/populate_event_ids_test.rb
Opening this in favour of #440.
Simple rake tasks to populate the newly created `event_id` column via mappings from `event`.
> Populate `event_id` from existing `event`

- app/mailers/user_mailer.rb
- app/models/user.rb
- app/views/user_mailer/two_step_enabled.html.erb
- app/views/user_mailer/two_step_enabled.text.erb
- test/integration/two_step_verification_prompt_test.rb
- test/models/user_mailer_test.rb
- test/models/user_test.rb
https://trello.com/c/2xcA8uQT/173-change-preview-only-2sv-and-wider-signon-behaviour-to-include-new-integration-environment
A new integration environment is being introduced to eventually replace
preview, so logic is being switched to only auto-flag users in
production environment.
This behaviour should eventually be controlled by a specific
configuration variable in line with 12 factor, but we need to get this
updated quickly in order to work with the new environment.
Additionally, this now depends on `instance_name` directly in line with
other logic in this app. For production, `instance_name` is `nil`.
> Auto-flag adminish users for 2SV in production only

- app/models/event_log.rb
- config/initializers/warn_on_unguarded_column_removals.rb
- lib/deprecated_columns.rb
- test/db/warn_on_unguarded_column_removals_test.rb
Adds the deprecated columns macro from alphagov/whitehall. This allows
a grace period when making subtractive schema changes.
I'll come back and extract this behaviour into a gem to be reused from both
this application and alphagov/whitehall.
> Add deprecated columns macro

- Gemfile
- Gemfile.lock
This addresses vulnerabilities in libxml2:
CVE-2015-1819
CVE-2015-7941_1
CVE-2015-7941_2
CVE-2015-7942
CVE-2015-7942-2
CVE-2015-8035
CVE-2015-7995
> Upgrade Nokogiri to 1.6.6.4

- db/migrate/20151202120153_add_default_to_event_logs_event.rb
- db/schema.rb
This allows us to stop referencing the event field completely within
our Rails code before dropping it.
This only changes the metadata of the table, doesn’t lock it and
completes within a few milliseconds so is safe to do as part of a
migration.
/cc @benlovell
> Add a default empty string to event_logs.event

- db/migrate/20151203161459_remove_event_column.rb
- db/schema.rb
Removes the now redundant `event` column, as this has been superseded by
the `event_id` and virtual `event` attribute and mapping.
/cc @benlovell
> Remove `event` column

- app/controllers/doorkeeper_applications_controller.rb
- app/policies/application_policy.rb
- app/views/doorkeeper_applications/edit.html.erb
- app/views/doorkeeper_applications/users_with_access.html.erb
- config/routes.rb
- spec/policies/application_policy_spec.rb
- test/integration/superadmin_application_users_test.rb
Team Finding Things has created a new app (Content tagger). People who have access to Panopticon should also have access to this app.
The process of providing access will be greatly helped by having a list of users that have access to panopticon. This PR adds a page for each application that lists the users that (in the past) have had access to an app.
When there are more than 100 users, pagination will be shown.
Trello: https://trello.com/c/pWDaETqu
> Allow superadmins to see users for app

- app/views/root/index.html.erb
- test/factories/users.rb
- test/integration/admin_user_index_test.rb
- test/integration/dashboard_test.rb
- test/integration/super_admin_reset_two_step_verification_test.rb
- test/models/user_export_presenter_test.rb
- test/models/user_test.rb
Displays the correct links depending on the current user's 2SV enrollment.
This opens 2SV up to all users on an opt-in basis.
> Display 2SV set up/change device links

- app/helpers/application_helper.rb
- app/helpers/bootstrap_flash_helper.rb
- app/views/layouts/application.html.erb
- test/units/helpers/application_helper_test.rb
I wasn't able to find a way of testing the behaviour without changing govuk_admin_template so that it renders the Google Analytics code in test mode - currently it only renders in production mode. The unit tests of the helpers were the best I could do. One alternative would be to stub the calls to `content_for`, but this seems very unpleasant. I'm open to suggestions.
> Scrub passphrase reset tokens from Google Analytics

- Gemfile
- Gemfile.lock
- app/helpers/application_helper.rb
Addressable was only being loaded as a test dependency,
but being used in runtime code. This meant that the gem
was not being required in production, and uses of
`Addressable::URI` were resulting in errors.
/cc @benlovell
> Make addressable an explicit dependency of signon

- config/environments/production.rb
To bring this more in line with 12-facgtor principals, this changes the
logging to go to STDOUT(json), and STDERR(everything else).
Prior art:
https://github.com/alphagov/government-frontend/pull/80
https://github.com/alphagov/publishing-api/pull/109
Related puppet change: https://github.com/alphagov/govuk-puppet/pull/4023
> Log to STDOUT and STDERR in production mode

- config/environments/test.rb
- config/locales/en.yml
Found this missing translation.
Have a separate commit for enabling errors when running tests so that it can be excluded depending on preference.
> Broken translation

- app/views/layouts/application.html.erb
- config/initializers/govuk_admin_template.rb
Since c79a5143d7dfcd8dd02e3913980cef879e269b2a, we were using Rails' I18n to
set the GovukAdminTemplate.app_title in an initializer. Unfortunately, whilst
the I18n code is available, it hasn't been configured at the time intializers
are loaded. This meant that users saw this in the page header:
```
translation missing: en.department.name Signon
```
The tests didn't fail because the setting to make missing translations raise
errors (in config/environments/test.rb) is also loaded after initializers.
> Fix app_title display translation missing

- config/initializers/devise.rb
- test/integration/batch_inviting_users_test.rb
- test/integration/passphrase_reset_test.rb
Since ec36b330c44eecc9b345dccdd6daaf25f0a585bc, we have used I18n to get the
email_from value. Because initializers are loaded before I18n has been
configured with a load path, when the Devise.config.mailer_sender was set, it
received an I18n translation missing message, instead of the email address
string. This was then apparently used by Devise to set the Reply To field and
probably the From field.
When UserMailer and NoisyBatchInvitation mailer call I18n, it has had a load
path set and so override the From field with correct/valid values, but the
Reply To field isn't.
The result was that emails were probably being rejected either by our email
sending service (Amazon SES) or elsewhere, so emails weren't being sent to
users.
Reading the comment for Devise.config.mailer_sender, it isn't …
> Fix emails not being sent

- app/controllers/passwords_controller.rb
- app/models/event_log.rb
- test/integration/event_log_test.rb
It would be useful to see when users are trying to use expired tokens.
Note that we can't log when a user tries to use a token from a passphrase reset
request that has been followed by another passphrase reset request. This is
because we can't relate the token to a user, because it is overwritten.
> Record when a passphrase reset page is visited with expired token

- .agignore
Anytime I search this project the dictionary file comes up with hits
and this is annoying and wasteful.
> Ignore dictionary file when searching via `ag`

- test/controllers/batch_invitations_controller_test.rb
- test/controllers/two_step_verification_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/email_change_test.rb
- test/integration/sign_in_test.rb
- test/integration/user_locking_test.rb
- test/models/noisy_batch_invitation_test.rb
- test/models/user_mailer_test.rb
Remove department specific names from test suit to allow test to pass when an alternative department name is used.
> Make tests agnostic of department name, email, etc.

- Gemfile
- Gemfile.lock
- app/helpers/analytics_helper.rb
- app/helpers/application_helper.rb
* Pick up change to automatically strip email addresses from all event actions and labels: https://github.com/alphagov/govuk_admin_template/pull/121
* Remove now redundant email substitution.
https://trello.com/c/0SLWcJwI/337-strip-personally-identifiable-information-before-sending-to-analytics-medium
> Bump admin gem to 4.2.0

- app/views/devise/two_step_verification_session/max_2sv_login_attempts_reached.html.erb
- app/views/user_mailer/notify_reset_password_disallowed_due_to_suspension.html.erb
- app/views/user_mailer/notify_reset_password_disallowed_due_to_suspension.text.erb
- app/views/user_mailer/suspension_notification.html.erb
- app/views/user_mailer/suspension_notification.text.erb
- app/views/user_mailer/unlock_instructions.html.erb
- app/views/user_mailer/unlock_instructions.text.erb
Email was stating that managing editors can un-suspend and unlock
accounts. Managing editors don't have this permission.
Updated to say that they can use the support form only.
Re-opening @lutgendorff’s PRs (#486 – #491) as a single commit and pull request.
> Update managing editors copy in emails

- db/migrate/20160420145549_remove_appointed_person_for_england_and_wales_organisation.rb
- db/schema.rb
This org was created in error and we are removing it.  The traffic is very low so we're not issuing a 410, just removing it (it should never have existed so a 404 is really what we want).
This is PR 5 of 5 for removing this org.
For more detail: https://trello.com/c/jbImjyLP/359-delete-an-org-page-5
> Migration to remove an org created in error

- test/models/inactive_users_suspension_reminder_test.rb
Some bugs have been reported regarding suspension notifications, adding regression tests here to ensure that we're testing for all reminders.
> Add tests for all suspension reminders

- app/presenters/usage_presenter.rb
- lib/tasks/export_usage_stats.rake
Produce a Signon report broken down by:
- the number of active and suspended editors
- organisation (as we define this in Whitehall document filtering)
- month (e.g. from the start of January 2015 to end of January 2016)
This can be generated via a rake task.
The dates can be customized as inputs from command line, e.g.:
`bundle exec rake export_usage_stats[2015-01-01,2016-01-31]`
> Create Signon Users Analytics

- Gemfile
- app/controllers/users_controller.rb
- test/controllers/users_controller_test.rb
It is now possible for a user to have a Signon account but not to have
access to any applications. Previously at least one application needed
to be selected.
In response to this [Zendesk ticket](https://govuk.zendesk.com/agent/tickets/1345740).
> Allow a user to have no application access

- lib/organisations_fetcher.rb
- test/models/organisations_fetcher_test.rb
The API can return an organisation with a `slug` that matches one we already know about, however the `content_id` may differ from the one we hold locally. This can happen if within the API the organisation has been destroyed and then recreated with the same `slug`. In this instance the organisation is assigned a new `content_id` by the API and causes a conflict with our internal representation when we try to sync.
> Update OrganisationFetcher to handle recreations

- config/application.rb
- config/initializers/session_store.rb
- lib/same_site_security/middleware.rb
- spec/features/cookies_security.rb
- spec/unit/same_site_security/middleware.rb
Trello: https://trello.com/c/DlBVF1KZ/426-improve-signon-cookie-security-small
Set the HttpOnly, Secure and SameSite=lax attributes for cookies, so 2-step-verification cookies could not be stolen by a man-in-the-middle attacker.
> Improve cookies security

- config/initializers/devise.rb
Previously, users would be automatically logged in once they had reset
their password. This had the effect of allowing users to bypass 2SV by
requesting a password reset.
Forcing users to sign in after they’ve reset their password closes this
loophole.
This feature didn't exist when 2SV was originally implemented.
> Force users to sign in after resetting password

- lib/tasks/users.rake
- lib/user_permission_migrator.rb
- spec/unit/user_permission_migrator_spec.rb
https://trello.com/c/gDbYr06M/272-amend-signon-for-separation-of-finders-and-manuals-large
Adds a task to migrate permissions for users between a source and target application.
We need to do this to copy Specialist Publisher user permissions into Manuals Publisher but it should work for any pairs of applications with the same permission names.
> Add permissions migration task

- app/views/doorkeeper_applications/index.html.erb
`home_uri` is an optional field so don't link to it if it doesn't exist.
Fixes #247.
> Only link to an app's `home_uri` if it exists

- app/views/devise/passwords/reset_error.html.erb
[Trello card](https://trello.com/c/uviL5BFo/41-add-google-analytics-tracking-to-invalid-passphrase-reset-link-error-message)
Unlike many of the other sign-in and password editing pages, this particular journey was not being recorded in our analytics.
> Record invalid password reset page in analytics

- app/controllers/users_controller.rb
- app/models/event_log.rb
- test/controllers/users_controller_test.rb
- test/models/event_log_test.rb
This adds event log entries like:
> Role changed by Alex Muller from admin to superadmin
Which is helpful when looking at compromised accounts.
Fixes #299.
> Record role changes in the event log

- db/migrate/20170110171851_remove_share_sale_publisher.rb
Amend this migration to call `delete` and not `destroy` as this [doesn't work as expected despite the examples given in the documentation](https://github.com/ActsAsParanoid/acts_as_paranoid#real-deletion). The migration has only run on integration hence the amendment.
> (Soft) delete Share Sale Publisher

- test/jobs/permission_updater_test.rb
- test/test_helper.rb
This fixes a couple of instances where tests were poorly isolated and failing randomly. Tracked down using the [`minitest-bisect`](https://github.com/seattlerb/minitest-bisect) gem.
> Fix random test failures

- app/controllers/doorkeeper_applications_controller.rb
- app/models/enhancements/application.rb
- app/views/doorkeeper_applications/edit.html.erb
- app/views/doorkeeper_applications/index.html.erb
- app/views/shared/_user_permissions.html.erb
- db/migrate/20170216105512_add_retired_to_applications.rb
- db/schema.rb
- test/integration/superadmin_application_edit_test.rb
- test/models/doorkeeper_application_test.rb
This adds a checkbox to the application edit page that allows users to mark the application as "retired". It's intentionally non-destructive and reversible.
It's an alternative to the soft-deletion https://github.com/alphagov/signon/pull/527 (reverted in https://github.com/alphagov/signon/pull/530 because it didn't work as expected).
Part of https://trello.com/c/dGPNmVub/482-retire-panopticon
> Allow retirement of applications 

- script/make_oauth_work_in_dev
This commit changes the signon munging script for the development VM, which is run automatically at the end of data replication.
* Introduces support for contacts-admin due to the mismatch between the app name and repo name
* Reads OAuth credentials from the environment variables set by puppet, falling back to the existing behaviour of reading from each app’s `gds-sso` config file
* Fixes the munging of app URLs by looking for the new integration domain name
* Ignores retired applications since these typically have their OAuth config removed
> Fix the signon munging script for development

- script/prepare_training_environment
This commit adds a script that prepares the development VM to act as a training environment by creating applications, organisations, users and permissions.
> Add script to prepare training environment

- script/prepare_training_environment
This commit amends the `prepare_training_environment` script to also grant `signin` permissions to the API users it creates, otherwise they can’t access anything.
> Add “signin” permission to training API users

- app/models/user.rb
- test/models/user_test.rb
Before this functionality was added, the following would happen:
1. User reaches inactivity time and gets automatically suspended at 5am
2. User is unsuspended but doesn't yet log in
3. User gets re-suspended at 5am the next day
This grace period was originally set at 3 days to combat this. However
it causes issues where people are off a day either side of a weekend
and is still generating repeat tickets. We’re going to try 7 days to
see if it reduces the number of support requests we receive.
> Extend grace period for newly unsuspended users

- app/views/user_mailer/suspension_notification.html.erb
- app/views/user_mailer/suspension_notification.text.erb
- app/views/user_mailer/suspension_reminder.html.erb
- app/views/user_mailer/suspension_reminder.text.erb
Whitehall Publisher and Licensing are 2 applications which we're specifically trying to improve or replace, so constantly telling our users about them by email is confusing.
Also https://insidegovuk.blog.gov.uk/2016/07/20/changes-to-the-style-guide-no-more-eg-and-ie-etc/
> Remove references to old GOV.UK applications

- app/controllers/users_controller.rb
- app/policies/batch_invitation_policy.rb
- app/policies/organisation_policy.rb
- app/policies/user_policy.rb
- app/views/users/_form_fields.html.erb
- spec/policies/batch_invitation_policy_spec.rb
- spec/policies/organisation_policy_spec.rb
- spec/policies/user_policy_spec.rb
- test/controllers/invitations_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/batch_inviting_users_test.rb
For: https://trello.com/c/B4Y7e22o/164-self-service-or-devolved-unlock-spike
Our goal is to increase the number of org admins there are so we can increase the number of people that can do simple user support requests.  Before this change: Org admins are basically admins who are limited in scope to just users in their org (or sometimes their org and it's children, grandchildre, etc..).  After this change: org admins can no longer create new users (directly or via batch invite), see a list of organisations, affect users in their subtree - they can only affect users that belong directly to their org.
The existing org admins (there are 7) have been spoken to and none have an issue with the restriction of their permissions.
> Change what organisation admins can do

- script/prepare_training_environment
This commit changes the URLs used for the `prepare_training_environment` script from `dev.gov.uk` to `training.publishing.service.gov.uk`.
> Fix URLs for training environment

- app/policies/supported_permission_policy.rb
- app/policies/user_permission_manageable_application_policy.rb
- app/services/user_update.rb
- lib/supported_permission_parameter_filter.rb
- lib/user_permissions_controller_methods.rb
- spec/policies/supported_permission_policy_spec.rb
- spec/policies/user_permission_manageable_application_policy_spec.rb
- test/integration/granting_permissions_test.rb
- test/services/user_update_test.rb
For: https://trello.com/c/uT9YI5mR/188-devolve-unlock-resetting-permissions
After rolling out org-admin permissions to more people (see #555) we had some reports that saving a user as an org admin was resetting their permissions.  Turns out this is a long-standing bug that we didn't know about because we didn't have many org admins.  When updating a user the `UserUpdater` sets their `supported_permission_ids` to whatever is passed in.  When presenting a user to a superadmin or admin user we show the complete set of permissions and submit the selected ones.  Meaning that the `UserUpdater` is given the full set of permissions that the user should be granted.  When presenting a user to an org admin however, we show a limited set of permissions based on the apps that the org admin has access …
> Stop org admin editing a user clearing non delegatable permissions

- app/policies/user_policy.rb
- lib/roles.rb
- lib/roles/admin.rb
- lib/roles/base.rb
- lib/roles/normal.rb
- lib/roles/organisation_admin.rb
- lib/roles/superadmin.rb
- spec/policies/user_policy_spec.rb
For: https://trello.com/c/Cvttl8Sx/209-can-org-admins-unsuspend-other-org-admins
Following a request from an org admin to be able to unsuspend other org admins (from their own org), we are now increasing the level at which org admins are allowed to operate.
Previously, they were only allowed control on `normal` users, without being able to manage other org admins. This is not true for superadmins, where they can edit users with the same role.
> Allow org admins to edit other org admins

- app/controllers/users_controller.rb
- app/views/shared/_user_permissions.html.erb
- app/views/users/_app_permissions.html.erb
- app/views/users/_form_fields.html.erb
- lib/user_permissions_controller_methods.rb
- test/controllers/users_controller_test.rb
For: https://trello.com/c/oEW7PsNs/192-devolve-unlock-ability-to-see-permissions
This will allow organisation admins to see all the permissions for a user, instead of seeing only the applications and permissions that the organisation admin has access to.
> Add access permissions list on edit user page for org admins

- Gemfile
- Gemfile.lock
- app/controllers/invitations_controller.rb
- app/controllers/sessions_controller.rb
- app/models/event_log.rb
- app/models/user.rb
- app/models/user_agent.rb
- app/views/users/event_logs.html.erb
- db/migrate/20170905111153_create_user_agents.rb
- db/migrate/20170906090625_add_ip_address_and_user_agent_id_to_event_log.rb
- db/schema.rb
- test/integration/event_log_test.rb
- test/integration/user_agent_test.rb
- test/models/event_log_test.rb
- test/models/user_agent_test.rb
For: https://trello.com/c/Lf1TWggV
Ip address and browser of user is now recorded on each successful
sign in. 'browser' gem is used to retrieve the browser that the
user is using to sign in.
When a new user account is created by an existing admin, the new
account has a record of who it was invited by.
These extra logging should make it easier to retroactively
trace user behaviour in the case of an incident.
> Add extra info in account access logs

- Gemfile
- Gemfile.lock
- db/migrate/20170905111153_create_user_agents.rb
- db/migrate/20170908160100_add_ip_address_and_user_agent_id_to_event_logs.rb
- db/schema.rb
Event logs table has has two new columns for storing ip addresses
and foreign key user_agent_id, which references a new user agent
table. These two tables will be used together to display extra
logging information of a user signing in. Gem 'lhm' is used to
perform the migration without locking the database, which is
necessary as the event logs table has over 18M records.
Follows on from #565
> Add user agent table and new columns to event logs table

- Gemfile
- Gemfile.lock
- app/controllers/invitations_controller.rb
- app/controllers/sessions_controller.rb
- app/models/event_log.rb
- app/models/user.rb
- app/models/user_agent.rb
- app/views/users/event_logs.html.erb
- test/integration/event_log_test.rb
- test/integration/user_agent_test.rb
- test/models/event_log_test.rb
- test/models/user_agent_test.rb
For: https://trello.com/c/Lf1TWggV/211-log-more-information-for-signon-events
This resurrects #563 without the migration that we did separately in #566.  The original migration required us to add columns to the `event_logs` table which in production had ~18 million rows.  Adding columns would lock the table and make the app unusable while it completed.  The version in #566 used the [`lhm`](https://github.com/soundcloud/lhm/) tool to do an "online" schema change that results in no downtime.  We've deployed that migration so now we're ready to deploy the code that uses these fields.
Our ultimate goal here is to store ip address and user agent info against sign in attempts, and to store a handful of extra events that will be useful for GDPR compliance.
> Track more details in event logs

- db/migrate/20170926101024_model_hmcts_org_structure.rb
- db/schema.rb
For: https://trello.com/c/c3d52nTH/228-model-hmcts-correctly-within-signon
Checks that the ancestry for HMCTS is modeled correctly. If it finds that some of HMCTS' children are not properly assigned, it re-assigns them.
| Parent                         | Children                             |
| ------------------------------ | ------------------------------------ |
| HM Courts & Tribunals Service  | Bankruptcy Court                     |
|                                | First-tier Tribunal (Mental Health)  |
|                                | ...                                  |
Also, "HM Courts Service" was a closed organisation with no parent. It will now be assigned to "HM Courts & Tribunals Service" together will all its other children. 
Building on the work of devolving …
> Model HMCTS correctly within Signon

- app/views/users/_form_fields.html.erb
- db/migrate/20171005140101_assign_apha_org_to_new_parent.rb
- db/schema.rb
For: https://trello.com/c/GwkV3LWw/262-super-org-admin-tweaks
This will add a description under the role dropdown on the edit user page. It describes what org admins and super org admins can do.
> Add role descriptions for (super) org admins

- db/migrate/20171017152038_add_short_url_manager_permission.rb
- db/schema.rb
The functionality to receive notifications when a new short URL is
requested was split off into the new `receive_notifications`
permission in https://github.com/alphagov/short-url-manager/pull/99.
This migration creates the permission and assigns it to
all users who have the `manage_short_urls` permission.
> Add new short-url-manager permission.

- app/controllers/passwords_controller.rb
Always log the validation errors when a password reset fails. Before, these were only being logged if the user's details had been persisted to the database. I suspect this was never true, because the record had just failed validation and so was never in a persisted state when this check was run.
We're currently trying to debug why a user cannot log into Signon, and these event logs are missing even though the user has reported validation errors and we can see that they have visited the password reset page.
It's not clear from the original commit (fe7ff13) why this check was necessary.
> Fix logging of password reset failures

- app/views/user_mailer/email_changed_notification.html.erb
The email tells you that "You should follow the instructions sent to your new email address". This refers to your new, unconfirmed email address, not your current one.
cc @tuzz
> Fix wording of email change notification

- db/migrate/20171006133438_cleanup_lhm_tables.rb
- db/migrate/20171006135205_cleanup_old_table.rb
- db/migrate/20171023161055_remove_soft_delete_correctly.rb
- db/schema.rb
For: https://trello.com/c/WzntS0j7/251-signon-fix-schema
Whenever a new migration gets created and run, 2 extra tables get added in the schema: 
1. A table starting with `lhm_<date>`. A migration was run using the LHM gem which is meant to be used for large databases with millions of rows. However, after using it, `lhm.cleanup` needs to be run in order to drop any temporary tables that it might have created in order to ensure zero downtime.
2. An `_old_event_logs` table which was not dropped properly
In addition to that, we also get a "deleted_at" field in the `oauth_applications` table, as well as an index on that column. This is a residue from when it was attempted to implement soft delete on doorkeeper tables using the `acts_as_paranoid` gem. This work was reverted, but the column was …
> Adds migrations to clean up schema

- app/controllers/confirmations_controller.rb
- config/environments/development.rb
- test/helpers/confirmation_token_helper.rb
- test/integration/email_change_test.rb
Story: https://trello.com/c/kZoLDLrT/286-changing-your-email-address-in-signon-shows-a-confusing-error-message
This fixes a compatibility issue we encountered with Devise where we were continuing to use encrypted tokens for confirmations, where they have dropped this behaviour.
This also adds in SMTP config which will allow hooking up to Mailhog a la [Whitehall](https://github.com/alphagov/whitehall/blob/master/config/environments/development.rb#L45-L49)
> Re-enable changing email while being unauthenticated

- db/migrate/20171026164712_model_dh_org_structure.rb
- db/migrate/20171027112449_model_dwp_org_structure.rb
- db/migrate/20171027112810_model_cabinet_office_org_shared_children_structure.rb
- db/migrate/20171027141009_model_home_office_org_structure.rb
- db/schema.rb
For:
* https://trello.com/c/pQum6KSu/272-model-dh-correctly-within-signon
* https://trello.com/c/z976OdQw/274-model-dwp-correctly-within-signon
* https://trello.com/c/Rmt2hrLQ/281-model-home-office-correctly-within-signon
Similar to #578 we're making sure these organisations are modelled correctly (based on the hierarchy in whitehall).  For some cases where whitehall models dual parentage, we've decided which parent is the "primary" parent and used that one here in signon because signon only supports a single parent structure (which is why we've got a Cabinet Office fix in here too that we didn't have in #572).
> Model Department of Health, Department for Work and Pensions, and Home Office correctly

- db/migrate/20171103111953_model_mod_org_structure.rb
- db/migrate/20171103145613_model_ago_org_structure.rb
- db/migrate/20171103151119_model_dfe_org_structure.rb
- db/schema.rb
For: 
- https://trello.com/c/YUHzHhRg/278-model-mod-correctly-within-signon
- https://trello.com/c/Bq4Tyb7p/267-model-ago-correctly-within-signon
- https://trello.com/c/kKelVpbt/270-model-dfe-correctly-within-signon
Similar to https://github.com/alphagov/signon/pull/578 and https://github.com/alphagov/signon/pull/580, we're making sure that these organisations have their organisational structure modelled correctly (based on the hierarchy in whitehall). 
For some cases where an organisation has two parents in whitehall, we've decided which parent is the "primary" parent and assigned that one to the org in signon because signon only supports a single parent structure.
> Model mod org correctly

- db/migrate/20171108144303_model_dit_org_structure.rb
- db/migrate/20171108144431_model_fco_org_structure.rb
- db/migrate/20171108144458_model_fsa_org_structure.rb
- db/migrate/20171108144537_model_hmt_org_structure.rb
- db/migrate/20171108144557_model_moj_org_structure.rb
- db/migrate/20171108145415_model_nio_org_structure.rb
- db/migrate/20171108150320_model_ukti_org_structure.rb
- db/migrate/20171108150355_model_welsh_gov_org_structure.rb
- db/schema.rb
For:
https://trello.com/c/y1E9av7z/273-model-dit-correctly-within-signon
https://trello.com/c/lGjMWdHM/275-model-fco-correctly-within-signon
https://trello.com/c/8MA3tUOe/276-model-fsa-correctly-within-signon
https://trello.com/c/bCAm6Vkh/277-model-hmt-correctly-within-signon
https://trello.com/c/FmZ6gAFV/279-model-moj-correctly-within-signon
https://trello.com/c/G7C9Y0hl/280-model-nio-and-scotland-office-correctly-within-signon
https://trello.com/c/JWVgB511/284-model-ukti-correctly-within-signon
https://trello.com/c/0UT6Ewmd/282-model-welsh-gov-correctly-within-signon
Similar to https://github.com/alphagov/signon/pull/583, we're making sure that these organisations have their organisational structure modelled correctly (based on the hierarchy in whitehall).
For some cases where an …
> Model multiple orgs correctly

- db/migrate/20170905111153_create_user_agents.rb
MySQL only supports key lengths of 767 bytes (which means about 255
characters as a character can take up to 3 bytes to store).  In MySQL
5.5 it would silently truncate the key for you, however in MySQL 5.6
it won't (see: https://bugs.mysql.com/bug.php?id=68453).  We plan to use
MySQL 5.6 on our new AWS infrastructure and this migration won't load
because of this bug.  We can work around it by explicitly telling MySQL
to only use the first 255 chars of the field rather than assuming it
would do this for us.
> Be explicit about index key length on user_agents

- app/controllers/invitations_controller.rb
- test/integration/inviting_users_test.rb
For: https://trello.com/c/6H9d5nNC/313-bug-signon-issue
We didn't have any tests around setting permissions (other than default ones) when inviting single users via the UI and so we didn't spot during the rails 5 upgrade that we'd broken this when we had to upgrade the code for permitting params.  It's not really the fault of the upgrade, we just have fairly spotty test coverage around all the possible functionality.
This PR fixes it and adds tests to that branch so we don't fall into the same trap again.
> Fix setting permissions while inviting users

- Jenkinsfile
- db/schema.rb
Modern rails has changed the format of schema.rb so it's useful to
regenerate it as a separate commit/PR so that the next PR with a migration
doesn't incur a large diff-cost simply for adding a column.
This regenerated schema has revealed that we some of our tables still use
latin1 instead of utf8, but we'll fix that separately.
> Regenerate schema.rb using modern rails

- app/controllers/batch_invitations_controller.rb
- app/models/batch_invitation_user.rb
- app/policies/batch_invitation_policy.rb
- app/views/batch_invitations/new.html.erb
- app/views/organisations/index.html.erb
- db/migrate/20180111145345_add_organisation_slug_to_batch_invitation_user.rb
- db/schema.rb
- spec/policies/batch_invitation_policy_spec.rb
- test/controllers/batch_invitations_controller_test.rb
- test/controllers/fixtures/users_with_orgs.csv
- test/fixtures/users_with_orgs.csv
- test/helpers/email_helpers.rb
- test/integration/batch_inviting_users_test.rb
- test/models/batch_invitation_user_test.rb
For: https://trello.com/c/62ShH5HQ/298-spike-batch-creation-of-new-signon-accounts
This PR allows super admins to upload a CSV of users for batch inviting that contains organisation slugs for each user, letting them invite a load of users who belong to different organisations all in one go.
> Allow super admins to batch create users for multiple orgs

- Dockerfile
This matches the version specified in `.ruby-version`.
> Upgrade Ruby in the Dockerfile

- app/helpers/batch_invitations_helper.rb
- app/views/batch_invitations/show.html.erb
- test/units/helpers/batch_invitations_helper_test.rb
For: https://trello.com/c/62ShH5HQ/18-batch-creation-of-new-signon-accounts
We always show the org info so we don't have to worry about checking the
policy and we have a simpler upgrade path if we decide to let admins
specify org details in the CSV as well as superadmins.
> Add organisation info to the show page for batch invites

- Jenkinsfile
Switch to deploying release_... instead of release, as this means it's
possible to more easily work out what was released. The Release app
also depends on the tag being used, rather than the branch for
displaying releases against commits.
> Deploy with the release_... tag, not release branch

- db/migrate/20180131120100_set_signin_as_default_permission_for_asset_manager_and_grant_to_all_users.rb
- db/schema.rb
This database migration is heavily based on [this one][1] which did the same thing for the Support and Content Preview apps.
The migration does two things:
1. Makes `signin` a default permission for the Asset Manager app. This means that new users will automatically be granted this permission.
2. Queues up jobs to grant the permission to all existing users.
We need this because we're using SSO in Asset Manager to protect draft assets. In the same way that all users are given `signin` permission for the Content Preview app in order to be able to view draft content, all users will need `signin` permission in order to be able to view draft assets.
Ideally we'd create a new Assets Preview app in Signon for this permission to mirror the Content Preview app. However, until we split Asset …
> Ensure all users have signin permission for Asset Manager

- app/controllers/users_controller.rb
If no letter is supplied, the new version of alphabetical_paginate will
list users that start with punctuation rather than 'A' if there are any
users whose name starts with punctuation instead of a letter.  It turns
out that we have a handful of users whose name starts with a space
character and so we need to force 'A' as the default letter if it's not
specified as otherwise it looks like we've paginated a weird list.
We also pass a duplicated version of `ALPHABETICAL_PAGINATE_CONFIG` into
the `alpha_paginate` call because the new version will mutate the supplied
hash, and we probably don't want that.
> Make sure we default to 'A' when listing users

- app/controllers/batch_invitations_controller.rb
- test/controllers/suspensions_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/batch_inviting_users_test.rb
- test/integration/event_log_creation_test.rb
- test/integration/passphrase_reset_test.rb
At the moment we call `save` which returns true or false depending on whether the save actually worked. In the case when it fails, we ignore that and then continue to use it as a foreign key of the `BatchInvitationUser` model, which then fails because the `BatchInvitation` isn't saved, and when that tries to save it fails again.
This doesn't solve the problem that we're seeing with CSV imports not working, but it should push the problem further up so we can identify what's going wrong and fix it.
I've also fixed a deprecation warning relating to use of `assert_equal nil`.
[Trello Card](https://trello.com/c/bUCRuBSv/140-batch-upload-of-users-broken-on-sign-on-2)
> Ensure BatchInvitation gets saved

- app/controllers/batch_invitations_controller.rb
- app/models/batch_invitation.rb
- test/models/batch_invitation_test.rb
We should check that the batch invitation doesn't already have said permission before adding it to prevent a Rails validation error when saving the batch invitation. This copies the same `grant_permission` and `grant_default_permissions` methods that already exist for the `User` model.
This solves a problem where the user interface for creating batch users doesn't show the default permissions which are implicitly granted to new users. Therefore it was possible to create a batch user configuration with the same supported permission declared twice which would fail Rails validation with the unhelpful error of "The change you wanted was rejected".
[Trello Card](https://trello.com/c/bUCRuBSv/140-batch-upload-of-users-broken-on-sign-on-2)
> Allow granting same permission multiples times for batch invitations

- app/policies/batch_invitation_policy.rb
- spec/policies/batch_invitation_policy_spec.rb
- test/controllers/batch_invitations_controller_test.rb
- test/integration/batch_inviting_users_test.rb
Content designers often need to upload multiple users from multiple organisations and currently only super admins can do that.
Typically super admin role is reserved for developers, and other content designers can be admins. Users in departments other than GDS are usually not admins or super admins.
I can't figure out why it was decided that only super admins would get this permission in https://github.com/alphagov/signon/pull/649.
[Trello Card](https://trello.com/c/TTgmuzzt/329-batch-upload-of-users-incorrectly-assigning-organisations)
> Allow admins to upload users with organisations

- Jenkinsfile
- app/controllers/application_controller.rb
- app/controllers/batch_invitations_controller.rb
- config/brakeman.ignore
- test/integration/event_log_creation_test.rb
- test/integration/sign_in_test.rb
This allows us to find security vulnerabilities. I've also had to fix some false positives and ignore some others, details of which are available in the commits.
[Trello Card](https://trello.com/c/JyrOAef3/363-fix-sql-injection-vulnerabilities-in-govuk-applications)
> Enable Brakeman

- app/assets/javascripts/new_admin_layout.js
- app/assets/stylesheets/new_admin_layout.scss
- app/controllers/sessions_controller.rb
- app/views/devise/sessions/new.html.erb
- app/views/layouts/admin_layout.html.erb
- config/application.rb
This uses the new design for the sign in page.
- Most of the things in the layout come from content publisher
- We've had to include jQuery (from jquery-rails, a dependency of govuk_admin_template) to get the current functionality to work.
- The header & footer will be updated to reflect new designs, I've not copied over these from content publisher
- This also removes a bunch of code that will never be run, but is part of Devise - specifically `if devise_mapping.rememberable?` and the other things in the links.
> Redesign the signin page

- test/factories/batch_invitation_user.rb
- test/factories/oauth_access_tokens.rb
- test/factories/oauth_applications.rb
- test/factories/organisation.rb
- test/factories/supported_permission.rb
- test/factories/users.rb
FactoryBot has deprecated the usage of "static" factory values:
```
name "user"
```
should become:
```
name { "user" }
```
> Fix deprecated usage of factories

- app/controllers/passwords_controller.rb
- app/views/devise/passwords/new.html.erb
This redesigns the "request a password reset" page using the new patterns.
I've removed `devise_error_messages!` because there are no error messages that can be displayed.
> Redo request password reset page

- Jenkinsfile
This is needed to maintain current behaviour since https://github.com/alphagov/govuk-jenkinslib/pull/35.
> Only lint diffs for now

- app/views/layouts/admin_layout.html.erb
- config/locales/devise.en.yml
- test/integration/authorise_application_test.rb
- test/integration/sign_in_test.rb
Currently, a user who visits `signon.publishing.service.gov.uk` will be confronted with a red flash alert message telling them "You need to sign in before continuing".
This commit removes the message, because the fact that they've arrived at a login page should be enough of a hint. The red message makes it look like something went wrong, but this scenario happens 99.9% of the time, so there's no need to alarm users.
> Don't show an error when signing in

- app/assets/stylesheets/new_admin_layout.scss
- app/controllers/root_controller.rb
- app/helpers/component_helper.rb
- app/views/layouts/admin_layout.html.erb
- app/views/root/index.html.erb
- test/controllers/root_controller_test.rb
- test/helpers/analytics_helpers.rb
- test/integration/dashboard_test.rb
- test/integration/manage_api_users_test.rb
- test/integration/sign_in_test.rb
- test/integration/sign_out_test.rb
- test/integration/superadmin_application_edit_test.rb
- test/integration/superadmin_application_users_test.rb
- test/integration/two_step_verification_test.rb
This is a implementation of the dashboard redesign by Sonia. The functionality is mostly the same as before.
I've removed the roles of the user, because I think this doesn't tell the user anything at the moment. Users that care about the roles of a user are probably all admins, and will have access to their own profile, which also lists the roles.
Also implements the navigation items in the header, as this is the first logged-in page that we've redesigned. We had to change "Applications" to "Apps" because we're running out of space in the header.
> Implement new design for dashboard

- app/controllers/doorkeeper_applications_controller.rb
- app/controllers/root_controller.rb
- app/views/doorkeeper_applications/edit.html.erb
- db/migrate/20181002104116_add_show_on_dashboard_to_applications.rb
- db/schema.rb
- test/integration/dashboard_test.rb
Some applications aren't interesting to users, and will not likely be accessed from the dashboard. This commit adds an option to the application page that will hide it from the dashboard.
> Allow applications to be hidden from the dashboard

- app/controllers/organisations_controller.rb
- app/views/organisations/index.html.erb
- test/controllers/organisations_controller_test.rb
I'm not sure what this page is for, but we're keeping it in order not to make too many changes to the app now. This converts the table to use a component.
> Use table component for organisations page

- app/controllers/doorkeeper_applications_controller.rb
- app/helpers/component_helper.rb
- app/views/doorkeeper_applications/_application_list.html.erb
- app/views/doorkeeper_applications/index.html.erb
This improves the layout for the applications index page. It's only visible to super admins.
> Re-layout applications index page

- app/controllers/confirmations_controller.rb
- app/views/devise/confirmations/show.html.erb
- test/controllers/confirmations_controller_test.rb
- test/helpers/user_account_operations.rb
This commit updates the page that users see when they are not signed in and click on a link to confirm a change of email address.
> Update change of email address confirmation

- app/assets/stylesheets/new_admin_layout.scss
- app/controllers/devise/two_step_verification_controller.rb
- app/views/devise/two_step_verification/_make_your_account_more_secure.html.erb
- app/views/devise/two_step_verification/prompt.html.erb
- app/views/root/index.html.erb
- test/integration/dashboard_test.rb
This updates the 2-step verification prompt page. This page is seen by user when they've been required to set up 2-step verification.
Also adds a permanent warning to the dashboard if 2-step verification hasn't been set up:
> Encourage people to set up 2-step verification

- config/routes.rb
Once enabled in puppet, this will make sure we have a more valuable healthcheck than currently.
https://github.com/alphagov/govuk-puppet/blob/master/modules/govuk/manifests/apps/signon.pp#L90
> Add /healthcheck endpoint

- app/helpers/root_helper.rb
- app/models/enhancements/application.rb
- app/models/organisation.rb
- app/models/user.rb
- app/views/root/signin_required.html.erb
- test/controllers/root_controller_test.rb
- test/integration/authorise_application_test.rb
Show who the publisher should contact if they can't access a publishing application.
https://trello.com/c/bOxIvf1L
> Make error messages more helpful

- config/routes.rb
- lib/healthcheck/api_tokens.rb
- test/lib/healthcheck/api_tokens_test.rb
https://trello.com/c/pvSF3FTe/5-rotate-gds-sso-tokens
This will help us to proactively rotate tokens by alerting us as reach
their expiry. We can't currently automate cycling of tokens, so the
check includes details of each API User and Application pair that need
attention, which is enough to find them in the UI.
> Add extra healthcheck for expiring API User tokens

- lib/healthcheck/api_tokens.rb
- test/lib/healthcheck/api_tokens_test.rb
Turns out nagios needs the message to always be a string.
> Fix healthcheck message being null when OK

- Gemfile
- Gemfile.lock
- app/mailers/user_mailer.rb
- app/models/user.rb
- app/views/user_mailer/notify_reset_password_disallowed_due_to_unaccepted_invitation.html.erb
- app/views/user_mailer/notify_reset_password_disallowed_due_to_unaccepted_invitation.text.erb
- test/integration/password_reset_test.rb
https://trello.com/c/HXSZikzB/38-improve-signon
Previously a user could request a password reset against an invitation that had not been accepted, even if it has expired. This ensures we only send password reset links to users with active accounts (no invitation, or invitation accepted).
> Stop password reset for unaccepted invitations

- app/presenters/usage_presenter.rb
- test/presenters/usage_presenter_test.rb
When we create the usage report csv, we should ensure the path exists
before creating the csv. The current behaviour will error if the
path does not exist and as such, the report will not be created.
Although the actual fix is only a one-line, refactor the code
to inject File and FileUtils to the constructor of UsagePresenter
so we can more easily test interactions with the file system.
I did explore using FakeFS as well as Minitest::Filesystem, but
decided to avoid introducing extra dependencies.
> Ensure path exists before creating usage report

- app/views/users/edit.html.erb
- test/integration/inviting_users_test.rb
This will allow us to remove the button from the index page in https://github.com/alphagov/signon/pull/961, which makes the UI cleaner. Also adds a missing test.
https://trello.com/c/HXSZikzB
> Add button to reinvite a user to the user page

- Gemfile
- Gemfile.lock
That doesn't show a deprecation warning. This change hasn't been
released yet but has been pushed upstream here [1].
1: https://github.com/lingz/alphabetical_paginate/pull/55
The patch changes alphabetical_paginate to work with Rails 6, where
non-attribute arguments will be disallowed.
Below is an example of a deprecation warning that shows up without
this:
```
DEPRECATION WARNING: Dangerous query method (method whose arguments
are used as raw SQL) called with non-attribute argument(s): "substr(
users.name, 1 , 1)". Non-attribute arguments will be disallowed in
Rails 6.0. This method should not be called with user-provided values,
such as request parameters or model attributes. Known-safe values can
be passed by wrapping them in Arel.sql().
```
> Use a fixed version of alphabetical_paginate

- app/controllers/devise/two_step_verification_session_controller.rb
At present, the 2SV cookie (which determines whether or not the user needs to provide a 2FA code) is not marked as secure or httpOnly. I think we intended to do this in https://github.com/alphagov/signon/pull/507, but I think this was missed.
I've not found a way to actually test this in code. I've tried the `cookies` hash [as described in the Rails docs](https://guides.rubyonrails.org/testing.html#the-three-hashes-of-the-apocalypse), and I've tried to access this cookie via `Capybara.current_session.driver.response.headers["Set-Cookie"]`. Any ideas welcome.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies
https://trello.com/c/cDd3UUeg
> Improve security for 2SV cookies

- lib/tasks/users.rake
In the users:grant_application_access_for_org Rake task. This means
that suspended users will be given access as well. Accounts are often
suspended, and then reactivated, so this better ensures that all users
in the organisation will be given access.
> Change to granting access to all users in an organisation

- app/controllers/suspensions_controller.rb
- app/views/suspensions/edit.html.erb
- lib/devise/models/suspendable.rb
- test/integration/event_log_creation_test.rb
- test/integration/manage_api_users_test.rb
- test/models/user_test.rb
If a suspended account is unsuspended, we want to force the user to reset their password (confirming that they have access to the registered email address), so set it to a random string.
This is using `SecureRandom.hex`, which has a limited character set in its output, but I think our current brute-force mitigation makes that fine.  I'm open to other suggestions though.
I've also changed the suspensions form to make it clear that the user needs to reset their password after being unsuspended.
> Randomise a user's password when unsuspending their account

- app/presenters/event_log_presenter.rb
- lib/tasks/export_event_log.rake
This commit adds a new rake task that can be used to export the signon event log (or portions of it) to a CSV file.
> Add rake task to export event log

- db/migrate/20190417111131_clone_trade_tariff_admin.rb
- db/migrate/20190417130540_clone_trade_tariff_backend.rb
This fixes some bugs in commit c81f453
The previous commit works in a rails console but not when deploying.
This is due to it not having a proper definition of
Doorkeeper::Application and it having the method
Doorkeeper::Application.supported_permissions. By adding the
definition and using a where command instead, this fixes the issue.
Zendesk: https://govuk.zendesk.com/agent/tickets/3634856
> Fix issues with the clone_trade_tariff_admin migration

- config/sidekiq.yml
ActiveMailer uses the `mailers` queue exclusively for sending emails, so remove the now defunct `mailer` queue after nearly 4 years.
> Remove mailer queue listening

- app/models/event_log.rb
- db/migrate/20190429105421_change_event_logs_ip_address_to_numeric.rb
- db/schema.rb
- test/integration/event_log_creation_test.rb
This commit replaces hand-written IPv4-to-integer code with the `IPAddr` Ruby built-in. This also has the side-effect of adding support for IPv6 addresses.
> Support IPv6 logging

- app/models/event_log.rb
The field names sent to Splunk should match the Common Information Model to make working with the data easier in the future. 
https://docs.splunk.com/Documentation/CIM/4.13.0/User/Overview
> Update Splunk event log field names to be CIM compliant.

- app/assets/stylesheets/application.scss
This fixes a bug where the font isn't loading. Font loading is disabled since govuk-frontend v2.9.0 to ensure font file is not required twice for projects that rely on govuk_template. The typeface comes disabled from govuk_publishing_component and needs to be enabled in repos that don't rely govuk_template.
> Add nta font

- app/models/event_log.rb
This commit wraps the Splunk event payload inside an `event` block as required by the Splunk HTTP event collector.
> Encapsulate Splunk event payload

- lib/tasks/users.rake
Allows revocation of all access to a given application for all users.
This is helpful when an application is shutting down and the owners would like to prevent all access.
https://govuk.zendesk.com/agent/tickets/3674781
> Add `rake users:revoke_application_access[application]`

- config/initializers/devise.rb
Replacing `his account` with `their account` in a comment block
> Remove gendered pronoun from comments

- app/controllers/api_users_controller.rb
- app/controllers/application_controller.rb
- app/controllers/authorisations_controller.rb
- app/controllers/confirmations_controller.rb
- app/controllers/devise/two_step_verification_controller.rb
- app/controllers/passwords_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/suspensions_controller.rb
- app/controllers/users_controller.rb
- app/models/event_log.rb
- app/services/user_update.rb
- test/controllers/api_users_controller_test.rb
- test/integration/event_log_creation_test.rb
- test/models/event_log_test.rb
- test/services/user_update_test.rb
IP addresses for Events were not being sent to Splunk. Including these will help with security monitoring.
This also changes the EventLog created at time stamp to be UTC.
> Send user IP address to Splunk event monitoring

- db/migrate/20190712160951_add_apha_as_child_of_defra.rb
- db/schema.rb
This migration adds APHA to the list of children of Defra.
See Zendesk: https://govuk.zendesk.com/agent/tickets/3738715
> Add APHA as a child of Defra

- app/controllers/sessions_controller.rb
- app/models/event_log.rb
- app/models/log_entry.rb
- app/views/users/event_logs.html.erb
- db/migrate/20190903085745_add_string_user_agent_to_event_log.rb
- db/migrate/20190903085803_add_string_user_email_to_event_log.rb
- db/migrate/20190903120837_set_default_event_log_uid.rb
- db/schema.rb
- test/integration/event_log_creation_test.rb
- test/integration/user_agent_test.rb
**Record user agent string on unsuccessful login:** done by adding a `user_agent_string` field to the `event_logs` table.  I'm not sure if this approach is better or worse than creating `UserAgent` models, I went for this because I figured it would be pretty straightforward to prune the event log if it grows too big.  If there are too many `UserAgent` values, then both `event_logs` and `user_agents` need pruning.
**Record email address when no such account exists:** done by making the `uid` field of `event_logs` optional (though it's required for all pre-existing event types), adding a `user_email_string` field, and adding a new event type.
The new event is type 38 and passes the email address in the `user` field.
---
https://govuk.zendesk.com/agent/tickets/3783119 …
> Improve splunk logging of unsuccessful login attempts

- lib/tasks/user_application_permissions.rake
Trello: https://trello.com/c/lPYBEJzc
This list is limited to content designers who have completed 2i training.
It gives users the permission, even if they don't have access to Collections Publisher.
This is so that when they are ready to start using Collections Publisher, they don't
need to remember to add this special permission.
Follows the same pattern of using PermissionUpdater, established in:
https://github.com/alphagov/signon/blob/master/lib/signin_permission_granter.rb
Integration test results: https://deploy.integration.publishing.service.gov.uk/job/run-rake-task/80979/console
This rake task will be removed once the user permissions have been updated in all environments.
> Add a rake task to grant permission "2i reviewer" in Collections Publisher

- lib/tasks/user_application_permissions.rake
Trello: https://trello.com/c/lPYBEJzc
Updates the rake task created in PR #1204 to check whether the
user has access to Collections Publisher, before giving them the
"2i reviewer" permission.
> Check if user has access to Collections Publisher

- Gemfile
- Gemfile.lock
[Chris' PR](https://github.com/lingz/alphabetical_paginate/pull/55) was merged into master (and is the only change since v2.3.3 which was the previous version we used).  
We want to use the changes in his PR to ensure that we're ready for Rails 6.
> Use source version of alphabetical_paginate

- Gemfile
- Gemfile.lock
@lingz has [released v2.3.4](https://github.com/lingz/alphabetical_paginate/pull/56) so we can get off using a commitish version from Github.  It's the same code as before, only with a patch version bump applied.
> Use rubygems version of alphabetical_paginate

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
Signon still uses `govuk_admin_template`, but this bump still brings in some new things from GOV.UK Frontend 3.
> Update to govuk frontend v3

- lib/data_hygiene/bulk_organisation_updater.rb
- lib/tasks/data_hygiene.rake
- test/lib/data_hygiene/bulk_organisation_updater_test.rb
This class takes a path to a CSV file and performs a bulk update of the email address and organisation associated with users. This is useful during machinery of government changes.
The CSV file must contain at least the following columns:
- 'Old email'
- 'New email'
- 'New organisation' (which must be a slug)
[Trello Card](https://trello.com/c/tDJ5oeIu/1702-add-rake-tasks-to-handle-machinery-of-government-changes)
> Bulk change organisation

- app/views/devise/two_step_verification_session/new.html.erb
The 2FA code input permits autocompletion.  The code is different for each login, so the autocomplete is not useful.
> Disable autocomplete for 2FA input when logging in

- app/mailers/user_mailer.rb
- app/views/user_mailer/unlock_instructions.text.erb
To use notify we rewrite mailer methods to call `view_mail` instead of    `mail`; however, the `unlock_instructions` email is defined by devise    and used `mail`. Overriding the mailer method so that it calls   `view_mail` with the correct parameters should address that.
https://trello.com/c/ZB29y9Y0/2050-signon-use-notify-instead-of-amazon-ses-%F0%9F%8D%90
> Override the mail method so devise uses notify correctly

- db/migrate/20200805142418_update_apha_parent.rb
- db/schema.rb
What
----
We received a zendesk ticket(linked below) from Defra which noted that they did not have access to the accounts under the Animal and Plant Health Agency(APHA) in signon, despite being their parent department. 
A look in the database confirmed that APHA is currently listed under the Welsh Government, this is incorrect. This change makes it so the APHA is now listed under Defra. 
How to review
-------------
We can deploy this branch to integration and see if the migration works. If it is properly formatted we can then deploy to production and close the ticket. 
Links
-----
[Zendesk ticket](https://govuk.zendesk.com/agent/tickets/4182860)
> Give APHA the parent of DEFRA

- app/mailers/user_mailer.rb
- app/models/user.rb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/reset_password_instructions.text.erb
- app/views/user_mailer/reset_password_instructions.text.erb
- test/integration/password_reset_test.rb
- test/support/password_helpers.rb
https://trello.com/c/ZB29y9Y0/2050-signon-use-notify-instead-of-amazon-ses-%F0%9F%8D%90
> Override reset_password_instructions mailer method for devise to use Notify

- app/mailers/user_mailer.rb
- app/models/user.rb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/invitation_instructions.html.erb
- app/views/user_mailer/confirmation_instructions.text.erb
- app/views/user_mailer/invitation_instructions.text.erb
- test/integration/batch_inviting_users_test.rb
- test/integration/email_change_test.rb
The default mailer methods defined by Devise will not use the correct methods to interface with Notify: we need to call `view_mail` and pass `template_id`, and overriding the `mail` method itself at a lower level doesn't work.
This involves creating one method for each type of mail sent by Devise (and `devise_invitable`) as well as templates for them — some of these can simply be moved, because we previously overrode the templates but not the methods. (However, rather than simply moving the plaintext template, I've converted the slightly-different HTML template to plaintext, as Notify will be converting it _back_ into HTML when it's sent).
This also partially reverts #1482, because that PR [overrode](https://github.com/alphagov/signon/pull/1482/files#diff-4676c008b11a5480d73d4a6de01e45b9R1 …
> Define mail methods on UserMailer to avoid using the default Devise methods

- docs/troubleshooting.md
This refers specifically to an error which was fixed by the Notify migration
> Remove obsolete troubleshooting documentation

- lib/data_hygiene/bulk_organisation_updater.rb
- lib/tasks/data_hygiene.rake
- test/lib/data_hygiene/bulk_organisation_updater_test.rb
If a user can't be found, check if one exists with the new email
address, as they could have already been moved. If they have already
been moved, print a warning, otherwise, print an error.
Keep going regardless of warnings or errors, but make sure to fail at
the end if any errors were encountered along the way.
> Handle missing users in the bulk organisation updater

- lib/tasks/govuk_editor.rake
This adds a task which when run adds the `govuk_editor` permission to all users who currently have access to the Publisher application. This is a necessary step towards adding a new permission later which will only give permission to edit Welsh content in Publisher.
Publisher will be updated to recognise the `govuk_editor` permission as granting the ability to perform every action on an edition. The upcoming `welsh_editor` permission will only grant access to editing Welsh language editions.
Once run the task can be deleted.
[Trello Card](https://trello.com/c/Hq2qgwiI/2155-give-permission-in-publisher-for-welsh-teams-in-departments-to-update-only-welsh-content)
> Add govuk_editor permission to all Publisher users

- app/controllers/application_controller.rb
- test/integration/inviting_users_test.rb
- test/test_helper.rb
When using a Notify service with an e-mail address allow list, or in trial mode, submitting an email-addresses that is not included in the team will trigger a `Notifications::Client::BadRequestError` with the message `Can't send to this recipient using a team-only API key`.
This PR will allow Signon to gracefully handle this error.
[Trello](https://trello.com/c/FEGnSfFP/2161-3-handle-not-in-team-notify-error-in-signon)
> Handle Notify BadRequestError

- Gemfile
- Gemfile.lock
- Rakefile
- spec/javascripts/support/jasmine_helper.rb
- spec/javascripts/support/jasmine_selenium_runner.yml
- test/integration/super_admin_reset_two_step_verification_test.rb
- test/test_helper.rb
Trello: https://trello.com/c/PlDX9ps8/180-run-govuk-docker-containers-as-root-to-allow-application-specific-mounts
This commit changes this repo to use the govuk_test gem which provides
a Chrome headless Selenium configuration for Capybara. It then uses
the govuk_test to configure Jasmine for selenium to use the same Chrome
headless configuration.
This has been done to reflect that GOV.UK convention is to use Chrome
Headless over PhantomJS - PhantomJS development has paused. The use of
govuk_test prepares this repo for an upcoming govuk-docker update [1].
[1]: https://github.com/alphagov/govuk-docker/pull/394
> Replace phantom js

- lib/organisations_fetcher.rb
- test/lib/organisations_fetcher_test.rb
This updates the organisation fetcher to manually fix APHA to set its parent to Defra. This introduces tech debt, but it was deemed to be the most practical option. Defra is a better parent for APHA than what it ends up being set to (The Welsh Government) as often editors in Defra will need access to content published by APHA.
It's worth noting, we've introduced a migration to make this change on three different occasions, but each time it's wiped when the fetcher runs:
- #574
- #1157
- #1481
At the moment the chosen parent will be the one that is last in the list ordered alphabetically. We wondered whether changing it to be the first in the list as stored in Whitehall was better, but although it fixes the parent for APHA, it introduces some different parents to other organisations that …
> Manually set APHA parent to Defra 

- test/integration/password_change_test.rb
A recent upgrade to Chromedriver means that `click_button` only works
if the element is visible on the screen.  Which it's not in this test.
So fix the test by scrolling to the button first.
> Fix issue with Chromedriver not clicking a button off the viewport

- docs/troubleshooting.md
Updating the documentation on manually sending a password reset email to a user:
- offers an alternative method that does not involve logging into a   production console
- accounts for Signon having moved from Carrenza to AWS
- adds instructions to use the gds-cli
- fixed formatting of the main header
> Update troubleshooting documentation

- app/controllers/healthcheck_controller.rb
- config/routes.rb
- lib/healthcheck/api_tokens.rb
- test/lib/healthcheck/api_tokens_test.rb
The API token check has value, but not as a readiness healthcheck.  So,
following a pattern from whitehall and a few other apps, I'm giving it
its own route, and it'll get its own Icinga alert.
Once govuk-puppet has been updated, the old endpoint can be removed.
See the RFC for more details.
---
[Trello card](https://trello.com/c/tl6RV1el/723-improve-govuk-healthchecks)
> Separate out API token healthcheck & add RFC 141 healthcheck endpoints

- README.md
- docs/README_FOR_APP
- startup.sh
Favours GOV.UK Docker in the README, removes startup script and tidies up a doc.
Trello:
https://trello.com/c/Psf7EzPB/204-move-away-from-startupsh
> Update README in favour of GOV.UK Docker 

- Dockerfile
- config/application.rb
Currently, assets are served by [nginx](https://github.com/alphagov/govuk-puppet/blob/9da822c3bb38e6565e7835e66ecadc43cb35f025/modules/govuk/manifests/apps/publisher.pp#L154)
in EC2 while in ECS we'll serve assets using the same [`CloudFront and S3`](alphagov/govuk-infrastructure#192)
infrastructure across all Backend Rails apps.
Being able to set `config.asset_host` will allow the Signon app to
point requests to its assets to the `CloudFront and S3` infrastructure.
While setting `config.assets.prefix`, will allow differentiation of assets
from different apps based on path in the same S3 bucket.
This change should be a no-op in the current platform because the
defaults for both of these config values is nil, and we won't set
these env vars with Puppet.
In addtiion, there is a need to …
> Modify config to allow custom assets host and location

- config/api_users.json
- config/applications.json
- lib/configure/api_users.rb
- lib/configure/applications.rb
- lib/tasks/bootstrap.rake
- test/lib/configure/api_users_test.rb
- test/lib/configure/applications_test.rb
This adds a rake task `bootstrap:all` which will enable us to configure signon with the OAuth applications and api users required to run in a GOV.UK cluster.
For now I've only added the apps required for the core GOV.UK cluster - that are currently running in ECS. We'll add others as needed.
Motivation
----
**Bootstrapping Signon is slow**. Currently when bringing up GOV.UK in a new environment, one must either copy an existing database to the new environment (making appropriate changes to application URLs, creating new tokens) or manually create all of the configuration required.
We want to automate Signon's bootstrapping process (the creation of Signon resources).
Implementation
----
We will run a new rake task `bootstrap:all[integration.publishing.service.gov.uk]` when deploying Signon …
> Add bootstrap rake task

- app/controllers/api/v1/authorisations_controller.rb
- config/routes.rb
- test/integration/api/authorisations_test.rb
This commit adds an API for the automated creation and rotation of ApiUser bearer tokens
**We don't rotate secrets generated by Signon often**. It is a manual process to generate a new bearer token, add it to our secrets store (hiera-eyaml), deploy Puppet, and then delete the old token.
However, we will soon be moving GOV.UK from EC2 to [ECS](https://aws.amazon.com/ecs/) (the replatforming team's goal).
As a side effect of the migration, we will change our secret store from the git-based hiera-eyaml (puppet/govuk-secrets) to AWS SecretsManager.
This gives us an opportunity to automate the rotation of Signon credentials, since AWS supports rotation of SecretsManager credentials natively.
Use a [SecretsManager Rotation Lambda](https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotat …
> Add API for bearer token creation and rotation

- lib/configure/api_users.rb
- lib/tasks/bootstrap.rake
- test/lib/configure/api_users_test.rb
The domain `digital.cabinet-office.gov.uk` isn't owned by us, and GDS IT run email on it so there is a chance of a conflict.
This enables us to use workspace/environment specific domains in emails, such as test.govuk.digital where a conflict is less likely.
> Use provided domain for ApiUser emails

- app/controllers/api/v1/applications_controller.rb
- config/routes.rb
- test/integration/api/applications_test.rb
This adds the endpoint `GET /api/v1/applications?name=Publishing+API` which will return the OAuth ID and Secret for a Doorkeeper App.
The endpoint is IP-restricted and requires a bearer token.
This will be used by the Concourse deploy pipeline when deploying apps. It's not sufficient to provide only a create endpoint, since we can be in a state where an application has been created but the generated secrets don't yet exist in SecretsManager. This endpoint enables the deploy pipeline to recover from this state.
Trello: https://trello.com/c/elhnwnaf/454-bootstrapping-signon-oauth-app-secrets
> Add get OAuth application API endpoint

- app/controllers/api/v1/applications_controller.rb
- test/integration/api/applications_test.rb
- test/integration/api/authorisations_test.rb
When creating an OAuth app one can specify the permissions that the app has. However, some apps don't have any permissions - this change adds support for those apps.
> Allow OAuth apps to have no special permissions

- app/controllers/api/v1/applications_controller.rb
- test/integration/api/applications_test.rb
We'll return a 409 Conflict status code and a more appropriate error message when we cannot create an application or its associated resources due to a RecordNotUnique error. This API's only client is the Concourse deploy pipeline, so it's an easy change.
> Return 409 status on failed recreate OAuth App call

- app/controllers/api/v1/authorisations_controller.rb
- app/models/api_user.rb
This changes the bearer token expiry time from 2 years to 60 days for tokens that are created via the API.
The expectation is that tokens created via the API will be automatically rotated every 30 days. This is currently the case for bearer tokens created for the platform in ECS.
If a rotation fails, it retries daily for a few days - we should be able to fix the issue within the 30 days after a rotation fails.
This does _not_ change anything in the EC2 platform - we'll still have long-lived tokens for apps there, since we must rotate tokens in that platform manually.
> Expire bearer tokens in 60 days

- lib/healthcheck/api_tokens.rb
- test/lib/healthcheck/api_tokens_test.rb
- test/test_helper.rb
This modifies the expiring tokens alert to ignore the expiration
of tokens that are managed by the Lambda rotation process. We're
taking advantage of the difference in email domain to filter the
alert (alphagov is typically used in production, while the Lambda
uses the environment's public domain).
It is OK for these tokens to expire, since the Lambda will create
new tokens, and leave the old tokens to expire without deleting them.
In future we'll create a new alert for monitoring Lambda rotation
failures.
https://trello.com/c/QbkAqyQW/570-signon-resolve-ux-alerting-issue
> Ignore expiring tokens alert for tokens created by Lambda

- app/controllers/devise/two_step_verification_controller.rb
- app/helpers/two_step_verification_helper.rb
- test/controllers/two_step_verification_controller_test.rb
- test/integration/sign_in_test.rb
- test/test_helper.rb
Note: This fix has already been deployed via the private repo deployment method.
A user could access the paths handled by `Devise::TwoStepVerificationController` without entering their current MFA token if it existed. This enabled a user to bypass the MFA flow. Commit 0ecdf332938239f6243ac86e02c820b8c34d4c49 seems to have introduced this.
Steps to reproduce provided by in-house pentester:
1. Enter username and password: https://signon.staging.publishing.service.gov.uk/
2. You're presented with the MFA form
3. Go directly to https://signon.staging.publishing.service.gov.uk/users/two_step_verification in your browser
4. You can now replace MFA for the account without needing theirs
Fix:
By removing the `skip_before_action: :handle_two_step_verification` we require a user to have entered …
> Bugfix: new MFA device can be created without current MFA token

- app/controllers/confirmations_controller.rb
We're currently getting some deprecation messages as `errors[:key] << value` has been deprecated.
This PR uses the errors#add method instead.
> Use the errors #add method to fix deprecation messages

- Jenkinsfile
This changes the Jenkins CI configuration to use MySQL 8.
MySQL is [available at port `33068 `](https://docs.publishing.service.gov.uk/manual/test-and-build-a-project-on-jenkins-ci.html#specifying-which-database-to-use) on the CI server. By explicitly setting the `TEST_DATABASE_URL`, we're telling Rails to use that MySQL server.
Previously, Rails implicitly used the default MySQL port `3306` which is a MySQL 5.5 server.
Trello ticket: https://trello.com/c/btcm7JyB/
The database config is already using the correct ENV var
> Upgrade CI to use MySQL 8

- app/controllers/api/v1/api_controller.rb
- app/controllers/api/v1/api_users_controller.rb
- app/controllers/api/v1/applications_controller.rb
- app/controllers/api/v1/authorisations_controller.rb
- app/helpers/admin_api_helper.rb
- config/environments/test.rb
- config/routes.rb
- lib/data_hygiene/bulk_organisation_updater.rb
- test/integration/api/api_users_test.rb
- test/integration/api/applications_test.rb
- test/integration/api/authorisations_test.rb
- test/lib/data_hygiene/bulk_organisation_updater_test.rb
This adds the `/api/v1/api-users` resource and changes the `/api/v1/authorisations` endpoint to be a sub-resource of api-users: `/api/v1/api-users/:id/authorisations`. This API is currently not in use so we are safe to break the API without modifying the version.
This addition enables the only client ([Signon bootstrap rake task](https://github.com/alphagov/govuk-infrastructure/pull/499)) to create all Signon resources necessary during cluster turnup. Previously ApiUsers were created using a Signon rake task.
Trello: https://trello.com/c/fUXJ6X1U/725-create-signon-resources-when-signon-is-deployed
> Add ApiUsers API endpoint

- db/migrate/20220106144058_remove_old_diagnostic_table.rb
- db/schema.rb
Trello: https://trello.com/c/7Tr2EOzG/67-plan-production-upgrade-for-signon-mysql-database
This table was created in 2019 [1] as part of a migration to the event
logs table (lhm is a reference to Large Hadron Migrator [2]). I don't think
it was actually intended to be ever part of the DB schema and just an
artefact of dev usage.
I've used a `if_exists: true` as this table doesn't seem to exist in all
environments.
As part of this work I've manually removed some tables from the production
database that weren't listed in the DB schema: __event_logs_old,
lhma_2019_04_30_10_36_45_946_event_logs and lhma_2019_06_18_13_31_49_199_event_logs
which were collectively using about 8GB of storage.
[1]: https://github.com/alphagov/signon/pull/1771/commits/cc9bac9b4817913ef9bae96234905ec1bce49fa6
[2]: …
> Remove lhma_2019_04_29_13_15_20_064_event_logs table

- db/migrate/20200805142418_update_apha_parent.rb
This db migration will fail if the Organisations do not exist in the Signon database.
> Remove non-robust DB migration

- app/views/root/signin_required.html.erb
Links on the "Sign in required" page needed `govuk-link` class added to be styled correctly.
To be visually consistent with the rest of the application.
Before:
After:
> Fix link appearance

- app/controllers/api/v1/applications_controller.rb
- app/controllers/api/v1/authorisations_controller.rb
- config/routes.rb
- test/integration/api/applications_test.rb
- test/integration/api/authorisations_test.rb
This is required for the signon-bootstrap client to update permissions on apps and api-users.
Co-Authored-By @theseanything 
https://trello.com/c/7ZSzslmt/849-signon-bootstrap-improvements
> Update Signon API to enable updating permissions

- app/assets/javascripts/application.js
- package.json
- yarn.lock
Adds jQuery as a local dependency, instead of relying on the jQuery that comes from the components gem.
**This PR should be deployed immediately prior to the removal of jQuery from GOV.UK** in order to minimise the time when this application will effectively contain two copies of jQuery. This shouldn't cause any errors, but it will lead to an increased asset size.
Note that I've only been able to test the first sign in screen in this application to check it works - not sure how to progress further locally.
jQuery is going to be removed from the components gem soon.
None.
Trello card: https://trello.com/c/mAfQNVRG/745-investigate-which-apps-we-could-remove-jquery-from?filter=member:andysellick2
> Add local jQuery

- app/assets/javascripts/application.js
- app/assets/javascripts/password-strength-indicator.js
- app/assets/stylesheets/application.scss
- app/views/devise/passwords/_change_password_panel.html.erb
This PR will remove the need to delicately swap jQuery when govuk_publishing_components is released without it as per: https://github.com/alphagov/signon/pull/1813
Principally the work in this PR is to rewrite the password-strength-indicator script. Which was quite an old bit of jQuery we had with some interesting approaches to showing errors. This code is tested through a feature test: https://github.com/alphagov/signon/blob/3301f7028850afd389b9c42e4bef1636b8d326d0/test/integration/password_change_test.rb#L69-L104 which hasn't needed any changes. I looked into writing JS unit tests but that was complex because of the two different layouts JS files.
Here's a quick gif of how it looks for evidence:
> Remove need for jQuery on design system layout

- app/assets/javascripts/application.js
- config/initializers/assets.rb
- package.json
- yarn.lock
We no longer need jQuery as a dependency for the design system aspects
of signon. This need was removed in: https://github.com/alphagov/signon/pull/1818
> Remove jQuery from design-system layout JS

- app/views/user_mailer/email_changed_notification.text.erb
The "Confirm your email change" email template was using the wrong variable. When referring to the user's "new email address", it was displaying the user's old email address.
Thanks to @ChrisBAshton for tipping us off about this bug.
> Fix use of incorrect variable in email template

- app/views/layouts/admin_layout.html.erb
- test/integration/dashboard_test.rb
- test/integration/sign_in_test.rb
This link is rendered to users who are not logged in. However the support system is behind Signon, so requires a user to be logged in to make a request. This leads to them being sent back to the same login page.
Removing the link to remove the continuous loop.
When signed out:
When signed in:
[Trello card](https://trello.com/c/A55SZgO4/346-remove-support-link-from-signon-homepage)
> Remove link to make a support request when logged out

- db/migrate/20220419100040_change_event_logs_user_agent_string_to_text.rb
This column currently has a limit of 255 characters. Changing to text to remove this limit as we have found some user agents can exceed this.
The update to `db/schema.rb` was accidentally committed already in https://github.com/alphagov/signon/pull/1842.
> Change `user_agent_string` column type to text

- Dockerfile
- Gemfile.lock
This covers the general case for Ruby gems wanting to write to what should be a read-only filesystem. We've configured most of the cache locations and whatnot already, but it seems there's no standard setting for Ruby/Rails to tell it where to write temporary files.
We create the symlink in the build stage as well as the final stage, because things like `rails assets:precompile` write stuff to `app/tmp` (which thankfully we don't need) and that would make it a pain to create the symlink later.
While we're there, update the version of Bundler to the one in the base image so that Bundler doesn't have to reinstall itself every time we build the image.
Tested: locally with `docker build -t signon .` / `docker run -it --rm signon bash`. Puma starts up ok, rails console works.
> Symlink /app/tmp to /tmp in the Docker image & sync Bundler version.

- Gemfile
- Gemfile.lock
- app/models/event_log.rb
This functionality hasn't been used since the events column was removed
way back in 2015 [1]. This gem is seriously old and has likely been
superseded by ignore_columns added to Rails 5.
[1]: https://github.com/alphagov/signon/commit/2528879bd4314027c3216773007c4f166f1c0a4b
> Remove deprecated_columns gem and code

- Gemfile.lock
Reverts alphagov/signon#1890
Reverting due to backwards compatibility bug in 29.15.0. See: https://github.com/alphagov/govuk_publishing_components/issues/2861
> Revert "Bump govuk_publishing_components from 29.14.0 to 29.15.0"

- app/models/doorkeeper/application.rb
- config/initializers/doorkeeper.rb
- test/models/doorkeeper_application_test.rb
This adds the ability to rewrite parts of the redirect and home URIs for OAuth Applications. This allows us to run Signon in our new infrastructure alongside the existing instance of Signon and redirect users to the correct domains for applications running in the new infrastructure. This will remove the need to create separate OAuth Applications for instances of applications in the new infrastructure.
You can use the following env vars to configure the URI string substitution:
SIGNON_APPS_URI_SUB_PATTERN: the pattern within URI to match and rewrite (e.g. "integration.publishing.service.gov.uk")
SIGNON_APPS_URI_SUB_REPLACEMENT: the string to replace the matching pattern (e.g. "integration.eks.govuk.digital")
> Rewrite redirect and home URIs for OAuth Applications

- lib/healthcheck/api_tokens.rb
- test/lib/healthcheck/api_tokens_test.rb
[Trello card](https://trello.com/c/j5cMUAJa/2954-split-expiring-signon-token-alert-into-individual-ones-3)
2nd line doesn't need to rotate expired EKS tokens - new tokens should automatically be issued for Replatforming's stuff.
Because this alert covers all tokens handled by signon, we can't just acknowledge/ignore the alert, as that would suppress genuine issues.
Instead we can take advantage of the fact that tokens for EKS apps have user names ending with `[EKS]`, and simply filter out those tokens from the alert.
> Ignore expiring EKS tokens in healthcheck

- app/views/devise/two_step_verification/_make_your_account_more_secure.html.erb
- app/views/devise/two_step_verification/show.html.erb
- app/views/devise/two_step_verification_session/new.html.erb
- test/integration/authorise_application_test.rb
- test/integration/sign_in_test.rb
- test/integration/two_step_verification_test.rb
These were requested ahead of a broader roll-out of 2SV for signon.
[Trello](https://trello.com/c/70fcYJqm/229-2-update-publisher-facing-guidance-and-current-in-app-sign-up-text)
> Copy changes for 2 step verification guidance

- lib/kubernetes/client.rb
- test/lib/kubernetes/client_test.rb
This broke with the Ruby 2 to 3 upgrade and we didn't notice because even though the broken constructor was covered by a test, the test still passes because the assertion is too permissive.
(This PR only fixes the implementation, not the test — I ran out of time trying to figure out a way to do that without rewriting the whole approach. The test still passes either way 😞)
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
https://testing.googleblog.com/2013/05/testing-on-toilet-dont-overuse-mocks.html
> Fix ArgumentError in Kubernetes::Client.new

- lib/volatile_lock.rb
- test/integration/volatile_lock_test.rb
Redis.current will be deprecated in Redis 5.0.
As Redis.current ultimately calls Redis.new we can migrate this method now to pave the way for future upgrades.
From Redis changelog from [5.0][1]:
‘Removed Redis.current. You shouldn't assume there is a single global Redis connection, use a connection pool instead, and libaries using Redis should accept a Redis instance (or connection pool) as a config. E.g. MyLibrary.redis = Redis.new(…).’
[Redis.current][2] just calls Redis.new so should just be able to swap methods.
[trello](https://trello.com/c/oGFWhrCO/1551-migrate-away-from-deprecated-redis-method)
> Use Redis.new rather than Redis.current

- app/models/user.rb
- config/application.rb
- config/secrets.yml
- lib/tasks/users.rake
- test/models/user_test.rb
Encrypt otp_secret_keys in signon.
This change is being made as we noticed during some other work that the otp_secret_keys for users in signon were stored as plaintext, while this is not against the principle of RFC-6238, and not a huge vulnerability, it was still worth fixing. 
I've used the `encrypts` model attribute introduced in Rails 7 for this, with separate keys for each environment.
Relevant PR's for Puppet and Secrets and below:
Puppet: https://github.com/alphagov/govuk-puppet/pull/11830
Secrets: https://github.com/alphagov/govuk-secrets/pull/1363
Trello: https://trello.com/c/cikBzyF1/246-encrypt-2fa-secret-keys-in-sign-on
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-ow …
> Encrypt opt secret keys

- lib/tasks/users.rake
This reverts commit d7dffbd3cc79556534eb657b901ab3a47a4634c9.
All keys have been migrated to encrypted data so this task is no longer needed. 
Trello: https://trello.com/c/cikBzyF1/246-encrypt-2fa-secret-keys-in-sign-on
> Revert "Add temporary rake task to encrypt otp_secret_keys"

- config/application.rb
These keys are not encrypted at the application level by activerecord and all unencrypted keys have been successfully migrated over, so this config is no longer needed.
Trello: https://trello.com/c/cikBzyF1/246-encrypt-2fa-secret-keys-in-sign-on
> Disallow unencrypted otp_secret_keys

- lib/tasks/sync_kubernetes_secrets.rake
This makes it easier to figure out what's wrong when a name doesn't match.
This PR shouldn't affect anything outside of Kubernetes.
Tested: ran in staging with a locally-built image; produces expected log output.
> Log the names of the k8s secrets in the app/token sync tasks.

- Jenkinsfile
Having this after build project meant that this had no effect and the local version of MySQL was used.
> Move Jenkinsfile env var so it has an effect

- Gemfile
- Gemfile.lock
Previously, there was an issue with the mailer gem in release 2.8.0 mikel/mail#1489.
To circumvent this we added it to the Gemfile and pinned it on the 2.7.0 release. Since this has been fixed we can remove it as a direct dependency.
> Remove mailer from the gemfile

- lib/tasks/permission_promoter.rake
- test/lib/tasks/permissions_promoter_test.rb
As part of turning on 2 step verification for all users, we would like any managing editors to have organisation admin roles (if they do not already have a higher level of admin rights), in order to ensure that the appropriate people in an organisation can manage their users.
We may remove this task in the future, but given the possibility of these permissions becoming out of sync, it may be useful to keep.
[Trello](https://trello.com/c/O8jeiIfc/432-give-organisation-admin-permission-to-the-non-gds-managing-editors-who-are-not-currently-organisation-admin)
Follow [these …
> Add task to promote all non-GDS managing editors to 'organisation admin' role

- lib/tasks/users.rake
- test/lib/tasks/users_test.rb
We will soon be switching on 2sv for all users, and so having the ability to set this flag by domain means we will be able to turn it on incrementally for sets of users.
[Trello](https://trello.com/c/yZFT5Rak/434-write-a-rake-task-to-allow-developers-to-set-the-flag-on-groups-of-users-by-organisation-and-by-email-domain)
> Add task to set 2sv for all users within an organisation or email domain

- db/seeds.rb
This gives us a test superadmin and test user for when we run the application locally during development.
Co-authored-by: @BeckaL
This work was identified as part of [Trello card](https://trello.com/c/qijNj4uh).
> Add seeds file

- app/controllers/signin_required_authorizations_controller.rb
- test/controllers/signin_required_authorizations_controller_test.rb
We currently have a test to ensure doorkeeper matches a hardcoded version. This value has to be updated each time the doorkeeper gem is upgraded.
We understand the reason being that a controller was based on (and inherits from) another controller in doorkeeper.
The expectation was developers would compare the controller in this app to the equivalent in doorkeeper before making any updates.
We know from anecdotal (and commit history) that this has not happened. It therefore feels this test is not achieving its original purpose.
We know the test coverage of this controller is good, so are removing the version check test and instead relying on the controller's tests to see if there have been any breaking changes in doorkeeper. …
> Remove test for doorkeeper version

- Gemfile
- Gemfile.lock
- app/controllers/two_step_verification_exemptions_controller.rb
- app/helpers/user_filter_helper.rb
- app/helpers/users_helper.rb
- app/models/event_log.rb
- app/models/user.rb
- app/policies/user_policy.rb
- app/services/user_update.rb
- app/views/two_step_verification_exemptions/edit.html.erb
- app/views/users/_form_fields.html.erb
- config/routes.rb
- db/migrate/20230126115902_add_reason_for_2sv_exemption_to_user.rb
- db/schema.rb
- test/controllers/two_step_verification_exemptions_controller_test.rb
- test/factories/users.rb
- test/helpers/users_helper_test.rb
- test/integration/admin_user_index_test.rb
- test/integration/change_user_role_test.rb
- test/integration/exempt_from_2sv_test.rb
- test/integration/inviting_users_test.rb
- test/integration/mandating_two_step_verification_test.rb
- test/models/user_test.rb
- test/policies/user_policy_test.rb
- test/services/user_update_test.rb
- test/test_helper.rb
This PR introduces the basics for exempting users from 2sv, adding a link on the 'edit user' page and a new page for adding and editing the exemption reason. 
The functionality is behind a feature flag, so users will not be able to exempt unless the environment has a "PERMIT_2SV_EXEMPTION". We plan to remove this feature flag once the other 2sv features are ready.
Screenshots of new functionality added:
| Scenario | Screenshot |
|----|-----|
| Link to add an exemption for a user |![Screenshot 2023-02-03 at 08 09 04](https://user-images.githubusercontent.com/6329861/216546237-036f5523-3385-475b-b20e-df3cb17915de.png)|
| Link to edit an exemption for a user|![Screenshot 2023-02-03 at 08 07 47](https://user-images.githubusercontent.com/6329861/216546002-91b1fc56-9a87-4ad5-bcce-f06bafa1a7d8.pn …
> Allow gds admins to exempt users from 2sv with reason

- app/models/api_user.rb
- app/policies/user_policy.rb
- db/seeds.rb
- test/integration/exempt_from_2sv_test.rb
- test/models/api_user_test.rb
- test/policies/user_policy_test.rb
Depends on https://github.com/alphagov/signon/pull/2083 [merged]
Signon has two types of users - human users, and 'api users'. An api user is created in the case where we want communication between two applications to be authenticated, so an api user is created for one of the applications, granting it access to another via a bearer token. Api users can be for applications internal to GDS and external.
Because we don't want to enforce 2sv on these users, this contains:
* some preventative work ensuring that api users cannot have the 'require_2sv' flag set to true. This should give us a layer of safety when setting this flag across big groups of users, when we turn 2sv on for all human users.
* Some work to prevent users from being able to give api users exemption reasons in the UI - since …
> Prevent api users from having 2sv required or exemption reasons set

- db/migrate/20230206131707_add_require2sv_to_organisations.rb
- db/schema.rb
This will be used to mandate 2SV for all users from an organisation.
[Trello card](https://trello.com/c/a3Zu69Td)
> Add `require_2sv` field to organisations

- app/controllers/devise/two_step_verification_controller.rb
- app/helpers/users_helper.rb
- app/models/api_user.rb
- app/models/user.rb
- app/views/root/index.html.erb
- app/views/users/_form_fields.html.erb
- lib/tasks/users.rake
- test/integration/dashboard_test.rb
- test/integration/two_step_verification_test.rb
- test/lib/tasks/users_test.rb
- test/models/user_test.rb
In a [previous PR](https://github.com/alphagov/signon/pull/2095), we introduced the ability to exempt a user from 2sv, based on providing an exemption reason.
This PR ensures that users who are exempted (i.e. those with exemption reasons) have an experience that is consistent with this status. This means:
* They are excluded from any rake tasks to bulk set the `require_2sv' flag on groups of users
* They do not see large call to actions to set up 2sv, although they are still able to set this up in the UI if their circumstances change
* When they set up 2sv, their exemption reason is removed, meaning that they no longer appear in the list of exempted users.
Screenshot to illustrate the difference when logging in as an exempted user:
| Before this change | After this change |
| ---- | ---- …
> Make exempted 2sv user experience consistent with their status

- app/controllers/devise/two_step_verification_controller.rb
- app/controllers/two_step_verification_exemptions_controller.rb
- app/models/event_log.rb
- app/models/user.rb
- app/presenters/user_export_presenter.rb
- app/views/two_step_verification_exemptions/edit.html.erb
- app/views/users/_form_fields.html.erb
- app/views/users/index.html.erb
- db/migrate/20230209131935_add2_sv_exemption_expiry_date_to_users.rb
- db/schema.rb
- test/controllers/two_step_verification_exemptions_controller_test.rb
- test/factories/users.rb
- test/integration/managing_two_step_verification_test.rb
- test/integration/two_step_verification_test.rb
- test/models/user_export_presenter_test.rb
- test/models/user_test.rb
- test/support/managing_two_sv_helpers.rb
This PR implements adding an expiry date to the 2sv exemptions form. Exemptions must now be created with expiry dates, reflecting the thought that some exemption reasons will be temporary and should be reviewed at some point.
This PR:
* Adds the exemption expiry date to the user interface and handles in the backend code
* Adds the expiry date to access logs when an exemption is created or updated
* Adds the expiry date to the information displayed about users on the users index page, and in the csv export from that page
* Updates some copy on the existing form as requested by Indy.
Screenshots:
| | Currently | Edit exemption form in this PR |
|----|----|----|
| Edit exemption form |<img width="1164" alt="Screenshot 2023-02-10 at 14 40 43" …
> Add expiry date to 2sv exemptions

- app/controllers/invitations_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/policies/user_policy.rb
- app/views/users/_form_fields.html.erb
- app/views/users/require_2sv.html.erb
- config/routes.rb
- db/seeds.rb
- test/controllers/invitations_controller_test.rb
- test/integration/inviting_users_test.rb
- test/models/user_test.rb
This implements the following:
- requires 2SV for all existing users (who are not exempt) from an organisation when their organisation is set to require 2SV
- requires 2SV for all new users from an organisation when their organisation is set to require 2SV (e.g. for users created by rake tasks, or in bulk)
- moves the 2SV checkbox during registration to a separate page, so it is only presented to users who are not required to have 2SV (either by membership of an organisation or because they are an admin/superadmin role)
Validations are still carried out when the first form is submitted, hence why we now need to explicitly check the submission is valid without persisted the user in the database.
The following user flows are now present during registration:
1. New user who is being assigned …
> Require 2SV for users from organisations where 2SV is mandatory

- lib/tasks/users.rake
- test/factories/users.rb
- test/lib/tasks/users_test.rb
This will allow us to mandate 2SV for all existing organisation admin and super admin users.
This task can be removed once it has been run in production.
[Trello card](https://trello.com/c/UGfyyMQ1/562-general-template)
> Add rake task to mandate 2SV for organisation admin and super admin users

- lib/tasks/users.rake
- test/lib/tasks/users_test.rb
We are currently matching the organisation in this rake task using the name.
This has caused us an issue with a name that contains an apostrophe as we cannot execute the rake task using `kubectl`.
Therefore updating to use the slug.
> Update 2SV mandating rake task to use slug

- lib/tasks/users.rake
- test/lib/tasks/users_test.rb
We currently have a rake task to enable 2SV for all existing users from an organisation, however we have to use the UI to enable it on an organisation.
This adds a rake task so it can be done without lots of clicking (e.g. when updating organisations in bulk).
[Trello card](https://trello.com/c/4Je11yym)
> Add rake task to enable 2SV on an organisation

- .github/pull_request_template.md
This app is now owned by the Access & Permissions team.
Note that I've removed the request to contact us in Slack; instead I've enabled Slack notifications for PRs on this repo in the #govuk-publishing-access-and-permissions-team channel.
> Change PR template to reflect change in app ownership

- app/controllers/api_users_controller.rb
- app/helpers/api_users_helper.rb
- app/views/api_users/index.html.erb
- app/views/organisations/index.html.erb
- test/controllers/api_users_controller_test.rb
- test/integration/manage_api_users_test.rb
Trello: https://trello.com/c/U0fhO3gx
This is part of the ongoing effort to migrate all of the application's user interface to using the GOV.UK Design System.
* We've moved name & email address into separate columns rather than distinguishing them using typography.
* The "Create API user" button is now on the left rather than over on the right. It's not obvious that having it on the right is something that the design system recommends.
* We've retained the use of the `del` element to visually distinguish suspended users since this seems semantically correct and their suspended state is also visible in a separate column anyway.
* We've retained the use of the `abbr` element for application permissions, even though we think it's being abused in order to provide a tooltip. Note that …
> Migrate API users index page to GOV.UK Design System

- Rakefile
One of these log messages is generated for every asset file when running the "default" rake task:
I, [2023-05-24T13:43:51.865470 #2412]  INFO -- : Writing
/govuk/signon/public/assets/signon/manifest-90aab26ade71e747f745b1227b433fd7d580a54f279ee2be6e1a67bb326bf03a.js
I don't think these log messages are particularly useful and in fact they obscure what might be a significant warning:
W, [2023-05-24T13:43:37.862925 #2412]  WARN -- : Removed sourceMappingURL comment for missing asset 'govuk_publishing_components/vendor/lux/lux.js.map' from /root/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/govuk_publishing_components-35.4.0/app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js
I'm not planning to address the latter in this commit, but with the INFO-level messages …
> Avoid INFO-level log messages in asset:precompile

- app/controllers/devise/two_step_verification_session_controller.rb
- test/integration/sign_in_test.rb
Trello: https://trello.com/c/9C8iNaKn
In `Devise::TwoStepVerificationSessionController#create`, if the 2SV code was invalid, the flash alert was set and the "new" template was *rendered*.  Although the flash alert was rendered at this point, it was not removed from the flash. So if the user then submitted the correct code, they were redirected to the "prior flow" (the root path by default) and the flash alert was (incorrectly) displayed again.
This commit uses `ActionDispatch::Flash::FlashHash#now` to set the flash alert - it is now removed as soon as it is rendered for the first time in the "new" template and not the second time in the subsequent "success" page.
Fixes #1417.
> Fix 2SV flash alert displayed on success after failure

- app/views/layouts/admin_layout.html.erb
- test/integration/inviting_users_test.rb
- test/integration/password_reset_test.rb
- test/support/analytics_helpers.rb
Trello: https://trello.com/c/4fDGiKTz
Since both the passwords controller and invitation controller pages were switched over to use the new design system layout in [this commit][1], the sensitive `password_reset_token` and `invitation_token` query string parameters have inadvertently been sent to Google Analytics when previously they was redacted.
I've confirmed that I can see recently generated `password_reset_token` & `invitation_token` values in Google Analytics. This is a security risk, because someone who has access to Google Analytics might be able to gain access to someone else's Signon account.
Before the change mentioned above, all pages were using the application layout as opposed to the `admin_layout` layout. The application layout provides content to the `govuk_admin_template` …
> Do not send sensitive tokens to Google Analytics

- Rakefile
This changes the invocation order of the Rake tasks associated with the default Rake task to run in the following order: lint, jasmine, test. I think this is a more logical order and it matches the CI workflow more closely i.e. lint-scss, lint-javascript, lint-ruby.
Previously, they were run in the following order: test, lint, jasmine; even though they were listed in the following order: lint test jasmine. This was because prior to the redeclaration of the default Rake task in the `Rakefile`, Rails sets the test task as a prerequisite for the default task. Thus we need to clear the prerequisites if we want to run the lint & jasmine tasks before the test task.
My main motivation for making this change is that it's quite frustrating to only see Rubocop violations *after* all the Ruby tests …
> Run lint Rake task *before* test Rake task

- test/support/analytics_helpers.rb
* Fix `AnalyticsHelper#refute_dimension_is_set` assertion which hasn't been doing anything useful since [this commit](https://github.com/alphagov/signon/commit/7fe1e64b593e01e3cc1d38049c78778262a47a3d).
* Use Capybara matcher in `AnalyticsHelper` assertions so they will use the built-in waiting mechanism in the hope this fixes the intermittent integration test failures we've seen in `test/integration/sign_in_test.rb` &
`test/integration/sign_out_test.rb`.
See commit notes for more details.
> Fix flakey sign-in and sign-out integration tests

- app/controllers/devise/two_step_verification_controller.rb
- app/views/devise/two_step_verification/show.html.erb
- app/views/layouts/admin_layout.html.erb
- test/integration/two_step_verification_prompt_test.rb
- test/integration/two_step_verification_test.rb
- test/support/user_helpers.rb
Trello: https://trello.com/c/Ht3aHQTT
This PR adopts the GDS design system for the show and update actions on the TwoStepVerificationController. A user sees this page when they add or change the two-step verification code for their account.
The main change to the page is the switch from collapsable sections to having everything visible by default. We considered using the step-by-step, accordion or tabs components/patterns but it's not obvious that these are suitable for forms. Also since there's not a lot of content in each "step", it's not obvious that there's a lot of benefit to the user of hiding some of the "steps". So we've just made the "steps" into numbered headings with non-collapsing content. We don't think this looks too bad. If there's too much content on the page, we could …
> Migrate 2SV setup page to GOVUK Design System

- db/migrate/20230613153019_add_foreign_key_constraint_to_application_id_on_oauth_access_tokens.rb
- db/schema.rb
Trello: https://trello.com/c/chkpC1am
We've been seeing [`ActionView::Template::Error` exceptions][1] in integration when editing the SSO Push user in integration. It appears to be happening because that user has a couple of access tokens associated with it that have `application_id` which point to non-existent applications.
I think we could argue whether or not we actually need (or indeed should) to be able to edit this "singleton" `ApiUser`, but either way it doesn't seem good from a database integrity point of view that an access token can end up with an `application_id` that points to a non-existent application.
In the migration we create dummy applications for those access tokens to point to. And then we add the foreign key constraint. This was the least controversial way I could …
> Add foreign key to oauth_access_tokens.application_id

- db/migrate/20230613153019_add_foreign_key_constraint_to_application_id_on_oauth_access_tokens.rb
Trello: https://trello.com/c/chkpC1am
This fixes the migration that was added in #2201.
It turns out that there are some orphaned `supported_permissions` records in integration which reference the same `application_id` as the orphaned `oauth_access_tokens` records. Unfortunately, because we were using `Doorkeeper::Application.create!` to create the missing applications, the `create_signin_supported_permission` `after_create` callback was being triggered and since an orphan "signin" supported permission already existed, a `Mysql2::Error` was triggered:
Mysql2::Error: Duplicate entry '3905-signin' for key
'supported_permissions.index_supported_permissions_on_application_id_and_name'
Originally I attempted to address this by using
`Doorkeeper::Application.insert!` vs `create!` in order to …
> Fix migration adding foreign key constraint to oauth_access_tokens

- app/jobs/permission_updater.rb
- app/jobs/push_user_updates_job.rb
- app/jobs/reauth_enforcer.rb
- test/jobs/permission_updater_test.rb
- test/jobs/push_user_updates_job_test.rb
- test/jobs/reauth_enforcer_test.rb
Trello: https://trello.com/c/chkpC1am
We've been seeing `SSOPushError` exceptions for an application even having disabled its support for push updates. We believe this is happening, because some jobs were created before support for push updates was disabled, the job then failed, and now it's retrying. And since the check against `Doorkeeper::Application#supports_push_updates?` was only happening at job creation time, the job will keep failing and triggering these exceptions.
By moving the check to job execution time, the failed jobs will succeed when they next retry without triggering an exception. This change will also protect us against something similar happening again in the future.
Note that I had to remove `with_supported_permissions: %w[user_update_permission]` from the creation of …
> Move SSO Push check from job creation to job execution time

- db/schema.rb
This should've been included in [the commit][1] where the foreign key was added.
[1]: 90ffc0ff35d5c00d93d1ed364899179fa5cb371b
> Update schema to include index on oauth_access_tokens

- app/helpers/root_helper.rb
- test/helpers/root_helper_test.rb
Trello: https://trello.com/c/RPnXXRR2
We've been seeing `ActionView::TemplateError` exceptions on this page. It seems as if it's possible for the `application` to be `nil` which seems to be reinforced by the use of `Object#try` when setting `session[:signin_missing_for_application]` in `SigninRequiredAuthorizationsController` actions.
I did try to work out under what circumstances the `application` might not be set, but it's really hard to follow all the code involving the Devise, Doorkeeper and/or Pundit gems. So for the moment, I've just added a guard condition to `RootHelper#gds_only_application_and_non_gds_user?` to make sure the user doesn't end up seeing an error page.
> Avoid ActionView::TemplateError on signin-required page

- app/controllers/devise/two_step_verification_session_controller.rb
- test/integration/two_step_verification_test.rb
Trello: https://trello.com/c/YxXfT38U
We've been seeing `NoMethodError` exceptions on `POST` requests to `/users/two_step_verification/session`. The exception was happening deep in the bowels of the ROTP gem, but the reason why it was happening was that `User#otp_secret_key` was `nil`.
I've managed to reproduce the problem with a user that's signed in but doesn't have 2SV setup, by visiting the `/users/two_step_verification/session/new path` (entered directly into the browser location) and submitting a code. Since the user doesn't have 2SV setup, `User#otp_secret_key` is `nil` and the exception is raised in `Devise::TwoStepVerificationSessionController#create`.
I haven't managed to track down a place where the application might send a user in this state to this page, so that remains a bit …
> Don't ask for 2SV code unless they have 2SV setup

- app/controllers/batch_invitations_controller.rb
- app/views/batch_invitations/show.html.erb
- app/views/layouts/admin_layout.html.erb
- test/controllers/batch_invitations_controller_test.rb
Trello: https://trello.com/c/jPK7WHy8/135-migrate-batchinvitations-to-use-design-system
This PR migrates the batch invitations show page (e.g. http://signon.dev.gov.uk/batch_invitations/1) to use the design system. 
I've made the following significant choices: 
1. Use the `notice` component to indicate when a batch is still being processed (the previous `alert-info` div)
2. Use a `success_alert` component to indicate that all records were successfully processed (the previous `alert-success` div)
3. Use an `error_alert` component to indicate if one or more records in the batch couldn't be processed (the previous `alert-danger` div). The previous alert didn't provide a mechanism for the user to fix the error so for now I've retained that behaviour by using an `error_alert` rather than a …
> Use design system for batch invitations show

- app/models/batch_invitation_user.rb
- test/models/batch_invitation_user_test.rb
Trello: https://trello.com/c/8oHupLq2/138-investigate-errors-with-uploading-batch-of-users-to-production
We've recently received notice that a user attempted to upload a batch of users and some or all of those users failed. We don't currently provide much guidance to the user on why their batches have failed, and in fact, we don't receive any information as the product team because those exceptions are currently being rescued silently.
This commit logs (via `GovukError`) some information about why the process failed, and I'm hoping we'll be able to use that information to improve the experience for the users, or at least be able to deal with their issues manually via the second-line process.
> Improve logging of failed batch invitations

- app/controllers/api_users_controller.rb
- app/views/api_users/new.html.erb
- test/controllers/api_users_controller_test.rb
Trello: https://trello.com/c/XwCQCdMu/140-migrate-apiusers-new-to-use-design-system
This commit moves the api_users new page to use the design system. The changes here should be fairly uncontroversial, but have involved rewriting most of the template.
I've specified that the `create` action should use the `admin_layout` in the ApiUsersController so that the correct layout is used when the page re-renders on validation error.
The `_form_fields` partial referenced in the old template is still used by the `edit` view, which will be migrated as a separate piece of work.
I've had to slightly change the integration test to target the error summary div provided by the design system, and to use a regex to match the text rather than an exact string (since the design system `error_summary` partial …
> Migrate api_users new page to design system

- db/migrate/20230622122857_add_missing_application_created_at_timestamps.rb
- db/schema.rb
We've got 3 records in oauth_applications where the created_at timestamp is null.
```
Doorkeeper::Application.table_name
=> "oauth_applications"
Doorkeeper::Application.where(created_at: nil).count
=> 3
Doorkeeper::Application.where(created_at: nil).map(&:name)
=> ["Panopticon", "Publisher", "Whitehall"]
```
These missing timestamps are causing the following [exception when viewing /oauth/authorized_applications][1].
```
ActionView::Template::Error /oauth/authorized_applications
undefined method `strftime' for nil:NilClass
```
The exception is being raised in [the Doorkeeper template][2].
The [oauth_applications table doesn't allow null values in the created_at field][3] so I'm unclear on how we've got these entries.
The earliest created_at in the table is 27 Apr 2012 so I've chosen to …
> Populate missing created_at timestamps in Doorkeeper::Application models

- app/models/batch_invitation_user.rb
- test/integration/batch_inviting_users_test.rb
- test/models/batch_invitation_user_test.rb
Trello: https://trello.com/c/8oHupLq2
We've been seeing a "User not persisted" exception in Sentry[1] when a user batch invites users whose organisation requires 2sv. This was because we were not providing the `require_2sv` parameter in the call to `User.invite!`. We've been validating that created users must have `require_2sv` set to `true` when their organisation requires it since c5a4fedc57 but hadn't updated the batch invitation tool to reflect that.
This commit sets the appropriate `require_2sv` value on the invited user. I've made sure that the value is true even when no organisation is provided to the batch or the individual user - I'm not entirely sure if it's possible for the batch upload code to reach that state but given that we're now enforcing 2sv for all users unless they …
> Fix batch invitation for organisations that require 2sv

- app/controllers/bulk_grant_permission_sets_controller.rb
- app/helpers/bulk_grant_permission_sets_helper.rb
- app/views/bulk_grant_permission_sets/new.html.erb
- app/views/users/index.html.erb
- test/helpers/bulk_grant_permission_sets_helper_test.rb
- test/integration/bulk_granting_permisions_test.rb
Trello: https://trello.com/c/Kf19VBou/148-migrate-bulkgrantpermissionsets-new-to-use-design-system
We've decided to replace this page with a simple form that allows an admin to grant the signin permission to all users for a specific application, since that is all the current system seems to be used for (there are three BulkGrantPermissionSet records in the production database, and they all grant "signin" permission to one or two applications).
This means we don't have to worry about finding a design-system alternative for the permissions multi-select box.
We think this can be extended to include specific permissions at a later date (perhaps as a second "step" in the flow) if we want/need to.
We still have a page that shows the results of previous runs of this bulk update (e.g. …
> Move bulk_grant_permission_sets/new page to design system

- config/initializers/devise.rb
- config/routes.rb
- db/migrate/20230629083629_update_sso_push_user_name.rb
- db/schema.rb
- docs/oauth.md
- lib/sso_push_credential.rb
This app was renamed from Sign-on-o-tron to Signon some years ago, but a bunch of the code and docs still reference the old name which is confusing.
A couple of the changes are not without risk of breaking things:
1. Changing the name of the Basic HTTP Authentication realm
2. Changing the name of the SSO Push user
However, I think the risk is worth it for reducing developer confusion! What do you think?
See the individual commit notes for more details.
> Remove references to sign-on-o-tron

- app/controllers/devise/two_step_verification_controller.rb
- app/helpers/two_step_verification_helper.rb
- app/models/user.rb
- app/views/devise/two_step_verification/show.html.erb
- app/views/devise/two_step_verification_session/new.html.erb
- lib/code_verifier.rb
- test/helpers/two_step_verification_helper_test.rb
- test/integration/authorise_application_test.rb
- test/integration/sign_in_test.rb
- test/lib/code_verifier_test.rb
Trello: https://trello.com/c/eZussIrd
We've had reports from our users that when they type in the code from their 2sv application, if they include a space (which the apps often include in their display between each group of 3 digits) we don't
accept the code and the "Sorry that code didn’t work. Please try again." error doesn't help them resolve the issue.
This PR allows the user to separate the digits of their code with either space or `-` characters, and also include leading or trailing spaces. So for a valid code `123456` we now accept, for example, ` 123456 `, `123 456`, `123-456`, `12 34 56`.
The first two commits in this PR aren't strictly required to achieve this change, but I found it a little confusing that we had two slightly different ways of asking the user for the 6 digit …
> Accept 2sv codes with spaces

- config/initializers/doorkeeper.rb
- config/routes.rb
- test/integration/doorkeeper_integration_test.rb
The Doorkeeper Gem makes several /oauth/applications routes available to allow users to CRUD Applications. We don't want to allow access to these routes but a misconfiguration in our doorkeeper.rb initializer meant that we were only accidentally preventing access.
The first commit in this PR fixes the Doorkeeper configuration to properly prevent access to /oauth/applications.
The second commit in this PR then removes the route entirely.
> Remove Doorkeeper's /oauth/applications routes

- app/controllers/bulk_grant_permission_sets_controller.rb
- app/helpers/bulk_grant_permission_sets_helper.rb
- app/views/bulk_grant_permission_sets/new.html.erb
- app/views/bulk_grant_permission_sets/show.html.erb
- test/integration/bulk_granting_permisions_test.rb
Trello: https://trello.com/c/gGY6x4mJ/173-migrate-bulkgrantpermissionsets-to-use-design-system
This PR migrates the BulkGrantPermissionSets#show action ([example, integration](https://signon.integration.publishing.service.gov.uk/bulk_grant_permission_sets/1)) to use the design system.
Note, since #2221 we now only support the bulk granting of the `signin` permission to applications. However there are older "permission sets" that granted other permissions, so I've decided that the show page should still display the additional permissions that were granted by those sets. We may want to revisit that decision later, and perhaps simplify this view further but for now, and in the interest of moving the page to the design system in a straightforward way, I've kept the current behaviour.
> Migrate bulk grant permission sets show to design system

- app/controllers/organisations_controller.rb
- app/views/organisations/edit.html.erb
- test/integration/mandate_2sv_for_organisation_test.rb
Trello: https://trello.com/c/uPouwNMf
I decided to remove the "cancel" button as we have the breadcrumb trail to return to the previous page, and the component guide suggests we should aim to have a single button per page[1].
I've downcased the button text to be consistent with other uses of buttons.
[1] https://components.publishing.service.gov.uk/component-guide/button
> Migrate OrganisationsController#edit page to design system

- app/controllers/users_controller.rb
- test/controllers/users_controller_test.rb
Trello: https://trello.com/c/1c6vLRnN
We found a bug[1] which prevented organisation and super organisation admins to retry validation errors when editing a user. This commit fixes that bug and adds a couple of tests to catch any regressions.
[1] https://govuk.sentry.io/issues/4307435188/?project=202251
> Allow (super) org admins to re-try editing users

- app/controllers/suspensions_controller.rb
- app/models/suspension.rb
- app/views/suspensions/edit.html.erb
- test/controllers/suspensions_controller_test.rb
- test/models/suspension_test.rb
Trello: https://trello.com/c/il1tKvaJ/181-migrate-suspensions-edit-to-use-design-system
I've removed the "cancel" button in favour of the breadcrumb trail, as the component guide suggests[1] that we should try to have a single button on each page.
I've also improved the error handling and made it follow the design system pattern by adding a Suspension model which uses ActiveRecord validations. Details in the second commit.
[1] https://components.publishing.service.gov.uk/component-guide/button
> Migrate user suspension edit page to design system

- app/controllers/signin_required_authorizations_controller.rb
- config/routes.rb
- test/controllers/signin_required_authorizations_controller_test.rb
Trello: https://trello.com/c/JvVlLMB4/182-remove-oauth-token-info-doorkeeper-route
Doorkeeper's [/oauth/token/info route is used as the redirect URI for native apps in the Implicit grant flow](https://github.com/doorkeeper-gem/doorkeeper/blob/v5.6.6/lib/doorkeeper/oauth/authorization/token.rb#L77-L83). Our Doorkeeper configuration prevents the Implict grant flow so we can remove this route.
The first 9 commits improve our `SigninRequiredAuthorizationsController` and associated tests and the final commit removes the /oauth/token/info route.
> Remove Doorkeeper's /oauth/token/info route

- app/controllers/users_controller.rb
- app/views/users/require_2sv.html.erb
Trello: https://trello.com/c/pEwkk3Dt
I've used the standard hint, checkbox and button components.
This page is shown as part of the user creation journey for users where their organisation doesn't mandate 2sv but we want to mandate it for the specific user. I've decided not to include a breadcrumb trail as there's not really any consideration made for navigating forward and backwards in this journey (the record is saved and the user emailed before we reach this page, for example).
> Migrate UsersController#require_2sv page to design system

- app/controllers/two_step_verification_exemptions_controller.rb
- app/models/two_step_verification_exemption.rb
- app/views/two_step_verification_exemptions/edit.html.erb
- test/controllers/two_step_verification_exemptions_controller_test.rb
- test/factories/two_step_verification_exemption.rb
- test/integration/managing_two_step_verification_test.rb
- test/models/two_step_verification_exemption_test.rb
- test/support/managing_two_sv_helpers.rb
Trello: https://trello.com/c/oqt4y7dH
I've introduced a new `TwoStepVerificationExemption` `ActiveModel` model to implement the field validation for this form; previously the validation was all done in the controller.
My main motivation for doing this was to be able to store validation errors against a particular field so that I could implement the Design System error summary correctly with links to the invalid fields and so I could implement something close to [the date field][1] validation recommended by the Design System.
However, I think it also bring some other benefits: the code is now a bit more idiomatic Rails, it's easier to test the validation, and when validation fails the values the user entered are retained (i.e. we re-render the form rather than redirecting as we did …
> Move 2SV exemptions page to use GOV.UK Design System

- config/secrets.yml
Previously the secrets were hard-coded in development. I've found myself needing to change them, but if I just change the hard-coded values, there's a danger I might push sensitive secrets into the public repo. So it seems safer to allow the secrets to be overridden using the same env vars that are used in production, but fallback to the hard-coded values if those env vars are not set.
> Allow setting secrets via environment variables in development

- test/factories/two_step_verification_exemption.rb
The test on line 9 of
`test/models/two_step_verification_exemption_test.rb` had started to fail today because the logic was wrong and it's the last day of the month today!
> Fix two_step_verification_exemption factory expiry date

- app/assets/stylesheets/_filters.scss
- app/controllers/users_controller.rb
- app/helpers/users_helper.rb
- app/views/users/_pagination.html.erb
- app/views/users/_user_filter.html.erb
- app/views/users/index.html.erb
- config/initializers/alphabetical_paginate_config.rb
- test/controllers/users_controller_test.rb
- test/integration/admin_user_index_test.rb
Trello: https://trello.com/c/QuwuPtZW
We're planning to move this page (like every other page in the Signon app) to use the GOV.UK Design System. However, we haven't yet worked out how to implement the filtering using the Design System. So in the meantime, we've decided to make some incremental improvements which will also help when we come to move the page to the Design System.
Please see the commit note for details and motivations for each change, but in summary we've:
* removed some of the less useful columns
* split the name & email into separate columns
* replaced the "Users by initial" pagination with standard pagination
* removed the pagination controls from the top of the table and reduced the number of users on each page to make the pagination controls at the bottom of the table …
> Incremental improvements to the users index page

- app/models/batch_invitation_user.rb
- app/models/user.rb
- db/migrate/20230802095323_strip_whitespace_from_users_names.rb
- db/schema.rb
- test/models/batch_invitation_user_test.rb
- test/models/user_test.rb
https://trello.com/c/WVFDaA9C/203-remove-spaces-at-the-beginning-of-some-users-names-which-confuses-ordering
We have some cases of `User` and `BatchInvitationUser` records in our production data that have leading and/or trailing whitespace in their name columns and we'd like to remove that whitespace because, in the case of `User`, it breaks alphabetical sorting by name.
Here we introduce some code to stop that happening again and a migration to fix the existing data.
> Remove unwanted spaces from users names

- db/migrate/20230801131609_change_event_logs_trailing_message_column.rb
- db/schema.rb
- test/services/user_update_test.rb
https://trello.com/c/mZuBjUXu
When a user has permissions added/removed we [record an event that includes the name of each permission][1]. If the length of the string containing all of these permission names exceeded 255 characters then the following exception was raised:
ActiveRecord::ValueTooLong
Mysql2::Error: Data too long for column 'trailing_message' at row 1
I considered truncating the message if it exceeded 255 characters but can't be confident that this data isn't being used elsewhere.
[1]: https://github.com/alphagov/signon/blob/0a2293f76e0ceb5d3eaf4c5e5167037cc82b80d1/app/services/user_update.rb#L52
> Change trailing_message column from varchar(255) to text

- app/controllers/batch_invitations_controller.rb
- app/models/batch_invitation_user.rb
- test/controllers/batch_invitations_controller_test.rb
- test/controllers/fixtures/users_with_non_valid_emails.csv
- test/models/batch_invitation_user_test.rb
https://trello.com/c/HOwVtQLy/184-give-batch-uploading-users-more-information-when-an-email-address-in-their-batch-is-invalid
Until now, one invalid email address in a batch upload (CSV) would raise
an ambiguous error and give the user no information about what went
wrong.
Now, if the batch encounters a validation problem, it returns to the
original form as before but also displays a more helpful error message.
Though, as I've implemented it, the message could be more helpful. But see for yourself:
> Give batch uploading users more information when an email address in their batch is invalid

- app/models/supported_permission.rb
- test/models/supported_permission_test.rb
https://trello.com/c/kgyjym0j/212-missing-validation-on-new-edit-application-permission-page
This pull request adds a validation rule that results in a more helpful error message if a user attempts to give 2 permissions the same name for a single application.
> Missing validation on new/edit application permission page

- app/views/api_users/_form_fields.html.erb
- app/views/api_users/new.html.erb
- app/views/devise/confirmations/show.html.erb
- app/views/devise/passwords/_change_password_panel.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/doorkeeper_applications/edit.html.erb
- app/views/suspensions/edit.html.erb
- app/views/two_step_verification_exemptions/edit.html.erb
- app/views/users/_form_fields.html.erb
- app/views/users/_user_filter.html.erb
- app/views/users/_user_filter_group.html.erb
- app/views/users/edit_email_or_password.html.erb
Trello: https://trello.com/c/WHsgcFDz
This explicitly sets the autocomplete attribute to "off" on all input elements unless there is [a specificly suitable value][1], e.g. "name", "email", "current-password", "new-password". Note that these values must apply for the current user and not for another user, e.g. when a user is editing the details of another user, autocomplete should be set to "off" for the "name" & "email" fields.
The original motivation behind this was that some password managers were filling in the "name" and "email" fields on the edit user page. This was because autocomplete was not set on the fields, the password manager heuristics decided that they were legitimate "name" & "email" fields, and (since there was only one matching item for the domain) the password manager …
> Set autocomplete attribute on input elements appropriately

- app/models/batch_invitation_user.rb
- app/models/reject_non_governmental_email_addresses_validator.rb
- app/models/user.rb
- test/models/batch_invitation_user_test.rb
- test/models/user_test.rb
https://trello.com/c/gME44pGU/210-prevent-new-users-with-being-created-with-non-governmental-email-addresses
Right now, a user can be created in Signon with any email address at
all. For example, you can create (and evidently people have created) new
users with `gmail.com` addresses.
This openness presents a number of potential security risks.
Here we use a custom validator to reject email addresses that match any of
a short list of well known email providers' domains.
Including these validation rules in `BatchInvitationUser` as well as
`User` means that the email addresses included in CSV uploads will be
verified, too. (Note that batch uploads encountering this new validation
error will still only see our generic "One or more emails were invalid"
error message for now. But the more …
> Prevent new users being created with non-governmental email addresses

- app/assets/stylesheets/_user_research_recruitment_banner.scss
- app/assets/stylesheets/application.scss
- app/controllers/root_controller.rb
- app/controllers/user_research_recruitment_controller.rb
- app/views/layouts/admin_layout.html.erb
- app/views/root/index.html.erb
- config/routes.rb
- db/migrate/20230804094159_add_user_research_recruitment_banner_hidden_to_users.rb
- db/schema.rb
- test/controllers/user_research_recruitment_controller_test.rb
- test/integration/user_research_recruitment_banner_test.rb
Trello: https://trello.com/c/yGMU3sR2
Supersedes #2301.
This adds a "sticky" banner on the Signon home page to recruit user research participants for GOV.UK Publishing. The "Find out more" button opens a Google Form (managed by the User Research folk) in a new browser tab. If the user clicks on this button, we record that in the Signon database and we never show them the banner again. If the user clicks on the "Hide this" button then we hide the banner for the duration of the current browser session, but it will be displayed to the user in their next browser session.
This is a reworked version of #2301 where I've addressed the issue that Calum spotted where the buttons in the banner were not full width on mobile screen widths. I've solved this by using a single form wrapped around the …
> Add user research recruitment banner v3

- app/helpers/two_step_verification_helper.rb
- app/mailers/mailer_helper.rb
- app/mailers/noisy_batch_invitation.rb
- app/mailers/user_mailer.rb
- app/models/govuk_environment.rb
- app/models/user.rb
- app/views/user_mailer/notify_reset_password_disallowed_due_to_suspension.text.erb
- app/views/user_mailer/suspension_notification.text.erb
- app/views/user_mailer/suspension_reminder.text.erb
- app/views/user_mailer/two_step_enabled.text.erb
- app/views/user_mailer/unlock_instructions.text.erb
- config/initializers/devise.rb
- config/initializers/instance_name.rb
- config/locales/department_specific.en.yml
- test/helpers/two_step_verification_helper_test.rb
- test/models/govuk_environment_test.rb
- test/models/noisy_batch_invitation_test.rb
- test/models/user_mailer_test.rb
- test/models/user_test.rb
Trello: https://trello.com/c/8HOXkVAT
Since the replatforming to k8s (a few months ago?), some application logic has not been correctly identifying the production environment. This has affected logic in the following functionality (see below for more details about each one):
* Mandating 2SV for users promoted to any admin role
* 2SV QR code issuer
* Automated email subject line, content & from address
Previously the implementation relied on the `INSTANCE_NAME` environment variable not being set in the production environment. However, since the replatforming to k8s, that environment variable has been [incorrectly set][1] to "production".
That means that since the replatforming a bunch of logic in the app has been working _incorrectly_. This was highlighted by some non-sensical text in an …
> Fix use of INSTANCE_NAME to determine environment-specific behaviour

- README.md
- docs/environment-variables.md
While I was working on https://github.com/alphagov/signon/pull/2311, I thought it would be useful to document the environment-variables used in the app. I think these are all the environment variables that are specific to this app or at least have an app-specific use in this app, but I might have missed some.
It would be nice to work out which ones are required in which environments, but that's a non-trivial amount of work, because the app doesn't seem to fail fast for at least some of the required ones.
Note that I haven't included env vars which are used as arguments to rake tasks or scripts.
> Add documentation about environment variables

- app/models/govuk_environment.rb
- config/initializers/govuk_admin_template.rb
- test/models/govuk_environment_test.rb
This follows on from [this PR][1].
The `GOVUK_ENVIRONMENT_NAME` env var is [made available to all apps][2] and is already being used in this app, e.g. to configure `GovukAdminTemplate`:
https://github.com/alphagov/signon/blob/2b935d7441b62545cb527e571312d709a33d0bba/config/initializers/govuk_admin_template.rb#L9-L10
The `GOVUK_ENVIRONMENT_NAME` env var has the same values as the `INSTANCE_NAME` env var in the different environments, i.e.
* ["integration"][3]
* ["staging"][4]
* ["production"][5]
So using `GOVUK_ENVIRONMENT_NAME` shouldn't change the behaviour of the app in any way.
We should look to remove the `INSTANCE_NAME` variable from `govuk-helm-charts` for the Signon app once this change has been deployed, because it will no longer be needed by this app.
I've also removed a bit of …
> Use GOVUK_ENVIRONMENT_NAME vs INSTANCE_NAME env var

- db/migrate/20230814160809_enable_pkce.rb
- db/schema.rb
- test/integration/doorkeeper_integration_test.rb
https://trello.com/c/59EBweBx
Signon utilises the [OAuth 2.0 Authorization Code Grant type][1] to enable users to authorize client applications to act on their behalf. That page includes:
> It is recommended that all clients use the [PKCE](https://oauth.net/2/pkce/) extension with this flow as well to provide better security.
This PR enables the PKCE extension in Doorkeeper. We're not yet mandating Signon clients to use PKCE but it will be used if the client supplies a `code_challenge` and `code_challenge_method` in the request for the Authorization Code.
We hope to mandate the use of PKCE once we're confident all Signon clients are using it.
[1]: https://oauth.net/2/grant-types/authorization-code/
> Enable OAuth2 PKCE extension in Doorkeeper

- config/initializers/govuk_admin_template.rb
It turns out that the `GOVUK_ENVIRONMENT_NAME` env var is not defined and the Rails env is not development or test during the GH action job which builds the image for deployment. This means that `GovukEnvironment.name` is `nil` and we see [the following exception][1]:
NoMethodError: undefined method `titleize' for nil:NilClass
I considered setting `GOVUK_ENVIRONMENT_NAME` in the GH action, but there didn't seem to be any precendent for doing that.
I also considered providing a fallback within the implementation of `GovukEnvironment.name`. However, I thought that might have other undesirable consequences.
So I've implemented the fallback in `config/initializers/govuk_admin_template.rb` which is a bit ugly, but hopefully it won't be too long before we get rid of `GovukAdminTemplate` …
> Provide fallback for GovukAdminTemplate.environment_label

- Dockerfile
- app/models/govuk_environment.rb
- config/initializers/govuk_admin_template.rb
- docs/environment-variables.md
- test/models/govuk_environment_test.rb
In [#2319](https://github.com/alphagov/signon/pull/2319) we fixed an issue which was triggered because this env var was not defined in the `build-and-publish-image` job in the `deploy` GH action.
This job uses [the shared `build-and-push-image` job][1] which [builds a Docker image][2] using Signon's `Dockerfile`. This `Dockerfile` is [based on][3] the `alphagov/govuk-ruby-base` image which [sets the `RAILS_ENV` env var to "production"][4].
The `Dockerfile` also includes [a command to run the `assets:precompile` task][5]. At this point the Rails app boots up and the code in `config/initializers/govuk_admin_template.rb` is executed.
Before the fix this resulted in [a call to `String#titleize` on `GovukEnvironment.name`][6] which was `nil`, due to the combination of `RAILS_ENV` being set to …
> Fail fast if GOVUK_ENVIRONMENT_NAME env var is missing in production env

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_contact-details.scss
- app/controllers/root_controller.rb
- app/views/components/_contact_details.html.erb
- app/views/components/docs/contact_details.yml
- app/views/layouts/admin_layout.html.erb
- app/views/root/privacy_notice.html.erb
- config/routes.rb
https://trello.com/c/AgYOfi7y/239-publish-the-signon-privacy-notice-and-link-to-it-in-signon-page
To meet one of the requirements of our Data Protection Impact Assessment, we're publishing this privacy notice and cookie policy for users of Signon.
I've had one eye on the styling of https://www.gov.uk/help/privacy-notice while working on this. Though, since that's a public facing page, I don't really know how similar this needs to be :confused: 
There's a suggestion on the Trello card about explaining what the page is for when linking to it. I haven't found an appropriate place to do that, since I've followed the convention of just including the link in the site's footer.
Things I'm still wondering:
- should the page heading have fewer capital letters in it?
- should the URL and footer …
> Publish /privacy-notice page

- app/models/event_log.rb
- app/models/user.rb
- config/initializers/date_formats.rb
- lib/expired_not_signed_in_user_deleter.rb
- lib/tasks/users.rake
- test/lib/expired_not_signed_in_user_deleter_test.rb
- test/models/user_test.rb
https://trello.com/c/hgj1pe57/243-delete-all-accounts-that-never-signed-in
1. Delete non-API users who were invited 90+ days ago and have never signed in.
2. Add a rake task so that a cron job can perform this action regularly.
> Delete non-API users who were invited 90+ days ago and have never signed in

- config/initializers/devise.rb
- test/integration/email_change_test.rb
- test/integration/inviting_users_test.rb
- test/test_helper.rb
https://trello.com/c/SWVUwQHc/101-consider-requiring-users-to-sign-in-after-accepting-invitation
To mitigate the security risk posed by leaked invitation tokens, we're
no longer automatically signing a user in when they accept an
invitation.
This is a feature of Devise's Invitable module, so not a lot of work on
our part (to enable or disable).
> Require user to sign in after accepting invitation

- app/models/event_log.rb
- test/factories/event_log.rb
- test/integration/user_locking_test.rb
- test/models/event_log_test.rb
Trello: https://trello.com/c/q1B1HKBy
Currently the Splunk-related functionality is effectively disabled, because neither of the relevant env vars are defined in any environment. See [this Trello card][1] for more details.
Prior to this commit, we were always queueing up a Sidekiq job whenever `EventLog.record_event` was called even though, as soon as that `SplunkLogStreamingJob` was executed, the first thing we did was give up if both the relevant env vars were not set.
Now we only queue up the job in the first place if the relevant env vars are defined. I've left the original check in `EventLog#send_to_splunk` in place, because there's a small chance the state of the env vars could change between the job being queued and the job being executed.
[1]: https://trello.com/c/Zp23Kd6c
> Avoid queueing job if Splunk-related functionality is disabled

- app/views/api_users/edit.html.erb
- app/views/api_users/index.html.erb
- test/integration/manage_api_users_test.rb
https://trello.com/c/dggyhTVY/62-api-users-page-fix-and-iterate-how-this-page-is-displayed
I'm making improvements to the API Users index page and these are the first and most straightforward bits.
The only users I've spoken to about these changes are Sean and Chris from the Platform Engineering team, who have had to make a lot of use of this page while working across multiple apps (particularly intensively while replatforming GOV.UK).
Is it OK to conclude that shipping this change will shed more light on any use cases that I haven't considered?
Before:
After:
> Trim API Users table

- db/seeds.rb
This PR adds the following users to db/seeds to complement the existing test.admin@gov.uk user:
- test.superadmin@gov.uk
- test.super-organisation-admin@gov.uk
- test.organisation-admin@gov.uk
I found the addition of these users useful while playing with the app in development.
I've also removed some duplication by using `Role::<role>#role_name` instead of hardcoded strings.
> Improve db seeds

- app/helpers/api_users_helper.rb
- app/views/api_users/index.html.erb
- test/integration/manage_api_users_test.rb
https://trello.com/c/dggyhTVY/62-api-users-page-fix-and-iterate-how-this-page-is-displayed
This tooltip was on our list of things that don't seem like they'd
comply with the design system.
So far I haven't found anybody who uses this feature.
Used to look like this:
Now it doesn't:
> Remove <abbr> tag from API Users table

- app/models/organisation.rb
- db/migrate/20230911092404_strip_whitespace_from_organisation_names.rb
- db/schema.rb
- test/models/organisation_test.rb
Trello: https://trello.com/c/rbUCwjHg
This commit removes and prevents unnecessary whitespace being added to `Organisation` `name` in a similar way to #2291 (for `User`). This only affects 1 record in integration and none in production, but it creates confusing ordering when we sort alphabetically by name.
> Fix and prevent unnecessary whitespace in organisation names

- app/controllers/root_controller.rb
- config/application.rb
- config/environments/test.rb
Trello: https://trello.com/c/cOsB2851
We've decided to disable the user research recruitment banner for now. I considered removing all of the relevant code but after talking to Joseph and Chris it seems likely that we'll want to bring this back in a month or two *and* retain the user's preference for hiding it.
I couldn't think of a great way of retaining the data in the `user_research_recruitment_banner_hidden` column on `users` and remind our future selves that we should use this data if we restore the banner from the git history. So instead I've decided to add a feature flag, turned off in production and development, but enabled in test (so we can retain the current test code too).
I'm not 100% convinced that keeping dead code around is a good idea, but based on what I know now this …
> Add a feature flag (disabled) for the user research banner

- app/controllers/account/applications_controller.rb
- app/controllers/accounts_controller.rb
- app/helpers/application_helper.rb
- app/helpers/navigation_items_helper.rb
- app/models/doorkeeper/application.rb
- app/models/supported_permission.rb
- app/policies/account_applications_policy.rb
- app/policies/account_page_policy.rb
- app/views/account/applications/index.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- test/factories/users.rb
- test/integration/account_applications_test.rb
- test/integration/account_test.rb
- test/models/doorkeeper_application_test.rb
- test/models/supported_permission_test.rb
- test/policies/account_applications_policy_test.rb
- test/policies/account_page_policy_test.rb
Trello: https://trello.com/c/7Hfe7eu0
This is the first step toward the new UI for allowing users to manage their own application permissions. It adds a page at `/account/applications` that lists the apps that a user does and doesn't have access to (i.e. those with and without the signin permission). We've chosen not to include retired apps as we don't think it makes sense for a user to be changing their permissions for retired apps.
The new applications page is currently only accessible to GOV.UK Admins (superadmins and admins). The intention is to make it available to Publishing Managers too but I'd prefer to get it working for the simpler case before tackling the complexity of Publishing Managers permissions.
Although not strictly necessary I've also chosen to add the `/account` path …
> Add a page listing the current user's applications

- config/initializers/prometheus.rb
- lib/collectors/global_prometheus_collector.rb
- test/lib/collectors/global_prometheus_collector_test.rb
This allows signon to provide prometheus metrics about the expiry time for api user tokens. The `metrics` method is called every time the `/metrics` endpoint is request, hence we cache the expensive database call as tokens are unlikely to change frequently.
These metrics would allow us to monitor and alert on expiring tokens that need rotating.
> Add token expiry timestamp Prometheus metrics

- app/controllers/batch_invitation_permissions_controller.rb
- app/controllers/batch_invitations_controller.rb
- app/helpers/batch_invitations_helper.rb
- app/models/batch_invitation.rb
- app/policies/batch_invitation_policy.rb
- app/views/batch_invitation_permissions/new.html.erb
- app/views/batch_invitations/new.html.erb
- config/routes.rb
- test/controllers/batch_invitation_permissions_controller_test.rb
- test/controllers/batch_invitations_controller_test.rb
- test/factories/batch_invitation.rb
- test/helpers/batch_invitations_helper_test.rb
- test/integration/batch_inviting_users_test.rb
- test/models/batch_invitation_test.rb
https://trello.com/c/FzaiUjkY/127-break-batchinvitations-new-into-two-separate-steps-to-prepare-for-migrating-to-the-design-system
This is the first step of moving `batch_invitations#new` to the design system. It breaks the large single page form into two separate steps across their own pages:
1. Upload user info
2. Manage permissions
The second step is implemented in its own controller.
> Break batch invitations creation into two steps

- app/models/batch_invitation_user.rb
- app/models/user.rb
- test/models/batch_invitation_user_test.rb
- test/models/user_test.rb
Trello: https://trello.com/c/dp3QzDlq
We've now chased up all users who were using one of our identified "non-governmental" email domains, so we can enforce this validation rule for all User accounts, not just new ones. This strengthens the validation we introduced in 00e93e9570.
> Prevent users changing their email addresses to non-governmental ones

- app/controllers/batch_invitations_controller.rb
- app/models/batch_invitation_user.rb
- test/controllers/batch_invitations_controller_test.rb
- test/integration/batch_inviting_users_test.rb
- test/models/batch_invitation_user_test.rb
Trello: https://trello.com/c/aO4nVCZT
* Avoid displaying validation errors on successful processing of file. Previously if a validation error was displayed and then corrected, the error was incorrectly displayed again on the success page.
* Strip leading & trailing whitespace from `BatchInvitationUser#email` before validation to avoid unnecessarily confusing validation errors.
* Strip leading & trailing whitespace from `BatchInvitationUser#organisation_slug` before save to avoid the potential for failing organisation lookups.
* Improve test coverage of `BatchInvitationUser#email` validation.
> Fixes for batch invitations

- test/models/user_test.rb
It was testing the wrong thing, now it's testing the right thing
> Fix copy-paste mishap in test setup

- db/migrate/20230925093142_strip_whitespace_from_batch_invitation_user_email.rb
- db/migrate/20230925093143_strip_whitespace_from_batch_invitation_user_organisation_slug.rb
- db/schema.rb
Trello: https://trello.com/c/aO4nVCZT
I forgot to do this as part of #2371.
I've constructed the query in the migration slightly differently to similar previous migrations, because I noticed the whitespace character in the regular expression wasn't working as intended. I plan to add new migrations for the columns we've already updated using the flawed query in a separate PR.
I've had to use `ActiveRecord::Persistence#update_attribute` in order to skip model validation, because some of the existing `BatchInvitationUser` records are invalid for other reasons.
I did consider writing the migration as a SQL `UPDATE`, but generating a `TRIM` expression that is exactly equivalent to `String#strip` isn't as trivial as it sounds!
> Strip whitespace from BatchInvitationUser email & organisation_slug

- app/models/batch_invitation_user.rb
- test/models/batch_invitation_user_test.rb
This was causing [a migration][1] to fail in integration with:
NoMethodError: undefined method `strip!' for nil:NilClass
This makes sense from the point of view that there is no validation on BatchInvitationUser#name and so there's nothing forcing it to be present.
I've added a unit test to force me to fix the problem.
[1]: https://github.com/alphagov/signon/blob/afe562d1905c90def59e80a5e483375538fa0935/db/migrate/20230925093143_strip_whitespace_from_batch_invitation_user_organisation_slug.rb
> Handle nil name in BatchInvitationUser#strip_whitespace_from_name

- db/migrate/20230925104847_strip_whitespace_from_user_name.rb
- db/migrate/20230925104848_strip_whitespace_from_batch_invitation_user_name.rb
- db/migrate/20230925104849_strip_whitespace_from_organisation_name.rb
- db/schema.rb
This includes new migrations to strip leading/trailing whitespace from:
* `User#name`
* `BatchInvitationUser#name`
* `Organisation#name`
In #2373 I noticed that the query we'd used to do this in #2291 & #2351 didn't escape the regular expression properly. ActiveRecord seems to have generated the following SQL `WHERE` expression:
WHERE (name REGEXP('^ +') OR name REGEXP(' +$')
I _think_ this will only have found names with leading/trailing space characters and not leading/trailing newlines/carriage-returns/tabs. Thus the previous migration didn't do anything bad, it just may have missed _some_ records.
In these new versions of the migration I've constructed the query slightly differently. Firstly I've double-escaped the whitespace character in the regular expression and secondly I've used …
> Fix for previous migrations that didn't strip whitespace for all the relevant records

- app/mailers/mailer_helper.rb
- app/mailers/user_mailer.rb
- app/views/user_mailer/suspension_notification.text.erb
- app/views/user_mailer/suspension_reminder.text.erb
- app/views/user_mailer/unlock_instructions.text.erb
- test/models/noisy_batch_invitation_test.rb
- test/models/user_mailer_test.rb
Trello: https://trello.com/c/0oTag1bi
This PR updates the content of the suspension reminder, suspension notification and unlock instruction emails following [some user research we did on their content](https://docs.google.com/document/d/1kIedI1QlYwf6RNjbVR3l4HApeRFmoHooShZNrDy7NNk/edit?pli=1).
> Update suspension and unlock email text

- app/helpers/users_helper.rb
- app/views/users/index.html.erb
Trello: https://trello.com/c/zNFNt7Oj
Two small improvements to the /users index page: 
- using a secondary quiet button for "upload a batch of users"
- removing the `2SV` `<abbr>` tag in the table header
> Users page improvements

- app/views/root/index.html.erb
https://trello.com/c/1AarwGE2/266-add-a-actions-and-settings-title-on-the-right-side-of-the-dashboard
Based on feedback from user research, without a heading, this section doesn't really look like anything at all.
Our page layout code isn't compatible with the specific layout suggested in the mock up (in the Trello card), so I've taken some cues from [this example Housing and local services page](https://www.gov.uk/get-help-energy-bills), putting the heading below the line.
> A heading for the right-hand section of dashboard

- app/controllers/invitations_controller.rb
- app/policies/user_policy.rb
- app/views/devise/invitations/new.html.erb
- app/views/users/_form_fields.html.erb
- lib/roles.rb
- test/controllers/invitations_controller_test.rb
- test/lib/roles_test.rb
- test/policies/user_policy_test.rb
Trello: https://trello.com/c/umBDQZUc
This is in preparation for splitting the page handled by the `InvitationsController#new` & `#create` actions into two pages with the second handling the setting of permissions. The `InvitationsController` is made more complicated than a typical controller for a few reasons, e.g.:
1.  The audience for the `#new`, `#create` & `#destroy` actions is admins & superadmins inviting new users; whereas the audience for the `#edit` & `#update` actions is new users accepting their invitations and setting their password.
2. It inherits from [`Devise::InvitationsController`][1] provided by `devise_invitable` but significantly customises its behaviour and its template(s) in `app/views/devise/invitations/`.
There's definitely a question in my mind about how much …
> Tidy InvitationsController

- lib/sso_push_credential.rb
- test/lib/sso_push_credential_test.rb
Trello: https://trello.com/c/piKwrxYP
Previously when a token reached its (10 year) expiry, the code in `SSOPushCredential.credentials` was still finding the expired token and trying to use it in the `SSOPushClient`, but triggering a `SSOPushError` exception due to an invalid bearer token, e.g. [this one](https://govuk.sentry.io/issues/4527419738/?project=202251).
While we were debugging this also realised that `SSOPushCredential.credentials` was also finding revoked tokens, thus making it impossible to resolve the situation from the Signon UI.
Now we ignore both expired & revoked tokens when deciding whether we already have a valid token or that we need to create one.
Note that [the `Doorkeeper::AccessToken.not_expired` scope][1] seems to helpfully exclude both expired *and* revoked …
> Ignore expired & revoked tokens in SSOPushCredential.credentials

- lib/collectors/global_prometheus_collector.rb
Tokens for the signon permissions users are automatically rotated once they expire, so we don't need to trigger alerts for them.
> Ignore reporting signon permission token expiry metrics

- Gemfile.lock
This will allow us to [upgrade selenium-webdriver][1].
[1]: https://github.com/alphagov/signon/pull/2406
> Upgrade govuk_test to 4.0.0

- .github/workflows/deploy.yml
We've been experiencing intermittent failures in this workflow that appear to be caused by `github.ref_name` being empty. Other teams in GDS have been [experiencing the same problem][1].
@theseanything has been in contact with GitHub support and received the following reply:
> We have an open internal issue where our engineers are investigating
> the intermittent unavailability of `github.ref_name` context when
> workflow runs are triggered on release events. I have added your report
> to the investigation.  We also have an open community discussion on
> this, You can add your voice to this. See below:
> https://github.com/actions/runner/issues/2788 As a workaround, could you
> try using `github.event.release.tag_name` instead, as this is the
> preferred method for referencing the tag …
> Use github.event.release.tag_name in Deploy workflow

- Gemfile.lock
This should allow us to [upgrade selenium-webdriver to 4.14.0][1].
[1]: https://github.com/alphagov/signon/pull/2415
> Upgrade govuk_test to 4.0.1

- app/helpers/users_helper.rb
- test/helpers/users_helper_test.rb
Trello: https://trello.com/c/R9bKDyi5
Rosa got in touch to say that this Organisation select box is not very usable, particularly in integration. The organisations are sorted in a seemingly random order and they include closed organisations that we never need to assign to new users.
This commit fixes both of those issues.
The previous tests stubbed `policy_scope` which is a Pundit-provided convenience for `Pundit.policy_scope` automatically passing in `current_user` as the first argument. I wanted to actually call the scope, so I could test that the `not_closed` and `order` scopes I've added were working correctly. To get `policy_scope` to work in the isolated tests I've explicitly included `Pundit::Authorization` in `UsersHelper` and stubbed `current_user` instead.
> Improve Organisation select on /users/invitation/new

- config/brakeman.ignore
I ran the following command which is based on [the version used in the CI pipeline][1]:
bundle exec brakeman . --except CheckRenderInline --interactive-ignore
And followed the instructions. It highlighted the one ignored warning as being "unused" and asked me whether I wanted to remove it, so I did.
[1]: https://github.com/alphagov/govuk-infrastructure/blob/b8b29b87e4c45c6ea010f29f17bc18fb78243712/.github/workflows/brakeman.yml#L20
> Update brakeman.ignore file against latest code

- app/controllers/account/manage_permissions_controller.rb
- app/helpers/users_helper.rb
- app/models/event_log.rb
- app/models/organisation.rb
- app/services/user_update.rb
- test/services/user_update_test.rb
We use the `UserUpdate` class in `Account::RoleOrganisationsController` to update the user's role and organisation. We're not passing `supported_permission_ids` in the `params` parameter to `UserUpdate#initialize` because we're not interested in changing a user's permissions in these operations. Unfortunately it turns out that `UserUpdate` expects to have the user's existing permissions passed in if you want them to remain unchanged. Otherwise `UserUpdate#filtered_user_params` will reset/clear all permissions for that user.
I've chosen to fix this in `UserUpdate#filtered_user_params` because it seems reasonable to me that leaving `supported_permission_ids` out of `params` should be interpreted as meaning that supported permissions shouldn't be changed.
Note that this bug would've caused …
> Fix permissions bug in UserUpdate

- app/models/supported_permission.rb
- db/migrate/20231017152747_add_foreign_key_constraint_for_user_application_permissions_application_id.rb
- db/migrate/20231017153040_add_not_null_constraint_for_supported_permissions_application_id.rb
- db/migrate/20231017153357_add_foreign_key_constraint_for_supported_permissions_application_id.rb
- db/schema.rb
- test/models/supported_permission_test.rb
Some data integrity issues have come up in the context of [this Trello card](https://trello.com/c/kvmb5OHO), so I wanted to sort them out so I could make sensible assumptions when making the actual changes I want to make for that Trello card!
There are a bunch of orphan records in `user_application_permissions` & `supported_permissions` tables which although they have an `application_id` value set, that value doesn't correspond with the `id` of a record in the `oauth_applications` table. My assumption is that the relevant records in `oauth_applications` have previously been deleted without deleting the associated records.
Since the `has_many :supported_permissions` association on `Doorkeeper::Application` includes the `dependent: :destroy` option and the `has_many …
> Add database contraints for permission-related application_id columns

- app/controllers/batch_invitation_permissions_controller.rb
- app/controllers/invitations_controller.rb
- app/models/user.rb
- app/views/batch_invitation_permissions/new.html.erb
- test/controllers/batch_invitation_permissions_controller_test.rb
- test/controllers/invitations_controller_test.rb
- test/integration/batch_inviting_users_test.rb
- test/models/user_test.rb
Trello: https://trello.com/c/5tHKKbWq
This PR ensures that any SupportedPermission with `default` set to `true` will be preselected in the user invitation and batch user upload permissions pages. With this change we no longer grant these permissions by default automatically, allowing the inviting user to deselect some of them if they are not appropriate for the specific user. 
I haven't included a migration to make the permissions listed in the trello card default. I figured we can easily do this through the UI once this change has landed (and double-check that we want the same permissions by default on both integration and production).
> Preselect default supported permissions when creating new users

- app/controllers/account/applications_controller.rb
- app/controllers/account/permissions_controller.rb
- app/controllers/account/signin_permissions_controller.rb
- app/controllers/doorkeeper_applications_controller.rb
- app/models/api_user.rb
- app/models/doorkeeper/application.rb
- app/models/supported_permission.rb
- app/models/user.rb
- app/views/batch_invitation_permissions/new.html.erb
- app/views/devise/invitations/new.html.erb
- app/views/doorkeeper_applications/edit.html.erb
- app/views/doorkeeper_applications/index.html.erb
- db/migrate/20231018141956_add_not_null_constraint_to_oauth_applications_retired.rb
- db/schema.rb
- test/controllers/batch_invitation_permissions_controller_test.rb
- test/controllers/doorkeeper_applications_controller_test.rb
- test/controllers/invitations_controller_test.rb
- test/factories/oauth_applications.rb
- test/models/doorkeeper/application_test.rb
- test/models/user_test.rb
Trello: https://trello.com/c/kvmb5OHO
While the Trello card is about hiding API-only apps, the overall motivation is to reduce the number of apps on various permissions pages and so I thought a good first step would be to exclude permissions relating to retired apps.
This adds a condition to the default scope on the `Doorkeeper::Application` model to only include `not_retired` applications in any query by default. It also incorporates this default scope into the `has_many :application_permissions` & `has_many :supported_permissions` associations on the `User` model. While using a default scope is perhaps a bit controversial, I think the notion of retiring an application is effectively a "soft delete" and this seems like a good use case for a default scope, not least because it should make …
> Hide retired apps on most pages

- app/assets/javascripts/modules/clear-selected-permissions.js
- app/views/batch_invitation_permissions/new.html.erb
- app/views/devise/invitations/new.html.erb
- spec/javascripts/modules/clear-selected-permissions-spec.js
- spec/support/jasmine-browser.json
Trello: https://trello.com/c/c6TxIASX
In #2436 we ensured that the default permissions for new users were checked in the permissions checkboxes on when inviting new users (singly or in a batch). This is a big time-saver for some inviting users who frequently add these
permissions. However there's a subset of inviting users who set up new user accounts who don't need these default permissions (e.g. when setting up users who use the Licensing app).
This PR adds a "Clear selected permissions" button to the `/users/invitations/new` and `/batch_invitations/:id/permissions/new` pages to make it easier for those inviting users to complete their task. 
Clicking the button clears the checked boxes and resets the "selected" counter for each app …
> Button to clear permissions on new user pages

- app/controllers/account/applications_controller.rb
- app/controllers/account/permissions_controller.rb
- app/controllers/doorkeeper_applications_controller.rb
- app/controllers/root_controller.rb
- app/models/doorkeeper/application.rb
- app/policies/user_permission_manageable_application_policy.rb
- app/views/doorkeeper_applications/edit.html.erb
- app/views/doorkeeper_applications/index.html.erb
- db/migrate/20231019080657_replace_oauth_applications_show_on_dashboard_with_api_only.rb
- db/schema.rb
- lib/user_permissions_controller_methods.rb
- test/controllers/account/applications_controller_test.rb
- test/controllers/account/manage_permissions_controller_test.rb
- test/controllers/account/permissions_controller_test.rb
- test/controllers/api_users_controller_test.rb
- test/controllers/batch_invitation_permissions_controller_test.rb
- test/controllers/doorkeeper_applications_controller_test.rb
- test/controllers/invitations_controller_test.rb
- test/controllers/root_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/account_applications_test.rb
- test/integration/dashboard_test.rb
- test/models/doorkeeper/application_test.rb
- test/policies/user_permission_manageable_application_policy_scope_test.rb
Trello: https://trello.com/c/kvmb5OHO
This follows on from #2446 in which we hid retired apps from most pages.
The idea in this PR is to hide API-only apps from most (but not all) pages in order to reduce the clutter on a bunch of pages - mainly (only?) pages which involve viewing/managing permissions for a user. It should no longer be possible to view or edit permissions for API-only apps on any pages except for the API user edit page and the "Edit supported permissions" page accessible via the application link in the "API-only" tab on the applications index page. We think this makes sense, because a non-API user should never need permissions for an API-only application.
Note that I've replaced `Doorkeeper::Application#show_on_dashboard` with `Doorkeeper::Application#api_only` and …
> Hide API-only apps on most pages

- .github/workflows/ci.yml
- script/minitest-ci
Trello: https://trello.com/c/66qRtGlu
This is closely based on alphagov/whitehall#8364.
In summary, this adds a new `script/minitest-ci` script which is called from within [a GitHub Action matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs). The script orders the tests randomly (but deterministically based on the commit SHA), splits them into 4 batches, and runs each batch of tests as a separate job. Since each job has its own container with a separate database, etc, the batches of tests are completely isolated from each other. An extra job is added on the end which waits for all the matrix jobs to finish successfully. See commit note for more details.
Looking at [recent CI build times](https://github.com/alphagov/signon/actions/workflows/ci.yml), this …
> Parallelize Ruby tests in CI build

- script/rails
This was originally added in 2012 in [this original commit][1] with Rails v3.2.3.
However, `bin/rails` was added in 2015 in [this commit][2] as part of #352 which upgraded the app to Rails v4. And this is now [the canonical location][3] for the `rails` script in our current version of Rails (v7.0.8).
It's confusing and potentially problematic to have both scripts in the repo, so I've removed the older one.
[1]: https://github.com/alphagov/signon/commit/d82798abe10189930f89803e959fb3494b956f9b
[2]: https://github.com/alphagov/signon/commit/640ae2fdec2cf21363dcb06cff39e7427cf21790
[3]: https://github.com/rails/rails/tree/v7.0.8/railties/lib/rails/generators/rails/app/templates/bin
> Remove defunct `script/rails` file

- app/models/user.rb
- app/views/api_users/edit.html.erb
- app/views/doorkeeper_applications/edit.html.erb
- app/views/shared/_user_permissions.html.erb
- app/views/users/_app_permissions.html.erb
- lib/sso_push_credential.rb
- test/controllers/api_users_controller_test.rb
- test/jobs/permission_updater_test.rb
- test/jobs/push_user_updates_job_test.rb
- test/jobs/reauth_enforcer_test.rb
- test/lib/collectors/global_prometheus_collector_test.rb
- test/lib/sso_push_credential_test.rb
- test/lib/tasks/sync_kubernetes_secrets_test.rb
- test/models/user_test.rb
Trello: https://trello.com/c/kvmb5OHO, https://trello.com/c/pN8KOiQV & https://trello.com/c/huqPdMv8
This follows on from #2452 & #2446. It's main focus is to ensure that we're not using access tokens for retired apps anywhere, e.g.
* Access tokens for retired apps no longer appear on the API user edit page.
* No longer send SSO Push requests to retired apps. Addresses [this Trello card][1].
* No longer include token expiry times to Prometheus for retired apps. This should mean that 2nd Line Tech do not see alerts for such tokens. At least partly addresses [this Trello card][2].
* No longer sync app secrets to K8s for retired apps. This was actually changed in #2446, but I've added a test for it in this PR.
[1]: https://trello.com/c/pN8KOiQV
[2]: https://trello.com/c/huqPdMv8
> Hide access tokens for retired apps

- app/models/users_filter.rb
- test/models/users_filter_test.rb
Trello: https://trello.com/c/kvmb5OHO
Previously, despite #2452, we were still showing permissions for API-only apps in the permissions filter on the users index page. Joseph spotted that I had missed it. This PR should fix it!
> Hide permissions for API-only apps on users index page

- lib/devise/models/suspendable.rb
Although the `Suspendable` csutom module is in the `Devise::Models` namespace, it wasn't very clear that `Suspendable#active_for_authentication?` and `Suspendable#inactive_message` override methods in `Devise::Models::Authenticatable`. Hopefully these comments will make things less confusing.
There are a bunch of other things in this module which aren't ideal, but I haven't addressed in this PR because I need to move on to something else:
* I wasn't even aware of its existence until just now - I think I had assumed it was an offical Devise module. I wonder it it would be better to inline the methods in this module into `User`, especially as it has some significant coupling to that class, e.g. the call to `User#revoke_all_authorisations`.
* The `active` & `suspended` scopes look like they …
> Add explanatory comments for Devise-related methods in Devise::Models::Suspendable

- app/models/doorkeeper/after_successful_authorization_processor.rb
- app/models/event_log.rb
- config/initializers/doorkeeper.rb
- test/integration/doorkeeper_integration_test.rb
- test/models/doorkeeper/after_successful_authorization_processor_test.rb
Trello: https://trello.com/c/2SRZa6cA
We've had some requests from other teams who want to know how often users log in to the applications they maintain.
We've decided to create an EventLog record each time a user is successfully authorized and an access token is created. This should be sufficient to answer the question "how many unique users have accessed a specific application in a given time period?".
I'll address the displaying of this data to users in a follow up PR once we've started collecting the data. At the moment the user-visible change as a consequence of this PR is the additional of a new event log item in the user's "access log":
> Log application access

- app/controllers/users_controller.rb
- app/policies/user_policy.rb
- test/controllers/users_controller_test.rb
- test/policies/user_policy_test.rb
The main thing I'm trying to achieve in here is to separate navigational concerns into the controller and authorization concerns into the policy class.
My motivation for doing this is that in [moving the "edit user" page to use the GOV.UK Design System](https://trello.com/c/uZD2I9dj), we're planning to have a separate page for changing just the email and I want to re-use the `Account::EmailsController` for users changing *another* user's email. I'm planning to move/rename `Account::EmailsController` -> `UserEmailsController` and share it between two sets of routes, one under the `account` namespace and one under the `users` resource, e.g. we will end up with paths like:
* `/account/emails/edit` (which already exists; to be used when a user edits their own email)
* …
> Separate navigational and authorization concerns in UsersController

- test/controllers/users_controller_test.rb
The `UsersControllerTest` is over 800 lines long and I was struggling to find my way around it. I think that using top-level contexts for the actions and 2nd-level contexts for signing in users with different roles is a bit less surprising.
My motivation for making these changes is that I'm currently [working on the user edit page](https://trello.com/c/uZD2I9dj) which means I'll be making a lot of changes in this area. Making these changes first will make that easier. And getting the commits merged soon will reduce the chance of any merge conflicts.
The commits are best viewed with the `--ignore-all-space` git diff option, because lots of the indentation has changed.
> Restructure users controller test

- test/controllers/users_controller_test.rb
Move 2 UsersControllerTest tests into appropriate context - I missed these in #2494.
As before my motivation for making these changes is that I'm currently [working on the user edit page](https://trello.com/c/uZD2I9dj) which means I'll be making a lot of changes in this area. Making these changes first will make that easier. And getting the commits merged soon will reduce the chance of any merge conflicts.
> More improvements to UsersControllerTest

- test/factories/users.rb
I've seen the string "A name is now required" on a number of occasions when trying to debug a failing test and incorrectly assumed that it related to some kind of unexpected validation error which has wasted a chunk of time.
This changes the name to use a sequence a bit like the email attribute which should be a lot less confusing in similar circumstances. 🤞
> Change default name in User factory to be less confusing

- app/controllers/users/names_controller.rb
- test/controllers/users/names_controller_test.rb
Trello: https://trello.com/c/DjdHEqxG
This was a mistake in #2497.
When the update completes successfully, the admin should be taken back to the "edit user" page for the user in question.
Previously they were redirected to the *non-existent* path for a non-existent `UsersController#show` action which was somehow (🤷) being handled by `UsersController#edit` as I intended!
> Fix redirect after admin updates another user's name

- app/controllers/users_controller.rb
- test/controllers/users_controller_test.rb
Trello: https://trello.com/c/PbX9UtR8
It's a bit hard to follow the git history of this controller, because it seems to have begun its life as a non-admin controller with actions allowing users to change their own user, but then in [this commit][1] a bunch of functionality from an admin controller was merged into it.
When we moved the users index page to use the Design System, we removed some actions from that page - see [this commit][2] & [this commit][3].
More recently we've split out a lot (all?) of the non-admin functionality into controllers under the `Account` namespace - see [this PR][4].
I'm pretty sure the redirects to `root_path` date back to a time when the action was called in the context of a user updating their own user. However, these three actions (`unlock_access`, …
> Fix redirects in UsersController actions: unlock_access, resend_email_change & cancel_email_change

- test/controllers/users_controller_test.rb
I should have removed this in #2503 when we stopped using `redirect_back_or_to` in the `UsersController#cancel_email_change` action.
> Remove redundant HTTP_REFERER header from UsersControllerTest

- test/controllers/users/names_controller_test.rb
This was a copy & paste error in #2497. I thought it was worth fixing it, because it's pretty much saying the opposite of what the assertion is testing.
> Fix test name in Users::NamesControllerTest

- lib/expired_oauth_access_records_deleter.rb
- test/lib/expired_oauth_access_records_deleter_test.rb
Trello: https://trello.com/c/GGWWve9b
We saw the following exception in production over the weekend:
> NoMethodError oauth_access_grants:delete_expired
>
> undefined method `name' for nil:NilClass application_names =
> records_by_user_id[user.id].map { |record| record.application.name }
The problem is that some of the expired `Doorkeeper::AccessToken`s belong to retired applications. Commit
9a9cd02d8574529b19f572a8352f031c3f07455e updated the default scope of `Doorkeeper::Application` so that it excludes retired apps by default.
The fix is to execute the query that finds the batch of expired grants/tokens within `Doorkeeper::Application.unscoped` so that we include retired apps.
As well as the tests added in this commit, I also used the Rails console in development, and its SQL query …
> Handle retired apps when deleting expired grants/tokens

- app/views/doorkeeper_applications/edit.html.erb
It took quite a bit of digging to understand what this setting does. Adding this will hopefully save someone else some time in future.
> Add help text to explain "Send push updates to this app"

- app/controllers/users/names_controller.rb
- test/controllers/users/emails_controller_test.rb
- test/controllers/users/names_controller_test.rb
Trello - https://trello.com/c/2t9zx0Aq
Prior to https://github.com/alphagov/signon/pull/2497 changing a user's name in Signon would queue a job to push that update out to the applications the user has access to. This PR reinstates the previous behaviour by using `UserUpdate` in `Users::NamesController#update`, which in turn uses `PermissionUpdater` to push updates to the user's apps.
I can't find any documentation that describes the changes that result in push updates to a user's applications, but as far as I can see, changing a user's name has resulted in a push update since the relevant functionality was added to [Signon][1] and [gds-sso][2] in 2012 so it seems reasonable that we retain this behaviour.
I've also added a test to ensure we continue to push email updates out to a user's …
> Update client apps when user's name changes

- app/helpers/account_applications_helper.rb
- app/views/account/applications/index.html.erb
- test/controllers/account/applications_controller_test.rb
- test/helpers/account_applications_helper_test.rb
Trello: https://trello.com/c/vInbSoSc
After reviewing the new account permissions pages we spotted a couple of small tweaks: 
- Change the wording of the "success" flash message
- Don't link to "update permissions" when there are no permissions to update.
> Copy tweaks for account application permissions

- app/views/users/emails/edit.html.erb
- app/views/users/names/edit.html.erb
The `#user_name_path` & `#user_email_path` route helper methods should require a `user` argument. However, the argument was not provided in either of the PRs where these forms were added (#2497 & #2509).
The assertions in `Users::NamesControllerTest` & `Users::EmailsControllerTest` were already comparing with the correct values and *somehow* the calls to `#user_name_path` & `#user_email_path` without any arguments were magically returning the correct value, even though when I try them in a Rails console, I get an `ActionController::UrlGenerationError`. So this mistake wasn't actually causing any problems.
> Fixes for edit user name & edit user email form actions

- config/initializers/govuk_error.rb
Trello: https://trello.com/c/MD4UabpW
Reently we've started seeing [a load of `ActiveRecord::StatementInvalid` exceptions][1] every night at about 01:00. These all wrap `Mysql2::Error` exceptions with a message along the following lines:
Table 'signon_production.<table-name>' doesn't exist
These exceptions seem to have started occuring around the time the db sync was moved to EKS. Presumably the sync is happening in a different way - perhaps table are being dropped & recreated when previously the data in the table was just being updated.
Anyway, [these docs][2] explain that we can configure Sentry to ignore specific exceptions that occur during the db sync and it looks like this is what other apps are relying on.
The [default `GovukError` configuration][3] excludes `PG:Error` & …
> Add Mysql2::Error to exceptions not reported during db sync

- app/controllers/users/organisations_controller.rb
- app/controllers/users_controller.rb
- app/policies/user_policy.rb
- app/views/users/_form_fields.html.erb
- app/views/users/names/edit.html.erb
- app/views/users/organisations/edit.html.erb
- config/routes.rb
- lib/roles/organisation_admin.rb
- lib/roles/super_organisation_admin.rb
- test/controllers/users/organisations_controller_test.rb
- test/controllers/users_controller_test.rb
- test/policies/user_policy_test.rb
Trello: https://trello.com/c/uZD2I9dj & https://trello.com/c/fA6dRVSm
This splits out the editing of another user's organisation into a separate page. The latest design calls for the splitting out the editing of a bunch of user fields into separate pages like this. The new "edit user organisation page uses the GOV.UK Design System, but the "edit user" page still does not. c.f. #2497,  #2509 & #2537.
The new "Change (organisation)" link on the "edit user" page only shows up if the current user is an Admin or a Superadmin, i.e. they have permission to change another user's organisation.
In my use of the [`error_summary` component](https://components.publishing.service.gov.uk/component-guide/error_summary) I have also brought the display of validation errors more into line with [this Design …
> Split out edit user organisation page from user edit page

- app/controllers/users/two_step_verification_resets_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/_form_fields.html.erb
- app/views/users/two_step_verification_resets/edit.html.erb
- config/routes.rb
- test/controllers/users/two_step_verification_resets_controller_test.rb
- test/models/user_test.rb
- test/support/managing_two_sv_helpers.rb
Trello: https://trello.com/c/uZD2I9dj & https://trello.com/c/caETStGa
This splits out the resetting of another user's 2SV into a separate page. The latest design calls for the splitting out of a bunch of user operations into separate pages like this. The new "reset user 2SV" page uses the GOV.UK Design System, but the "edit user" page still does not. c.f. https://github.com/alphagov/signon/pull/2497, https://github.com/alphagov/signon/pull/2509 & https://github.com/alphagov/signon/pull/2537.
Previously the "Reset 2-step verification" link on the "edit user" page was enhanced by UJS to prompt the user with a confirmation dialog and then submit a PATCH HTTP request to the controller. Since you now have to click the "Reset 2-step verification" link on the "edit user" page AND then click the …
> Add separate page for resetting another user's 2SV

- app/views/user_mailer/invitation_instructions.text.erb
- app/views/user_mailer/reset_password_instructions.text.erb
- config/locales/devise.en.yml
- config/locales/devise_invitable.en.yml
- test/integration/batch_inviting_users_test.rb
- test/integration/email_change_test.rb
- test/integration/inviting_users_test.rb
- test/integration/password_reset_test.rb
- test/models/batch_invitation_test.rb
- test/support/password_helpers.rb
Trello: https://trello.com/c/uENLLz5k
Copy and accessibility improvements to new account and password reset emails.
> Email copy updates

- app/controllers/users/two_step_verification_mandations_controller.rb
- app/views/users/_form_fields.html.erb
- app/views/users/two_step_verification_mandations/edit.html.erb
- config/routes.rb
- test/controllers/users/two_step_verification_mandations_controller_test.rb
- test/integration/managing_two_step_verification_test.rb
- test/support/managing_two_sv_helpers.rb
Trello: https://trello.com/c/uZD2I9dj & https://trello.com/c/caETStGa
This splits out mandating 2SV for another user into a separate page. The latest design calls for the splitting out of a bunch of user operations into separate pages like this. The new "mandate 2SV" page uses the GOV.UK Design System, but the "edit user" page still does not. c.f. https://github.com/alphagov/signon/pull/2497, https://github.com/alphagov/signon/pull/2509, https://github.com/alphagov/signon/pull/2537 & https://github.com/alphagov/signon/pull/2545.
Previously this functionality was implemented via a checkbox on the "edit user" page. This checkbox was only displayed when 2SV was not already mandated for the user either via an organisation mandate or an individual mandate, i.e. when `User#require_2sv?` was …
> Add separate page for mandating 2SV for another user

- app/views/suspensions/edit.html.erb
- app/views/users/event_logs.html.erb
The "access log" and "suspend/unsuspend user" pages are linked to from both the "edit user" page *AND* the "edit API user" page and so we should take that into account in the breadcrumb links to avoid confusing the user.
> Fix breadcrumbs for pages shared with API users

- app/helpers/users_helper.rb
Add `govuk-link` CSS class to action links on edit user page, so the links are styled more consistently with the rest of the app.
> Fix style of action links on "edit user" page

- app/controllers/api_users_controller.rb
- app/controllers/authorisations_controller.rb
- app/policies/api_user_policy.rb
- app/views/api_users/edit.html.erb
- app/views/api_users/manage_permissions.html.erb
- app/views/api_users/manage_tokens.html.erb
- app/views/authorisations/new.html.erb
- app/views/users/manage_permissions.html.erb
- config/routes.rb
- test/controllers/api_users_controller_test.rb
- test/integration/manage_api_users_test.rb
Trello: https://trello.com/c/wSKG73MP
This is a small step towards moving this page to use the GOV.UK Design System. Splitting the page up like this should mean we can work on different bits of the page in parallel.
Note that I've added breadcrumbs for the page as part of this.
> Split manage permissions and manage tokens out of "edit API user" page

- Dockerfile
- Gemfile.lock
And update `BUNDLED WITH` in `Gemfile.lock` to the appropriate Bundler version.
These were missed in #2583 and I think it means we haven't actually been running the app on v3.2.2 after that PR was merged.
> Upgrade Ruby v3.1.2 -> v3.2.2 in Dockerfile

- app/models/user.rb
- app/policies/user_policy.rb
- app/views/shared/_user_permissions.html.erb
- app/views/users/_app_permissions.html.erb
- test/models/user_test.rb
To be the inverse of `User#api_user?` and corresponding with the existing `User.web_users` scope.
We can use `User#web_user?` to avoid unnecessary inverse logic and make the code more readable by using `if user.web_user?` vs `unless user.api_user?` and `user.web_user?` vs `!user.api_user?`.
Also the callsite in `UserPolicy#exempt_from_two_step_verification?` was using the non-predicate attribute accessor which wasn't very idiomatic.
> Extract `User#web_user?` predicate method

- app/controllers/api_users_controller.rb
- test/controllers/api_users_controller_test.rb
These relate to a time when the `User` model had `accepts_nested_attributes_for :permissions`. However, these were renamed to `:application_permissions` in [this commit][1] and removed entirely in [this commit][2] all as part of #311 which was merged 8 years ago!
The controller test about pushing permission changes out to apps wasn't relying on the `permissions_attributes` param being set. And none of the form fields under `app/views/api_users/*` use the name.
[1]: https://github.com/alphagov/signon/pull/311/commits/e2126f392b312a05263b5ca26c13e6c68ad002fc
[2]: https://github.com/alphagov/signon/pull/311/commits/d0df5b1b0569ffc08f04cace7e8665102188e138
> Remove vestiges of `permissions_attributes` param

- app/controllers/suspensions_controller.rb
- app/policies/api_user_policy.rb
- app/views/api_users/edit.html.erb
- test/controllers/suspensions_controller_test.rb
- test/policies/api_user_policy_test.rb
Trello: https://trello.com/c/s9Qdhk0Y
Previously, `SuspensionsController#load_and_authorize_user` was only ever checking `UserPolicy#suspension?` to determine whether the current user was authorized to suspend/unsuspend an API user. This meant that although it hasn't been possible for Admins to *navigate* to the suspend/unsuspend user page for an API user, it would have been easy enough to hack the URL to reach the page and then there was nothing preventing them from suspending/unsuspending the API user.
I think this was an oversight when the `UserPolicy#suspension?` was introduced almost 9 years ago in https://github.com/alphagov/signon/pull/298. Since it was calling `User.find` it would never have returned an instance of an `ApiUser` and thus it would never have tried to use …
> Prevent Admins from suspending/unsuspending API users

- app/controllers/account/permissions_controller.rb
- app/controllers/users/permissions_controller.rb
- test/controllers/account/permissions_controller_test.rb
- test/controllers/users/permissions_controller_test.rb
- test/support/pundit_helpers.rb
Trello: https://trello.com/c/09yMSdcU
We noticed some problems with the implementation of both `Users::PermissionsController#update` and `Account::PermissionsController#update`:
1. The signin permission would be removed unless explicitly added in the call to `update`
2. Permissions not grantable from the UI would be removed unless explicitly added in the call to `update`
3. Permissions not grantable from the UI could be added if explicitly added in the call to `update`
4. Permissions could be passed to `UserUpdate` for applications other than the application whose permissions were being viewed
See the individual commits for more detail.
We're fixing these problems before moving the API User edit page to use similar functionality.
> Fix Users and Account::PermissionsController#update

- app/views/account/applications/index.html.erb
- app/views/account/permissions/edit.html.erb
- app/views/account/permissions/show.html.erb
Trello: https://trello.com/c/w3rzFU0k
We noticed that the "applications" and "view/update permissions" pages under a user account had inconsistent breadcrumb navigation when compared to, for example, "change your organisation" (`app/views/account/organisations/edit.html.erb`).
> Add missing breadcrumb links to account app/permissions pages

- test/controllers/users/applications_controller_test.rb
- test/controllers/users/emails_controller_test.rb
- test/controllers/users/invitation_resends_controller_test.rb
- test/controllers/users/names_controller_test.rb
- test/controllers/users/organisations_controller_test.rb
- test/controllers/users/permissions_controller_test.rb
- test/controllers/users/roles_controller_test.rb
- test/controllers/users/two_step_verification_mandations_controller_test.rb
- test/controllers/users/two_step_verification_resets_controller_test.rb
- test/controllers/users/unlockings_controller_test.rb
- test/controllers/users_controller_test.rb
- test/support/pundit_helpers.rb
This tidies up a bunch of controller tests as follows:
* [Extract `PunditHelpers#stub_policy_for_navigation_links`](https://github.com/alphagov/signon/pull/2597/commits/ab2f9261c53d09cf5e85518b056c7ddd24b8474b).
* [Stub all the policies used in the navigation items](https://github.com/alphagov/signon/pull/2597/commits/71929fd102f4373740a3fdb65bbd18906095db3c).
* A bunch of commits changing controller tests to use `PunditHelpers#stub_policy` instead  of stubbing `UserPolicy.new` directly.
> I ran into a problem with this, because when using the `PunditHelpers#stub_policy` helper method, the stubbing of `UserPolicy.new` specifies the arguments it should be called with, i.e. the `with(current_user, record)` bit of `policy_class.stubs(:new).with(current_user, record).returns(policy)`. This …
> Consistently use PunditHelpers#stub_policy in controller tests

- app/controllers/authorisations_controller.rb
- app/models/event_log.rb
- app/views/api_users/manage_tokens.html.erb
- test/controllers/api_users_controller_test.rb
- test/integration/manage_api_users_test.rb
- test/models/event_log_test.rb
The "Re-generate" button revokes the access token and creates a new one for the same API user and application. However, in the meantime application(s) will continue to use the old (now revoked) access token and thus API requests will fail. A separate step is needed to sync the new valid access token to the relevant application container(s).
I suspect this is why [the documentation][1] used by #govuk-2ndline-tech recommends first creating a new access token and only revoking the old one once the new one has been synced to the relevant application container(s) and is confirmed to be working OK.
I've also looked at the count of `EventLog` records in production which seems to confirm that the "Re-generate" button has rarely been used:
* `EventLog::ACCESS_TOKEN_GENERATED`: 88
* …
> Remove button for re-generating access token for API user

- Gemfile
- Gemfile.lock
- app/assets/javascripts/legacy_layout.js
- app/controllers/api_users_controller.rb
- app/controllers/authorisations_controller.rb
- app/policies/authorisation_policy.rb
- app/views/api_users/manage_tokens.html.erb
- app/views/api_users/new.html.erb
- app/views/authorisations/edit.html.erb
- app/views/authorisations/new.html.erb
- app/views/layouts/admin_layout.html.erb
- config/routes.rb
- test/controllers/api_users_controller_test.rb
- test/controllers/authorisations_controller_test.rb
- test/integration/manage_api_users_test.rb
- test/policies/api_user_policy_test.rb
- test/policies/authorisation_policy_test.rb
- test/support/pundit_helpers.rb
Trello: https://trello.com/c/75Jyg8zR
The majority of the commits in this branch are refactorings or other improvements intended to make the actual changes easier. The two key commits where the actual changes are made are:
* [Split out new page for revoking API user access tokens](https://github.com/alphagov/signon/pull/2616/commits/870045ef63737922a02d65352b3e3fb9f0cc0bdf)
* [Move API user manage tokens page to GOV.UK Design System](https://github.com/alphagov/signon/pull/2616/commits/32a74fa7de4614666680d54300f3c05a4a854012)
I've also made a few tweaks to other pages relating to API users in order to make all the pages more consistent with each other and with other pages across the site.
I considered displaying each token's expired/valid status on the manage tokens page using the [`tag` …
> Move managing tokens for API users to use GOV.UK Design System

- app/models/user.rb
- db/seeds.rb
- lib/devise/hooks/two_step_verification.rb
- lib/devise/models/suspendable.rb
- lib/inactive_users_suspender.rb
- test/controllers/api_users/applications_controller_test.rb
- test/controllers/api_users/permissions_controller_test.rb
- test/factories/users.rb
- test/helpers/users_with_access_helper_test.rb
- test/integration/admin_user_index_test.rb
- test/integration/password_reset_test.rb
Trello: https://trello.com/c/wSKG73MP
Arises from: #2599 
rubocop-govuk enables the "strict" style of the Rails/TimeZone cop[1]. This cop doesn't have a preference[2] for either of the equivalent methods `Time.zone.now` or `Time.current`. Since the latter is shorter and we're currently using a mixture of both I've gone with `Time.current`. I don't think we can enforce this without deviating from rubocop-govuk but hopefully being consistent now will help keep things that way.
[1]
https://github.com/alphagov/rubocop-govuk/blob/97fcbc866aa10a75c7c1c89fc3c2c562cc04fc26/config/rails.yml#L89 [2] https://github.com/rubocop/rubocop-rails/blob/cb01e4d6a33b0e4285b2972f9c64fc45e5776429/lib/rubocop/cop/rails/time_zone.rb#L26
> Replace Time.zone.now with Time.current

- test/controllers/api_users/permissions_controller_test.rb
- test/controllers/users/emails_controller_test.rb
- test/controllers/users/names_controller_test.rb
- test/controllers/users/organisations_controller_test.rb
- test/controllers/users/roles_controller_test.rb
- test/controllers/users/two_step_verification_mandations_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/sign_out_test.rb
- test/jobs/reauth_enforcer_test.rb
- test/lib/inactive_users_suspender_test.rb
- test/lib/inactive_users_suspension_reminder_test.rb
- test/lib/signin_permission_granter_test.rb
- test/lib/tasks/sync_kubernetes_secrets_test.rb
- test/models/batch_invitation_user_test.rb
Trello: https://trello.com/c/wSKG73MP
Arises from: #2599 
Using Mocha::ObjectMethods#expects "adds an expectation that the specified method must be called exactly once with any parameters"[1] so we don't need to chain `once` in these cases.
[1] https://mocha.jamesmead.org/Mocha/ObjectMethods.html#expects-instance_method
> Remove redundant use of `once` in tests

- app/helpers/api_users_helper.rb
- app/views/api_users/applications/index.html.erb
- test/helpers/api_users_helper_test.rb
Trello: https://trello.com/c/wSKG73MP
Arises from: #2599 
To ensure we keep up with changes to the design system this PR replaces the table markup on `/app/views/api_users/applications/index.html.erb` with the `table` design system component.
> Use table component on API users application index

- .github/dependabot.yml
I saw that @brucebolt had added this to a number of other repos (e.g. https://github.com/alphagov/collections/pull/3495) and thought it made sense to add it here too.
More information in the [GitHub Docs][1].
[1]: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
> Configure dependabot to monitor GitHub Actions

- app/views/layouts/admin_layout.html.erb
c.f. https://github.com/alphagov/whitehall/pull/8727
I considered using `Plek.external_url_for` to generate the URL based for the "status" app (like the code is already doing for the "support" app), but it doesn't look like there's an equivalent of that app in any other environments, so it didn't seem worthwhile.
> Add link to GOV.UK status page to footer

- app/controllers/account/permissions_controller.rb
- app/controllers/api_users/permissions_controller.rb
- app/controllers/users/permissions_controller.rb
- app/models/user_update_permission_builder.rb
- test/controllers/account/permissions_controller_test.rb
- test/controllers/api_users/permissions_controller_test.rb
- test/controllers/users/permissions_controller_test.rb
- test/models/user_update_permission_builder_test.rb
Trello: https://trello.com/c/yDM25WlZ
This PR is an attempt to remove some of the duplication we added in c7236440f, edf2e83e and 92c5f5c0 with the `build_user_update_params` controller method. I did consider folding some of this logic into `UserUpdate` but as we're currently thinking about simplifying or removing that altogether (e.g. #2623) I think for now it's an improvement to have the code shared between the three controllers via a simple Ruby object. It'll at least make it easier to move somewhere else in the future.
> Refactor build user update params

- app/assets/stylesheets/application.scss
- app/helpers/api_users_helper.rb
- app/helpers/application_table_helper.rb
- app/views/account/applications/index.html.erb
- app/views/api_users/applications/index.html.erb
- app/views/users/applications/index.html.erb
- test/controllers/users/applications_controller_test.rb
- test/helpers/application_table_helper_test.rb
- test/integration/account_applications_test.rb
- test/integration/user_applications_test.rb
Trello: https://trello.com/c/yDM25WlZ
This PR removes some duplication of logic in the views that render the `/account/applications`, `/users/:id/applications` and `/api_users/:id/applications` pages. It also removes the hard-coded HTML and instead relies on the `govuk_publishing_components` `table` component to generate the markup. 
In the final commit I introduce a small CSS override modelled on a similar pattern used in Whitehall to align the final "actions" column of the table to the right. 
There are some small visual differences after this refactor (notably we've lost the ability to specify the widths of the first two columns of the tables), but I've gone over these with Calum and we're happy that the changes introduced are acceptable given the overall improvement to consistency and …
> Refactor applications tables

- app/controllers/root_controller.rb
- app/views/layouts/application.html.erb
- app/views/root/accessibility_statement.html.erb
- config/routes.rb
- test/controllers/root_controller_test.rb
[Trello](https://trello.com/c/ryT5a6vG/402-add-our-accessibility-statement-to-signon)
> Add accessibility statement for signon

- app/views/layouts/application.html.erb
The layout_footer component was [changed in Dec 2023][1] to make all links absolute. Unfortunately this broke our privacy notice and accessibility statement links because they became `<Plek.new.website_root>/<path>` (e.g. www.gov.uk/privacy-notice in production). Using the `_url` helper methods should mean that we're correctly linking to these pages in the Signon app.
[1]: https://github.com/alphagov/govuk_publishing_components/commit/1cdd65fa90b895c0b1df64fbd2400d0099b5eb27
> Use absolute URLs in footer links

- app/helpers/components/.govuk_dependabot_merger.yml
[Trello](https://trello.com/c/rIHzlaZq/411-configure-signon-to-automatically-merge-internal-dependencies)
This is the first step in configuring automatic merging for all the internal (GOV.UK) dependencies, per documentation[1].
Only patch and minor versions will be eligible.
The next step will be adding signon to the opted-in repos [2], but it is contingent on getting this config merged.
[1] https://github.com/alphagov/govuk-dependabot-merger?tab=readme-ov-file#usage
[2] https://github.com/alphagov/govuk-dependabot-merger/blob/main/config/repos_opted_in.yml
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) …
> Configure automatic merging for internal deps

- config/application.rb
We introduced this cookie rotation code in e711982abbf as part of the upgrade to Rails 7. Since our session cookies do not have a `Max-Age` or `Expires` attribute they are treated by the browsers as Session cookies and expire when the browser window is closed. I think it's safe to assume that all cookies issued under the old scheme (sometime before approximately April 13th 2022 when e711982abbf was made) have now been rotated, so this code can be removed.
> Remove cookie rotate code

- app/helpers/api_users_helper.rb
- app/helpers/users_helper.rb
- app/views/api_users/index.html.erb
- app/views/users/index.html.erb
- test/helpers/users_helper_test.rb
- test/integration/manage_api_users_test.rb
The strikethrough is not part of the design system, so we've decided to use the govuk-tag style instead.
The design on the card showed green for active users, grey for suspended users, but there were no examples of locked or invited users.
I've chosen to only use green for active users, and grey for all other statuses.
[Trello](https://trello.com/c/ZW8yl3g8/280-review-discuss-other-options-possible-for-displaying-suspended-users-rather-than-strikethrough-since-this-isnt-inline-with-the-d)
Follow [these …
> Show user status as tag instead of strikethrough

- package.json
- yarn.lock
We've been seeing the following error running the Jasmine specs in a govuk-docker container running on Apple silicon:
SessionNotCreatedError: session not created:
Chrome failed to start: exited normally.
For a full diagnosis of the problem see [this govuk-docker PR][1] which was a first attempt at fixing the problem.
Note that the problem was also triggering a warning like the following even on non-Apple silicon:
The chromedriver version (120.0.6099.199) detected in PATH at
/usr/bin/chromedriver might not be compatible with the detected chrome
version (121.0.6167.85); currently, chromedriver 121.0.6167.85 is
recommended for chrome 121.*, so it is advised to delete the driver in
PATH and retry
This PR forces yarn to install v4.17.0 of the `selenium-webdriver` node package which includes [a …
> Fix Jasmine specs in govuk-docker on Apple silicon

- app/assets/stylesheets/components/_table.scss
For users with certain access needs (for example tunnel vision), the empty space between the table heading (in vertical table mode) and the table cell content causes difficulties, making them lose track of what labels associate with what values.
I found that the text would not become properly left-aligned at all magnification steps until I changed both the `text-align` property of all table cells, and the `justify-content` property.
Suggestions welcome, CSS is not my strongest area.
Follow [these …
> Allow table cell text to align left

- app/models/reject_non_governmental_email_addresses_validator.rb
- app/views/account/emails/edit.html.erb
- app/views/api_users/new.html.erb
- app/views/devise/invitations/new.html.erb
- app/views/users/emails/edit.html.erb
- app/views/users/names/edit.html.erb
- config/locales/en.yml
- test/controllers/account/emails_controller_test.rb
- test/controllers/api_users_controller_test.rb
- test/controllers/users/emails_controller_test.rb
- test/controllers/users/names_controller_test.rb
- test/integration/email_change_test.rb
- test/integration/inviting_users_test.rb
- test/models/batch_invitation_user_test.rb
- test/models/user_test.rb
This reverts commit 1eb45b8ce50223816ff7ebbe77d997310a1b2576.
The reverted commit left us in an inconsistent state when it came to displaying User validation error messages. Some of the validation error messages were standalone (e.g. "Enter an email for the user") while others only made sense when combined with the attribute (e.g. "Email can't contain non-ASCII characters").
I attempted to fix the problems with this inconsistency in PR #2717 but have now run out of time so have agreed with Craig S that it's better to revert the problematic commit for now.
> Revert "Improve User validation messages"

- app/controllers/sessions_controller.rb
- test/controllers/sessions_controller_test.rb
Trello: https://trello.com/c/qo01Wq1w
We were seeing [the following exception][1] when there was no `user` param in the request:
NoMethodError: undefined method `[]' for nil:NilClass (NoMethodError)
I've added a test to demonstrate the problem and fixed it by using [`Devise::SessionsController#sign_in_params`][2].
Since `SessionsController` inherits from `Devise::SessionsController`, we probably should have been using this method anyway to properly sanitize the `params`. Using that method also has the benefit of fixing the problem, because it will always return an empty `Hash` rather than `nil`.
I've also taken the opportunity to replace a comment in the implementation with an explanatory test.
As noted in the Trello card, I think we could make further improvements in this controller by …
> Fix NoMethodError in SessionsController#create

- db/migrate/20240228080000_reencrypt_user_otp_keys.rb
- db/schema.rb
In Rails 7.0, the [encryption algorithm was changed from SHA-1 to SHA-256](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#active-record-encryption-algorithm-changes) but users who generated their OTP key when we used an older version of Rails  would still have their key stored with SHA-1. Rails 7.0 could support both types of encryption by default, so we saw no issues.
However in Rails 7.1, the option `support_sha1_for_non_deterministic_encryption` is set to `false` by default, meaning users encrypted with SHA-1 would be unable to login.
We therefore changed this setting to `true` [when upgrading to Rails 7.1](https://github.com/alphagov/signon/pull/2745/commits/90d4cf0ea3f0df5013b7fedfeddcd0570b90cc10). By re-encrypting all users with SHA-256, we can disable this setting. …
> Re-encrypt all users

- config/application.rb
This reverts commit 90d4cf0ea3f0df5013b7fedfeddcd0570b90cc10.  Depends on https://github.com/alphagov/signon/pull/2746.
[Trello card](https://trello.com/c/ljplz6sM)
> Remove support for SHA-1 encryption

- lib/tasks/once_off/add_gds_editor_permission.rake
One-off rake task to add the GDS Editor permission  (if not already present) and grant it to any user who has the Imminence signin permission and is in GDS.
Needed so that GDS people who currently access Imminence will not lose the ability to see all datasets after the organisation data permissions update is merged. We can review and remove permissions later if necessary.
https://trello.com/c/UHBoqLxy/2358-add-per-department-permissions-to-imminence
> One-off rake task to add the GDS Editor permission 

- db/migrate/20240423105028_remove_user_application_permissions_with_deleted_supported_permission.rb
- db/schema.rb
[Trello](https://trello.com/c/J0Aq6mq6/1115-investigate-a-weird-nomethoderror-bug-with-permissions-that-mara-found)
We've been seeing `NoMethodError`s raised when trying to fetch certain users' current permissions in the permissions update flow
It appears that the `SupportedPermission` with ID `2316` has been deleted, but that the associated `UserApplicationPermission`s were not, despite the model callbacks that should destroy dependencies. There are 46 `UserApplicationPermission`s with a `supported_permission_id` of `2316`. This is currently the only `supported_permission_id` without a corresponding `SupportedPermission` that appears in any `UserApplicationPermission`s, so hopefully the missed callbacks were an isolated incident. This commit therefore adds a migration to deal with this …
> Add migration to clean up `UserApplicationPermission`s

- .github/workflows/deploy.yml
- Dockerfile
This swaps signon to use the multi-architecture workflow so we start getting side-by-side AMD86 and ARM64 builds. So we can start testing an ARM-flavour of Signon in Integration.
Pinging @JonathanHallam for visibility on the Pub Platform team (I think).
> Start making ARM builds for Signon

- Dockerfile
This bumps the version of Ruby to 3.2.3, as we don't have any ARM base/builder images for 3.2.2. This should un-break the build hopefully.
> Bump Ruby to 3.2.3 for ARM builds.

- db/migrate/20240429130154_remove_user_permissions_with_deleted_permission.rb
- db/schema.rb
Copy of @yndajas migration to clean up an errant UserApplicationPermission
A different UserApplicationPermission was present in Production vs integration, this removes that permission.
See https://github.com/alphagov/signon/pull/2829 for further context.
Trello: https://trello.com/c/lFr9qVJq/1132-remove-deleted-permissions-from-users
> Another migration to clean up `UserApplicationPermissions`

- app/views/layouts/_google_tag_manager.html.erb
- app/views/layouts/application.html.erb
Based on the work we did previously on publisher in https://github.com/alphagov/publisher/pull/1963
There are no other calls to content_for :head in this application, so it should be fine to call it directly here.
Tested locally with:
GOOGLE_TAG_MANAGER_AUTH=some-auth
GOOGLE_TAG_MANAGER_ID=some-id
GOOGLE_TAG_MANAGER_PREVIEW=some-preview
Gives this snippet in the head:
//<![CDATA[
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl+'&gtm_cookies_win=x&gtm_auth=some-auth&gtm_preview=some-preview';f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','some-id');
//]]>
We'll …
> Add Google Tag Manager configuration to Signon

- app/controllers/supported_permissions_controller.rb
- app/views/supported_permissions/confirm_destroy.erb
- app/views/supported_permissions/index.html.erb
- config/routes.rb
- docs/usage.md
- test/controllers/supported_permissions_controller_test.rb
It is not currently possible to delete a supported permission through the user interface.
This has led to code being run on a Rails console when permissions need to be deleted, which has led to other issues because the wrong method was invoked (`delete` instead of `destroy`, which didn't delete the associated `UserApplicationPermission` records).
Therefore adding a delete button (including confirmation view) to allow to do be done in the user interface.
| Action | Screenshot |
| -- | -- |
| Index for supported permissions, showing new 'Delete' link | ![Screenshot showing the index for supported permissions for a fake application.  There is now a red 'Delete' …
> Add button to delete application supported permissions

- lib/tasks/sync_kubernetes_secrets.rake
- test/lib/tasks/sync_kubernetes_secrets_test.rb
We used to have a lot of cruft lying around in Signon, but now it's much tidier. It's now feasible for us to just import the secrets for all active (non-retired) Doorkeeper applications and all non-suspended API users.
This removes an awkward step in setting up or renaming an application which tends to trip people up.
> Make secrets sync zero-configuration.

- app/views/account/roles/edit.html.erb
- app/views/users/roles/edit.html.erb
- test/integration/account_roles_test.rb
- test/integration/change_user_role_test.rb
[Trello](https://trello.com/c/sW9M14wM/1191-change-your-role-input-not-prefilled-with-current-data)
On the pages where a user can edit their or another user's role, the select element always had "Normal" preselected, regardless of the user's actual current role. This was because of a mistake in the preselection logic, which is fixed here
---
> Fix current role on edit role pages

- lib/tasks/permissions.rake
- test/lib/tasks/permissions_test.rb
[Trello](https://trello.com/c/SlnFFy5r/1192-create-a-template-rake-task-where-we-update-multiple-users-permissions-based-on-a-condition)
This adds a Rake task to remove the Whitehall editor permission from non-GDS users with the managing editor permission
---
> Remove editor permission rake task

- lib/tasks/permissions.rake
[Trello](https://trello.com/c/SlnFFy5r/1192-create-a-template-rake-task-where-we-update-multiple-users-permissions-based-on-a-condition)
This Rake task didn't have any count logging, so in order to be sure it worked, you'd have to run some of the code after (and also ideally before) running the Rake task to check the permission counts. This task has already been run, but we may reuse it in future and/or use it as a template for other similar Rake tasks, so we should make it more of a best practice example now
---
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#me …
> Add logging to permission removal Rake task

- app/assets/javascripts/modules/accessible-autocomplete.js
- app/assets/stylesheets/components/_accessible-autocomplete.scss
- spec/javascripts/modules/accessible-autocomplete-dropdown-spec.js
[Trello](https://trello.com/c/adKh8Cas/1207-make-autocomplete-arrow-work)
There's an [ongoing issue][1] with the accessible autocomplete that stops the arrow from opening the options menu when `showAllValues: true` is enabled. The `showAllValues: true` option shows all values when focused on the autocomplete element without having typed anything. This somewhat fixes the behaviour in Signon
https://github.com/alphagov/signon/assets/40244233/44f96253-9a32-4297-bc2a-9e3066255459
https://github.com/alphagov/signon/assets/40244233/58f8a357-483d-4512-a760-44cb2e2d3d40
--- …
> Make autocomplete arrow button work

- app/assets/javascripts/modules/accessible-autocomplete.js
- app/assets/stylesheets/components/_accessible-autocomplete.scss
- app/controllers/account/permissions_controller.rb
- app/controllers/users/permissions_controller.rb
- app/views/account/permissions/edit.html.erb
- app/views/shared/_add_permissions_with_autocomplete_form.html.erb
- app/views/users/permissions/edit.html.erb
- test/controllers/account/permissions_controller_test.rb
- test/controllers/users/permissions_controller_test.rb
- test/integration/account_applications_test.rb
- test/integration/granting_permissions_test.rb
[Trello](https://trello.com/c/4ABkAgkF/1210-allow-multiple-permissions-to-be-selected-before-being-added)
The new autocomplete form for adding permissions to apps with more than eight supported permissions redirects users to the applications path after adding a permission. Sometimes users want to add multiple permissions at the same time. This offers a middle ground, whereby we still have a single value autocomplete, but there's an option to be redirected back to the form after adding each permission
https://github.com/alphagov/signon/assets/40244233/7043870b-7cd9-454e-89dd-54dee5c523e5
https://github.com/alphagov/signon/assets/40244233/70d45b1f-4feb-4cf3-a941-cc972a159e60
---
This application is owned by the publishing platform team. Please let us know in #govuk-publishing-platform when …
> Allow adding multiple permissions with autocomplete

- Dockerfile
- app/models/govuk_environment.rb
- docs/environment-variables.md
- lib/healthcheck/api_tokens.rb
- test/lib/healthcheck/api_tokens_test.rb
- test/models/govuk_environment_test.rb
- test/test_helper.rb
Both environment variables are set to the same value. GOVUK_ENVIRONMENT is used more frequently, renaming for consistency.
> Use GOVUK_ENVIRONMENT instead of GOVUK_ENVIRONMENT_NAME

- app/models/event_log.rb
- app/models/log_entry.rb
- app/views/shared/_event_logs_table.html.erb
- test/integration/account_activities_test.rb
Response to some user concerns about often automated account activity. Decided to restrict visibility of certain events `Access token generated`, `Access token revoked`, `Access grants deleted`, `Access tokens deleted`.
Visibility of these events was causing confusion for some users, so restricting them to admin/superadmin only visibility seemed sensible.
Trello: https://trello.com/c/Vv4Dn2O7/1193-only-display-technical-events-in-user-activity-log-for-admins-superadmins
Follow [these …
> Hide certain account activity events from non-admins

- app/helpers/application_table_helper.rb
- app/views/api_users/applications/index.html.erb
- test/helpers/application_table_helper_test.rb
[Trello](https://trello.com/c/A51nRJZy/1234-refactor-applicationtablehelper)
This is some groundwork for fixing the broken delegatable permissions feature: a minor refactor (mostly a restructure/tidy up) of the `ApplicationsTableHelper`, which is used to generate "Grant access", "Remove access", "View permissions", and "Update permissions" buttons/links on applications pages
---
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails …
> Refactor `ApplicationTableHelper`

- app/assets/stylesheets/application.scss
- app/helpers/application_table_helper.rb
- app/views/account/applications/index.html.erb
- app/views/api_users/applications/index.html.erb
- app/views/users/applications/index.html.erb
- test/helpers/application_table_helper_test.rb
[Trello](https://trello.com/c/2hbs3qaV/1231-fix-applications-table-alignment-issues)
We've had issues with the height of the final column in the applications tables since at least February. This fixes it
---
> Fix applications table actions column

- test/integration/granting_permissions_test.rb
A quick fix for a couple of comments that incorrectly describe assertions
---
> Fix test comment

- app/helpers/components/table_helper.rb
- app/views/account/applications/index.html.erb
- app/views/api_users/applications/index.html.erb
- app/views/components/_table.html.erb
- app/views/users/applications/index.html.erb
[Trello](https://trello.com/c/Vn5vDNV8/1232-fix-applications-tables-column-alignment)
In #2341, the table component from `govuk_publishing_components` was copied over and customised
In #2664, we migrated the applications tables to use this. In the process, we lost the custom classes on the first two columns, which set the widths to 1/4 and 1/3 respectively. This was noted as "acceptable" in the PR body in exchange for improved consistency and other benefits from using the component
However, since we have a custom version of the table component, it's very easy for us to support custom classes. This was in fact done in the same PR that copies the component into the Signon codebase, adding custom class support for the outer table element in 4f09fbc
This adds support for custom classes in the …
> Fix applications tables column alignment

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_table.scss
- app/views/account/applications/index.html.erb
- app/views/api_users/applications/index.html.erb
- app/views/components/_table.html.erb
- app/views/users/applications/index.html.erb
- db/seeds.rb
- test/controllers/account/applications_controller_test.rb
- test/controllers/api_users/applications_controller_test.rb
- test/controllers/users/applications_controller_test.rb
[Trello](https://trello.com/c/9pwUMehD/1233-use-vertical-layout-for-applications-table-on-small-screens)
Since https://github.com/alphagov/signon/pull/2341, we've had support for making tables use a vertical layout on smaller viewports, similar to how the summary list reflows on smaller viewports (the end result is something of a hybrid of table and summary list layouts)
We already use this on the users screen. This feels like something that would be useful on the applications screen too
---
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-requ …
> Make applications table vertical on small screens

- app/helpers/application_table_helper.rb
- app/views/account/applications/index.html.erb
- app/views/users/applications/index.html.erb
- docs/access_and_permissions.md
- test/controllers/account/applications_controller_test.rb
- test/controllers/users/applications_controller_test.rb
- test/helpers/application_table_helper_test.rb
[Trello](https://trello.com/c/VNAR8G4o/1250-show-view-permissions-link-even-when-updatable)
Previously on the applications pages the view permissions link wouldn't show if the user could edit permissions. However, we'll soon fix delegatable permissions, which will mean that publishing managers will only see delegatable permissions on the update permissions page. It would be useful for them to be able to see all permissions, even if they can't grant non-delegatable ones, so we should show the view link regardless of update authorisation
--- …
> Show view permissions link even when updatable

- lib/tasks/event_log.rake
[Trello](https://trello.com/c/jPtUcWij/1256-check-whether-any-user-in-departments-check-whether-any-users-in-non-gds-departments-have-recently-used-the-delegatable-permissi)
This will help us find out more about which permissions are being added and removed by and for non-GDS users. We want to use this information to inform how we proceed with the work to fix delegatable permissions
---
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing …
> Add Rake task for querying permissions event logs

- lib/tasks/event_log.rake
[Trello](https://trello.com/c/jPtUcWij/1256-check-whether-any-user-in-departments-check-whether-any-users-in-non-gds-departments-have-recently-used-the-delegatable-permissi)
The output of this Rake task is a CSV-formatted string. Two of the columns contain organisation names, which themselves occasionally include commas. This wraps the organisation name columns in quote marks to prevent each of these being read as multiple columns
---
Follow [these …
> Fix organisation column in permissions Rake task

- Gemfile
- Gemfile.lock
- app/assets/config/manifest.js
- app/assets/javascripts/application.js
- app/assets/javascripts/es6-components.js
- app/assets/stylesheets/components/_table.scss
- app/views/layouts/application.html.erb
- config/environments/production.rb
I've followed the instructions for [Upgrading to GOV.UK Frontend v5 in the govuk_publishing_components gem](https://docs.google.com/document/d/1uwip7pzQwM7t5ghn9_8KrsWXLePSRUltFPZ5fYw6Ab8/edit). And, as predicted, this app didn't require _all that many_ changes
https://trello.com/c/aZ4vNT80/1240-upgrade-govukpublishingcomponents-for-signon
> Upgrade to govuk_publishing_components version that uses GOV.UK Frontend V5.1

- docs/access_and_permissions.md
The access and permissions documentation doesn't currently cover what users can do when inviting new users. This adds coverage for that
---
> Document invitations access and permissions logic

- docs/access_and_permissions.md
[Trello](https://trello.com/c/acNFcZG0/1263-document-how-access-and-permissions-work-for-new-users-invitations)
Update access and permissions files documentation to cover files used by the `InvitationsController`. This was missed in #3035 
---
> Update access and permissions files documentation

- .github/dependabot.yml
Dependabot has a [default limit of 5](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/troubleshooting-dependabot-errors#dependabot-cannot-open-any-more-pull-requests) for the number of pull requests it will open on a repo. We have missed some updates today, since Dependabot has been limited to the numbe of updates it can open.
Therefore increasing the limit to 20, as we are unlikely to exceed this.
> Increase dependabot PR limit for Ruby gems

- app/views/accounts/show.html.erb
Ensure the accounts settings page uses a 3 column layout
The card component in the govuk_publishing_components gem will be updated to use a one column layout by default in a future release - https://github.com/alphagov/govuk_publishing_components/pull/4118
Setting `three_column_layout` to true will ensure the accounts settings page still uses a 3 column layout
[Trello card](https://trello.com/c/JFKnseKS/2714-create-a-pr-in-signon-the-only-other-place-in-alphagov-using-the-card-component-to-set-a-3-column-layout-s-m)
---
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline. …
> Ensure the accounts settings page uses a 3 column layout

- test/controllers/users/applications_controller_test.rb
Fixes a superficial typo from #3040.  Curiously, this isn't a syntax error, but it is redundant and belongs in the bin
---
> Remove stray slash

- test/integration/granting_permissions_test.rb
It looks as though these tests hadn't been updated after a change in the UI, so they were asserting on the absence of something on a page where it would never appear. This fixes setup and assertions to match the current scenario
---
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if …
> Fix false negative tests

- app/controllers/users/applications_controller.rb
- app/policies/users/application_policy.rb
- docs/access_and_permissions.md
- test/controllers/users/applications_controller_test.rb
This is another step to bring the users and account access and permissions flows more in sync
---
> Use `Users::ApplicationPolicy` in `Users::ApplicationsController`

- app/policies/account/application_policy.rb
- test/policies/account/application_policy_test.rb
- test/policies/users/application_policy_test.rb
This brings things more in like with the `Users::ApplicationPolicy` test suite, making more use of stubbing and DRYing things up
---
> Refactor `Account::ApplicationPolicy` test suite

- app/controllers/account/permissions_controller.rb
- app/controllers/users/permissions_controller.rb
- app/helpers/application_table_helper.rb
- app/models/doorkeeper/application.rb
- app/policies/account/application_policy.rb
- app/policies/supported_permission_policy.rb
- app/policies/users/application_policy.rb
- docs/access_and_permissions.md
- test/controllers/account/applications_controller_test.rb
- test/controllers/account/permissions_controller_test.rb
- test/controllers/users/applications_controller_test.rb
- test/controllers/users/permissions_controller_test.rb
- test/helpers/application_table_helper_test.rb
- test/integration/account_applications_test.rb
- test/integration/granting_permissions_test.rb
- test/models/doorkeeper/application_test.rb
- test/policies/account/application_policy_test.rb
- test/policies/supported_permission_policy_scope_test.rb
- test/policies/users/application_policy_test.rb
This is the main PR for fixing delegatable permissions. This is the first that will actually change how things work: publishing managers (organisation and super organisation admins) will now only be able to manage permissions marked as delegatable (for users of equal or lower level in the same organisation, or a child organisation for super organisation admins)
---
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/developme …
> Fix delegatable permissions

- app/controllers/account/permissions_controller.rb
- app/controllers/users/permissions_controller.rb
- app/helpers/application_permissions_helper.rb
- app/models/doorkeeper/application.rb
- app/views/account/permissions/edit.html.erb
- app/views/users/permissions/edit.html.erb
- test/helpers/application_permissions_helper_test.rb
- test/integration/account_applications_test.rb
- test/integration/granting_permissions_test.rb
- test/models/doorkeeper/application_test.rb
[Trello](https://trello.com/c/UGZFWxk3/1292-add-notice-to-edit-permissions-page-about-delegatable-filter)
This will be shown to publishing managers on the edit permissions page when there are non-delegatable non-signin permissions so that they are aware that they aren't seeing all permissions for the given app
---
> Show notice when there are non-delegatable perms

- app/controllers/root_controller.rb
- app/views/root/index.html.erb
In 8ad9b99, I removed `UserPermissionsControllerMethods`, which is where this code previously lived, since this was the only place it was being used. However, it looks like we don't even use the permissions, so we can just pass down the applications that we get in a previous line
---
> Remove redundant RootController code

- app/models/doorkeeper/application.rb
- app/models/supported_permission.rb
- test/models/doorkeeper/application_test.rb
- test/models/supported_permission_test.rb
The `sorted_supported_permissions_grantable_from_ui` method was getting a little complex, with a lot of conditional logic. This separates out the sorting and filtering, with the former the responsibility of the `SupportedPermission` model, and the latter remaining the responsibility of the `Doorkeeper::Application` model based on the passed in arguments
In the `Doorkeeper::Application` tests, we're using [Mocha's with][1] with a block using [Minitest's assert_same_elements][2] to check that the array argument contains the same elements regardless of order
Mocha does have various [ParameterMatchers][3], which can be used with `with`, but unfortunately not an equivalent of `assert_same_elements` or something like [Jest's expect.arrayContaining][4]
[1]: …
> Refactor supported permissions method

- app/models/user_application_permission.rb
- test/models/user_application_permission_test.rb
This was used by the `UserApplicationPermissionPolicy`, which was deleted in 2a78b5c
---
> Removed unused method

- lib/tasks/event_log.rake
[Trello](https://trello.com/c/F4b1rEqL/1293-identify-and-revoke-permissions-which-have-been-inappropriately-granted-to-users-by-org-superorg-admins)
This will be used to find out if any non-GDS publishing managers have given non-GDS users permissions that we wouldn't expect them to be giving (as a result of the broken delegatable permissions feature)
---
> Add Rake task for querying non-GDS permissions

- lib/tasks/event_log.rake
[Trello](https://trello.com/c/F4b1rEqL/1293-identify-and-revoke-permissions-which-have-been-inappropriately-granted-to-users-by-org-superorg-admins)
I noticed that some the data had a lot of events in which permissions were added but not listed. Some of the permissions could have been removed, but there were too many. It turns out I was splitting the event log's message incorrectly, so the task was looking for e.g. "Editor" within an array like ["signin", " Editor"]. This revises the split to account for the programmatically-added whitespace, which should (correctly) result in more matches
--- …
> Fix permissions by non-GDS users Rake task

- app/controllers/doorkeeper_applications_controller.rb
- app/models/doorkeeper/application.rb
- app/models/event_log.rb
- app/policies/application_policy.rb
- app/views/doorkeeper_applications/access_logs.html.erb
- app/views/doorkeeper_applications/edit.html.erb
- app/views/doorkeeper_applications/monthly_access_stats.html.erb
- config/routes.rb
- db/migrate/20240809112119_index_event_logs_columns.rb
- db/schema.rb
- test/integration/application_access_log_page_test.rb
- test/integration/application_monthly_access_stats_page_test.rb
Occasionally, we get asked questions like "how many people actually use this Whitehall?" or "how many people actually use Content Data?".
This feels like information that should be at anyone working on Publishing's fingertips, but it isn't. We can answer things like "how many people have permission to access Content Data?" easily enough, by filtering the Users table. But people who've _actually accessed it_ is a bit of a mystery.
Currently the best bet is to ask a developer to run a SQL query for you, and hope that they don't make one of the many easy-to-make mistakes which would result in you getting the wrong answer.
[In November 2023](https://github.com/alphagov/signon/pull/2471) we added successful authorization events to the event log (which is retained for two years). That means …
> Add admin UI to view application access events and monthly stats

- docs/access_and_permissions.md
[Trello card](https://trello.com/c/YfiVd4pW/1249-document-how-the-signin-permissions-routes-work-which-are-used-in-the-applicationtablehelper)
Adds some more documentation in the same vein as #3016 for the Signin Permissions Controllers and tidies up a couple of small bits.
> Document Signin Permissions Controllers

- app/views/doorkeeper_applications/monthly_access_stats.html.erb
With many thanks to Jade Fryer for compiling this information from various discussions on Slack and clarifying the wording.
Note the visually hidden "Data" heading is to prevent the data table from appearing under the last heading in the details element ("Data retention") for screen reader users.
> Improve "about this data" definitions and caveats

- test/controllers/api_users/permissions_controller_test.rb
- test/factories/users.rb
[Trello card](https://trello.com/c/mppostUR/1289-refactor-apiuserspermissionscontrollertest)
Refactors the API Users Permissions Controller tests for the `#edit` action to make things a bit easier to read and ensure we're testing the right things to prevent false positives.
This is a rework of #3107, in which I felt I tried to change too much in one go, was difficult to review and modify. In splitting out PRs into smaller chunks, I'm hoping they'll be easier to review and unblock possible parallel work.
Up next, we'll be refactoring tests for the `#update` action.
We're a little unsure about the need for `signin` permissions with API users at the moment, as tests appear to be passing for the right reason without us assigning them to test users. We'll be investigating them shortly, but to …
> Refactor API Users Permissions Controller #edit tests

- app/helpers/users_with_access_helper.rb
- test/helpers/users_with_access_helper_test.rb
This adds the `govuk-link` class to a link that was missing it
---
> Fix users with access link

- test/controllers/api_users/permissions_controller_test.rb
- test/factories/users.rb
[Trello card](https://trello.com/c/mppostUR/1289-refactor-apiuserspermissionscontrollertest)
Refactors the API Users Permissions Controller tests for the `#update` action to make things a bit easier to read and ensure we're testing the right things to prevent false positives. It also attempts to bring tests in line with the other Permissions Controller tests.
Like #3110, this is a rework of #3107, in which I felt I tried to change too much in one go, was difficult to review and modify. 
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) …
> Refactor API Users Controller #update tests

- test/controllers/account/permissions_controller_test.rb
- test/controllers/users/permissions_controller_test.rb
Makes Account and User Permissions Controller tests in line with the recently-refactored API User Permissions tests in #3121 by:
- Removing unecessary reloading of users
- Grouping similar tests in contexts
- Combining "happy path" rendering tests.
> Tidy up Account and Users Permissions Controller tests

- lib/tasks/permissions.rake
I accidentally used a return instead of a `next` to go to the next iteration in a `find`
---
> Fix Rake task for getting non-GDS permissions

- config/locales/department_specific.en.yml
- test/models/user_mailer_test.rb
Replacing the redirected URL with the actual URL to the support app.
> Update link to support app

- lib/tasks/permissions.rake
- test/controllers/two_step_verification_exemptions_controller_test.rb
- test/factories/oauth_applications.rb
- test/factories/organisation.rb
- test/integration/users/two_step_verification_test.rb
- test/lib/tasks/permissions_test.rb
- test/policies/user_policy_test.rb
[Trello](https://trello.com/c/F4b1rEqL/1293-identify-and-revoke-permissions-which-have-been-inappropriately-granted-to-users-by-org-superorg-admins)
These have been identified as inappropriately granted to non-GDS users as part of an exercise to clean up the data after having fixed the way delegatable permissions work. We need to remove these permissions from non-GDS users
---
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails …
> Add Rake task to remove inappropriately-granted perms

- package.json
Should fix https://github.com/alphagov/signon/security/dependabot/85
We have a high severity security alert on Signon. jasmine-browser-runner 2.5.0 depends on express 4.19.2 which depends on path-to-regexp 0.1.7. express 4.20.0 fixes the issue, so this tells Yarn to use that version or above
Technically it looks like jasmine-browser-runner should already allow patch and minor bumps in its dependencies (using `^`), but Dependabot couldn't upgrade express/path-to-regexp
jasmine-browser runner isn't updated particularly regularly - usually every few months, and patch versions are rare - so it's plausible that they won't release a patch for this any time soon
While this is only a dev dependency - and therefore shouldn't be particularly high risk to ignore - the upgrade will at least resolve …
> Fix high severity security alert

- package.json
- yarn.lock
to fix a security vulnerability.
We had a medium security vulnerability because jasmine-browser-runner depends on express 4.20.0 which depends on serve-static 0.16.0 which depends on send 0.18.0, which is currently vulnerable due to https://github.com/advisories/GHSA-m6fv-jmcg-4jfg.
The changes to `yarn.lock` were generated by running `yarn upgrade jasmine-browser-runner` to ensure it's using the patched version (0.19.0) of the `send` dependency.
Follow [these …
> Upgrade jasmine-browser-runner dependencies (particularly "send")

- app/controllers/account/permissions_controller.rb
- app/controllers/account/signin_permissions_controller.rb
- app/controllers/users/permissions_controller.rb
- app/controllers/users/signin_permissions_controller.rb
- app/helpers/application_access_helper.rb
- app/helpers/application_permissions_helper.rb
- app/views/account/applications/index.html.erb
- app/views/api_users/applications/index.html.erb
- app/views/users/applications/index.html.erb
- test/controllers/account/permissions_controller_test.rb
- test/controllers/account/signin_permissions_controller_test.rb
- test/controllers/users/permissions_controller_test.rb
- test/controllers/users/signin_permissions_controller_test.rb
- test/helpers/application_access_helper_test.rb
- test/helpers/application_permissions_helper_test.rb
- test/support/granting_access_helpers.rb
- test/support/removing_access_helpers.rb
- test/support/updating_permissions_helpers.rb
[Trello card](https://trello.com/c/TrHzYz6u/1352-add-a-success-banner-when-granting-or-removing-app-access)
This is (I feel) a neater, second attempt at #3171 with less complexity and is more easily extensible.
We previously displayed a success alert banner when one's own or another user's permissions were updated, but didn't show anything when granting access or removing it. We now display the same banner with different messaging when a user's access is granted or removed.
The API Users journey didn't need updating here, as we already show flash messages when an API token is created or revoked, as well as when permissions are updated.
⚠️ This repo is …
> Display success banner when adding or removing access to an application (take 2)

- lib/tasks/permissions.rake
- test/lib/tasks/permissions_test.rb
[Trello](https://trello.com/c/aRHyvjGE/1401-update-rake-task-to-leave-content-tagger-tagathon-participant-permission)
We have a Rake task for removing permissions from non-GDS users, which will be run once to rectify permissions having been inappropriately granted before we tightened up the feature that allows delegation of granting permissions
We've decided not to remove the 'Tagathon participant' permission, so this updates the Rake task in preparation for running it
---
Follow …
> Retain Content Tagger 'Tagathon participant'

- test/integration/applications/access_logs_test.rb
- test/integration/applications/monthly_access_stats_test.rb
- test/integration/sign_in_test.rb
- test/integration/two_step_verification_test.rb
- test/integration/users/account_access_logs_test.rb
- test/models/batch_invitation_test.rb
- test/models/user_test.rb
- test/policies/batch_invitation_policy_test.rb
- test/support/user_helpers.rb
We were getting a lot of noise about tests missing assertions because of using custom assertion methods (or just relying on tests not raising errors rather than explicitly asserting anything). This adds `assert` in multiple places to fix this, and in one case adds a default return of `true` in a method we need to assert on
E.g.
```
Test is missing assertions: `test_: setting a 2SV code signed in with an existing 2SV setup should require the code again on next login. ` /govuk/signon/test/integration/two_step_verification_test.rb:57
```
--- …
> Fix missing assertions warning

- app/assets/stylesheets/application.scss
- app/helpers/application_table_helper.rb
- app/helpers/components/table_helper.rb
- app/views/account/applications/index.html.erb
- app/views/api_users/applications/index.html.erb
- app/views/components/_table.html.erb
- app/views/users/applications/index.html.erb
- docs/access_and_permissions.md
- test/helpers/application_table_helper_test.rb
[Trello](https://trello.com/c/01evLxdL/1409-clean-up-applications-table-960-1199px-viewport-layout)
At present, on viewports of between 940px and 1199px, the actions links/buttons are various shades of messy, owing to the fact that they share a single column, use `flex` alignment, and are of different widths
This updates the layout so that the actions links/buttons are nicely aligned and consistently positioned at all viewport sizes and regardless of which of the four links/buttons appear in the given tables
---
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#mer …
> Reduce applications table action links layout

- db/migrate/20241001140623_rename_supported_permission_delegatable_column.rb
[Trello](https://trello.com/c/XTbuNRCz/1385-revise-delegated-permissions-terminology-in-codebase)
Looks like a mistake creeped into #3205 and we missed it. The migration failed on Argo, so amending the existing migration should work since it's not yet been applied
---
> Fix delegated column rename migration

- package.json
- yarn.lock
Dependabot has alerted us to a security issue with `cookie`, a dependency of `express`, in turn a dependency of
`jasmine-browser-runner`. A fix has been released for `express`, but `jasmine-browser-runner` isn't frequently updated, so I'm adding a resolution for `express` in the meantime
https://github.com/alphagov/signon/security/dependabot/91
---
> Upgrade Express to fix security issue

- config/environments/production.rb
The previous regex permitted `app-name.dodgygov.uk`. Updating to disallow this and only permit `*.gov.uk`.
[Trello card](https://trello.com/c/frqFN7D8)
> Update hosts for application

- docs/usage.md
These steps are currently missing from the documentation. I did consider adding them to https://docs.publishing.service.gov.uk/manual/alerts/signon-api-user-token-expires-soon.html itself, but that's more about rotating existing tokens, so this feels the more appropriate place.
Trello: https://trello.com/c/YdGWsy0I/3035-integrate-the-specialist-finder-edit-forms-with-support-api
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails …
> Document how API token integrates into eks

- app/views/organisations/_organisation_table.html.erb
- test/controllers/organisations_controller_test.rb
This adds a column to the organisations index table with the name of the parent organisation.
The information is available from a Rails console, but not in the UI, meaning it can be difficult to see the organisation hierarchy without developer input.
Screenshot:
[Trello card](https://trello.com/c/il3oWbfb)
> Show parent organisation in table

- app/views/supported_permissions/index.html.erb
[Trello](https://trello.com/c/rcDUrNIT/1500-add-link-to-definition-of-publishing-manager-in-the-permissions-page-for-each-app-in-signon)
We had a question about the meaning of some of the content on this page, particularly the definition of a publishing manager. We wrote documentation about this in this repo's docs, which it turns out are automatically published on gov.uk in the dev docs. We're therefore linking to this resource for readers who want to know more
The existing paragraphs are largely - if not fully - duplicated from those docs, which doesn't create some extra maintenance burden vs having one source of truth, but it's probably useful to have at least a short explainer here without having to click through to a linked external (if still gov.uk) page
---
This application is …
> Link to access and permissions public page

- app/views/suspensions/edit.html.erb
[Trello](https://trello.com/c/Xcmxk6gg/1503-update-message-guidance-when-unsuspending-signon-accounts-to-say-that-the-user-has-7-days-to-log-in)
We have a rule in the code that a user must log in within seven days of being unsuspended, or the suspension will be reenforced. This doesn't seem to be documented outside of the code (at least not anywhere obvious). We had a support request come in about a user affected by this, so we should clarify this requirement on the unsuspension form
---
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) …
> Update unsuspension guidance

- app/controllers/api/users_controller.rb
- app/models/doorkeeper/application.rb
- app/presenters/api/user_presenter.rb
- config/routes.rb
- test/controllers/api/users_controller_test.rb
- test/models/doorkeeper/application_test.rb
- test/presenters/api/user_presenter_test.rb
Trello card: https://trello.com/c/jVvs4nAP/640-get-author-information-from-signon
In Content Modelling, we have a need to get user information from a central repository. We have an endpoint that returns information about documents that use a given content block, but we only have the UUID of the user who last updated it. To populate the information, we're currently relying on the fact that the Content Block Manager runs in Whitehall to fetch user information. However, if a user isn't present in Whitehall, we have to show the user as "Unknown".
This adds an API endpoint to signon that allows us to get information about users with given UUIDs. This is slightly unknown territory, as Signon is mainly a frontend application. 
To achieve this, we protect our controller with …
> Add an API endpoint to get author information

- .github/workflows/pact-verify.yml
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- docs/api.md
- lib/tasks/applications.rake
- test/service_consumers/pact_helper.rb
Trello card: https://trello.com/c/ifMWZl9n/783-add-api-adapters-for-signon
This adds the Pact tests provider and the workflow, so we can run Pact tests via `gds-api-adapters` (PR here https://github.com/alphagov/gds-api-adapters/pull/1316).
I've also added some lightweight documentation with details about the endpoint and how to authenticate.
> (783) Configute Pact tests provider for Signon

- package.json
- yarn.lock
This updates the dependency `path-to-regexp` to a newer version.
Resolves https://github.com/alphagov/signon/security/dependabot/102.
[Trello card](https://trello.com/c/qvmUj6qK)
> Update `express` npm package to version 4.21.2

- Gemfile.lock
- app/views/users/_users_filter.html.erb
- Upgrades to `govuk_publishing_components` 48.0.0
- Renames a parameter as a result to prevent a label/id being linked together, lost due to a breaking change in the components gem.
- I have tested locally by copying this search component onto the index page of the app, as I can't access the exact page it's rendered on. It's working as expected.
- The changes in this PR are needed because of this PR:  https://github.com/alphagov/govuk_publishing_components/pull/4540 Specifically, `id` refers to ids on the parent HTML element of the component now, so to preserve the ids being for the labels/inputs in this repo they are now called `label_id`.
> Upgrade govuk_publishing_components to 48.0.0

- lib/tasks/data_hygiene.rake
- test/lib/tasks/data_hygiene_test.rb
The `OrganisationFetcher` does not handle the situation of an organisation having been deleted in Whitehall without first being closed.
This means a deleted organisation remains marked as open, and can have users assigned to it in Signon.
Adding rake tasks to:
1. allow us to manually mark organisations as closed, so the organisation no longer appears as an option to which users can be assigned in the user interface.
2. allow us to move all users from one organisation to another, without needing to add all their email addresses in a CSV file.
[Trello card](https://trello.com/c/WDv2141z)
> Add rake tasks for dealing with deleted organisations

- app/controllers/api/users_controller.rb
- test/controllers/api/users_controller_test.rb
Now we’re using the users API locally in a couple of applications, the apps are falling over when trying to access the endpoint. I looked into seeding an application user, but this is tricky because we can’t guarantee what the token will be very easily. I’ve worked around this by skipping the authentication if we’re in the development environment.
It’s not ideal, but saves a lot of messy config in the Docker containers to get apps that use the Signon API up and running.
> Skip API authentication in dev environment

- .github/workflows/ci.yml
- test/test_helper.rb
Our JS-enabled MiniTest tests are failing fairly consistently on CI. We believe that this started when the most recent Github Actions ubuntu-latest image was released[^1]. Though, we don't 100% understand why. There's some speculation[^2] that the root of the issue has something to do with Chrome/Chromedriver version 134 (which is the version bundled with that new ubuntu-latest).
[^1]: https://github.com/actions/runner-images/pull/11761
[^2]: https://github.com/teamcapybara/capybara/issues/2800
We've largely copied what the Mainstream Publishing team did to get their CI back up-and-running[^3].
[^3]: https://github.com/alphagov/publisher/pull/2596
Summary of changes:
* add --no-sandbox flag to Chromedriver startup (GovukTest will do this for us if we set the `GOVUK_TEST_CHROME_NO_SANDBOX` …
> Use old Chrome in CI tests, with --no-sandbox flag
