app/assets/javascripts/modules/organisation_filter.js
app/assets/stylesheets/admin.scss
app/assets/stylesheets/filters.scss
app/controllers/admin/users_controller.rb
app/helpers/user_filter_helper.rb
app/helpers/users_helper.rb
app/models/user.rb
app/views/admin/users/_user_filter.html.erb
app/views/admin/users/_user_filter_group.html.erb
app/views/admin/users/index.html.erb
spec/javascripts/organisation_filter.spec.js
test/functional/admin/users_controller_test.rb
test/integration/admin_user_index_test.rb
test/integration/event_log_test.rb

Add a column for organisation in the users index, and allow filtering by org.

Display and filter users by organisations

---

app/controllers/users_controller.rb
app/presenters/user_export_presenter.rb
app/views/users/_user_filter.html.erb
test/functional/users_controller_test.rb
test/unit/user_export_presenter_test.rb

Includes each user's permissions in all apps.

Export CSV of currently filtered users.

---

app/controllers/users_controller.rb
db/migrate/20150109083425_create_join_table_user_application_permissions.rb
db/migrate/20150121073933_create_join_table_batch_invitation_application_permissions.rb
db/schema.rb

These are some fixes for @vinayvinay's permission remodelling branch which I'm currently based off for the event log work.  One of these is a removal of a minor redundancy, but the changes to the index names are required to run the migrations.

Permissions remodel fixes

---

Gemfile
Gemfile.lock

Remove sqlite3 development dependency

---

Gemfile
Gemfile.lock
app/controllers/api_users_controller.rb
app/controllers/doorkeeper_applications_controller.rb
app/controllers/invitations_controller.rb
app/controllers/supported_permissions_controller.rb
app/controllers/users_controller.rb
app/models/batch_invitation.rb
app/models/batch_invitation_application_permission.rb
app/models/batch_invitation_user.rb
app/models/enhancements/application.rb
app/models/event_log.rb
app/models/organisation.rb
app/models/permission.rb
app/models/supported_permission.rb
app/models/user.rb
app/models/user_application_permission.rb
lib/roles.rb
lib/roles/admin.rb
lib/roles/normal.rb
lib/roles/organisation_admin.rb
lib/roles/superadmin.rb
lib/user_parameter_sanitiser.rb
test/unit/batch_invitation_user_test.rb
test/unit/lib/user_parameter_sanitiser_test.rb
test/unit/user_test.rb

We need to [upgrade Devise to 3.2](https://www.pivotaltracker.com/story/show/91090666) and Devise Invitable to 1.4, which assumes that we're using Rails 4, or at least strong params. This PR is a preliminary step to doing the full Devise upgrade. It also helps to get us nearer to Rails 4, which we should upgrade to soon in any case.
Lots of these changes relate to specific behaviour of Devise and its extensions - look at individual commit messages for more explanation of those.
We've relied on existing test coverage extensively for these changes - the coverage [looks pretty good](https://ci-new.alphagov.co.uk/job/govuk_signonotron2_branches/ws/coverage/rcov/index.html) so we're fairly confident that we haven't broken anything, but should keep this on Preview for a few days before …

Introduce strong parameters

---

Gemfile
Gemfile.lock

Deploy on preview (#1453) failed due to uglifier not being found.

Missing `uglifier` dependency in Gemfile

---

lib/tasks/users.rake

This:
1. avoids an n+1 query
2. doesn't need the user to have logged in
3. Skips API users
4. Adds logging

Speed up content preview task

---

app/jobs/push_user_updates_job.rb
lib/inactive_users_suspension_reminder.rb

A couple of errbit errors have cropped up in production, https://errbit.production.alphagov.co.uk/apps/52ef92340da11517d5000003/problems/55bb0f21657863081b5b0000 and https://errbit.production.alphagov.co.uk/apps/52ef92340da11517d5000003/problems/55ba34a2657863726d6d0000. This addresses those errors. 
Review commit-by-commit, each commit has full details of the change.
/cc @jamiecobbett

Minor post-Rails 4.2.3 fixes for background jobs

---

app/controllers/devise/two_step_verification_controller.rb
app/models/event_log.rb
app/models/user.rb
test/integration/sign_in_test.rb
test/integration/two_step_verification_test.rb

https://trello.com/c/LbIGKlNh/108-log-user-actions-for-mvp-2sv
Ensure entries for 2-step-related events are added to the user's event log

2-step event logs

---

app/controllers/prototype_controller.rb
app/views/prototype/phone_unavailable.html.erb
app/views/prototype/recover_account.html.erb
config/routes.rb

Prototype work from @fofr.
Want to merge this just for User Research purposes.

2-step verification email recovery prototype

---

Gemfile
app/controllers/application_controller.rb
app/controllers/devise/two_step_verification_controller.rb
app/controllers/passwords_controller.rb
app/controllers/sessions_controller.rb
app/helpers/two_step_verification_helper.rb
app/models/event_log.rb
app/models/user.rb
app/policies/user_policy.rb
app/views/devise/two_step_verification/prompt.html.erb
app/views/root/index.html.erb
app/views/users/_form_fields.html.erb
config/initializers/doorkeeper.rb
config/routes.rb
db/migrate/20150928115351_add_requires2sv_to_users.rb
db/migrate/20150929135437_rename_users_requires2sv.rb
db/migrate/20151006091244_add_deferred2sv_at_to_users.rb
db/schema.rb
lib/roles/superadmin.rb
spec/policies/user_policy_spec.rb
test/factories/users.rb
test/helpers/user_helpers.rb
test/integration/authorise_application_test.rb
test/integration/dashboard_test.rb
test/integration/inviting_users_test.rb
test/integration/two_step_verification_prompt_test.rb
test/integration/two_step_verification_test.rb
test/models/user_test.rb

Let's try this again... This should now address all the requisite acceptance criteria and will have resolved the oauth redirect oddities. Thorough descriptions are in the individual commits.
Some of this was done in unison with @boffbowsh so it would be good to have some fresh eyes to review @benilovj @jamiecobbett.

Flag for 2SV

---

app/views/devise/two_step_verification_session/new.html.erb
app/views/users/_form_fields.html.erb

Trello: https://trello.com/c/diHw4iMo

Improvements to 2SV reset for user/administrator

---

app/controllers/devise/two_step_verification_controller.rb
app/models/user.rb
app/views/devise/two_step_verification/prompt.html.erb
app/views/devise/two_step_verification/show.html.erb
test/controllers/two_step_verification_controller_test.rb
test/integration/two_step_verification_prompt_test.rb
test/models/user_test.rb

Add various behaviours to enforce 2SV hard go live.
Trello: https://trello.com/c/rBeCGzWg

2SV hard go live

---

app/controllers/devise/two_step_verification_controller.rb
app/models/user.rb
app/views/devise/two_step_verification/prompt.html.erb
app/views/devise/two_step_verification/show.html.erb
config/routes.rb
db/migrate/20151120134709_remove_deferred_at_from_users.rb
db/schema.rb
test/controllers/two_step_verification_controller_test.rb
test/integration/authorise_application_test.rb
test/integration/dashboard_test.rb
test/integration/two_step_verification_prompt_test.rb
test/models/user_test.rb

Trello: https://trello.com/c/1gH5NTC6
2SV went live today so we can clean up the cruft. Removes deferral, go
live date checks and simplifies 2SV prompt logic.

Clean up after 2SV hard go live date

---

app/controllers/doorkeeper_applications_controller.rb
app/models/user.rb
app/queries/users_with_access.rb
app/views/doorkeeper_applications/users_with_access.html.erb

Per feedback on https://trello.com/c/G9oupgco, this PR:
- Displays the permissions of the user on the application users page
- Sorts the users by last signin date

Show user permissions in application user list

---

app/controllers/users_controller.rb
app/helpers/user_filter_helper.rb
app/helpers/users_helper.rb
app/models/user.rb
app/presenters/user_export_presenter.rb
app/views/users/_user_filter.html.erb
app/views/users/_user_filter_group.html.erb
app/views/users/_user_filter_group_no_js.html.erb
app/views/users/index.html.erb
test/integration/admin_user_index_test.rb
test/models/user_export_presenter_test.rb
test/models/user_test.rb

https://trello.com/c/JpTKA5M5
This PR may be better reviewed commit by commit.
Before changes showing original UI
===========================
After changes showing filter and new 2SV Status column
===========================================

Add 2SV status filtering to User list.

---

app/controllers/devise/two_step_verification_controller.rb
app/mailers/mailer_helper.rb
app/mailers/noisy_batch_invitation.rb
config/initializers/i18n.rb
config/locales/department_specific.en.yml
test/controllers/two_step_verification_controller_test.rb
test/models/noisy_batch_invitation_test.rb

Superceeds PR: https://github.com/alphagov/signonotron2/pull/468 without view changes

Extract department text phase 1

---

app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/mailer/unlock_instructions.text.erb
app/views/layouts/user_mailer.html.erb
app/views/layouts/user_mailer.text.erb
app/views/user_mailer/email_changed_by_admin_notification.html.erb
app/views/user_mailer/email_changed_by_admin_notification.text.erb
app/views/user_mailer/email_changed_notification.html.erb
app/views/user_mailer/email_changed_notification.text.erb
app/views/user_mailer/notify_reset_password_disallowed_due_to_suspension.html.erb
app/views/user_mailer/notify_reset_password_disallowed_due_to_suspension.text.erb
app/views/user_mailer/suspension_notification.html.erb
app/views/user_mailer/suspension_notification.text.erb
app/views/user_mailer/suspension_reminder.html.erb
app/views/user_mailer/suspension_reminder.text.erb
app/views/user_mailer/two_step_changed.html.erb
app/views/user_mailer/two_step_changed.text.erb
app/views/user_mailer/two_step_enabled.html.erb
app/views/user_mailer/two_step_enabled.text.erb
app/views/user_mailer/two_step_flagged.text.erb
app/views/user_mailer/two_step_reset.html.erb
app/views/user_mailer/two_step_reset.text.erb
app/views/user_mailer/unlock_instructions.html.erb
app/views/user_mailer/unlock_instructions.text.erb
test/models/user_mailer_test.rb

Closes #472.
Mostly contributed by @dwhenry. This removes duplication from the mailer templates.

Refactor mailer views

---

app/views/devise/mailer/invitation_instructions.html.erb
app/views/devise/mailer/invitation_instructions.text.erb
app/views/devise/two_step_verification_session/max_2sv_login_attempts_reached.html.erb
app/views/devise/two_step_verification_session/new.html.erb
app/views/layouts/application.html.erb
app/views/layouts/user_mailer.html.erb
app/views/layouts/user_mailer.text.erb
app/views/noisy_batch_invitation/make_noise.html.erb
app/views/noisy_batch_invitation/make_noise.text.erb
app/views/root/index.html.erb
app/views/user_mailer/email_changed_by_admin_notification.html.erb
app/views/user_mailer/email_changed_by_admin_notification.text.erb
app/views/user_mailer/email_changed_notification.html.erb
app/views/user_mailer/email_changed_notification.text.erb
app/views/user_mailer/notify_reset_password_disallowed_due_to_suspension.html.erb
app/views/user_mailer/notify_reset_password_disallowed_due_to_suspension.text.erb
app/views/user_mailer/suspension_notification.html.erb
app/views/user_mailer/suspension_notification.text.erb
app/views/user_mailer/suspension_reminder.html.erb
app/views/user_mailer/suspension_reminder.text.erb
app/views/user_mailer/two_step_changed.html.erb
app/views/user_mailer/two_step_changed.text.erb
app/views/user_mailer/two_step_reset.html.erb
app/views/user_mailer/two_step_reset.text.erb
app/views/user_mailer/unlock_instructions.html.erb
app/views/user_mailer/unlock_instructions.text.erb
app/views/users/two_step_flagged.html.erb
config/initializers/govuk_admin_template.rb
config/locales/department_specific.en.yml

This is the last piece of work to allow pension wise to merge our branch back in.
We still have some differences, which I will leave within our branch :
- Using Postgres instead of MySQL - existing branch attempting to solve this issue.
- Using Puma instead of Unicorn.
- Using Bugsnag instead of Airbrake.
- Adding Newrelic logging
- Using Rails12Factor instead of LogStasher
- Upgrade of SideKiq to v 4.0
Let me know if you think any should be merged in (or written to allow either to be used).
David

Replacement department name with locale lookup.

---

app/controllers/batch_invitations_controller.rb
app/policies/batch_invitation_policy.rb
spec/policies/batch_invitation_policy_spec.rb
test/integration/batch_inviting_users_test.rb

Fix to bug preventing user with organisation admin from being able to batch invite users.

Batch upload for organisation admin

---

app/views/devise/invitations/edit.html.erb
app/views/devise/passwords/_change_password_panel.html.erb
config/locales/en.yml

Remove duplicate submit button on invitation accept form

---

config/devise.yml
config/initializers/devise.rb

Depends on https://github.com/alphagov/govuk-puppet/pull/4877 and https://github.gds/gds/deployment/pull/1083 being in production.
I think this approach is safer than what we have at the moment.

YAML secrets for Devise

---

Gemfile
Gemfile.lock
app/models/enhancements/application.rb
db/migrate/20161223162747_add_deleted_at_to_application.rb
db/schema.rb
test/models/lib/enhancements/application_test.rb

We have a few applications we'd like to retire from signon but we need to keep the records of them.

Add soft deletion

---

db/migrate/20170110171851_remove_share_sale_publisher.rb
db/schema.rb

This application doesn't exist any more so remove it from Signon

Remove Share Sale Publisher

---

script/prepare_training_environment

This commit changes the username and password for training users to make them simpler to remember.

Change username and password for training users

---

script/make_oauth_work_in_dev
script/prepare_training_environment

We have retired the app
Trello: https://trello.com/c/2MF97xce/154-retire-content-api

Removing content-api references

---

db/migrate/20170927105747_model_cabinet_office_org_structure.rb
db/schema.rb

For: https://trello.com/c/vsChwAV6/227-model-cabinet-office-correctly-within-signon
Checks that the children and grandchildren of Cabinet Office have the right ancestry assigned to them.
| Parent          | Children                                     | Grandchildren                    |
| --------------- | ---------------------------------------------| -------------------------------- |
| Cabinet Office  | Committee on Standards in Public Life        |                                  |
|                 | Office of the Leader of the House of Commons |                                  |
|                 | ...                                          | ...                              |
|                 | Prime Minister's Office, 10 Downing Street   | UK Holocaust Memorial Foundation | …

Model Cabinet Office ancestry correctly within Signon

---

db/migrate/20171002120204_model_defra_org_structure.rb
db/schema.rb

For: https://trello.com/c/4uywjwpG/229-model-defra-correctly-within-signon
Checks that the children and grandchildren of the "Department for Environment, Food & Rural Affairs" (DEFRA) have the right ancestry assigned to them.
| Parent                                            | Children                                         | Grandchildren                         |
| ------------------------------------------------- | -------------------------------------------------| ------------------------------------- |
| Department for Environment, Food & Rural Affairs  | Animal Health and Veterinary Laboratories Agency |                                       |
|                                                   | The Food and Environment Research Agency         | UK Government Decontamination …

Model DEFRA org ancestry correctly

---

db/migrate/20171020125018_model_dclg_org_structure.rb
db/migrate/20171020132253_model_dft_org_structure.rb
db/schema.rb

For: 
* https://trello.com/c/9oMatX0Z/259-model-dclg-correctly-within-signon
* https://trello.com/c/qk0lXJYW/260-model-dft-correctly-within-signon
We model the hierarchies of DCLG and DfT correctly to bring them up-to-date based on the hierarchy in whitehall.  Just like we did in #573 and #572 for other orgs.

Model dclg and dft correctly

---

db/migrate/20171107105233_model_beis_org_structure.rb
db/migrate/20171107122414_model_dcms_org_structure.rb
db/migrate/20171107131556_model_dfid_org_structure.rb

For:
* https://trello.com/c/YiC1anUw/268-model-beis-correctly-within-signon
* https://trello.com/c/cqyVMWYE/269-model-dcms-correctly-within-signon
* https://trello.com/c/TzflLNHY/271-model-dfid-correctly-within-signon
Just like #585, #580, etc... we make sure signon has the correct hierarchy for these orgs, based on the hierarchy defined in Whitehall.

Model BEIS, DCMS, DfID correctly

---

doc/mass_password_reset.md

Add mass password reset documentation

---

doc/usage.md

Add information about how signon gets its list of organisations and how it keeps it up to date.

Document organisation fetcher

---

Jenkinsfile

As far as I can tell this previously followed the steps for
govuk.buildProject() almost exactly (but a bit out of date).
There's a bunch of work to be done to get the sass linting to play ball
though so this has been disabled.

Use govuk.buildProject in Jenkinsfile

---

Dockerfile
Procfile
config/database.yml

Wider context: https://github.com/alphagov/publishing-e2e-tests/pull/202
This PR adds foreman as a gem dependency of docker (as per [foreman instructions](https://github.com/ddollar/foreman#installation)) as the means to run the processes for this app.
It also adds the web process to the Profile to boot the web server.

Foreman dockerfile

---

lib/tasks/users.rake
lib/user_suspensions_exporter.rb
test/factories/event_log.rb
test/models/lib/user_suspensions_exporter_test.rb

I used environment variables to be consistent with the other rake tasks.
---
[Trello card](https://trello.com/c/71LDXfs0/307-export-of-users-who-have-had-accounts-suspended)

Rake task to export a list of users created / auto-suspended since a given date

---

config/application.rb

I added this line to test, but forgot to remove.

Show correct environment colours

---

app/views/devise/sessions/new.html.erb

Update login page to set autofocus on the first input
[Trello card](https://trello.com/c/05wMNlxg)

Add autofocus on login page

---

app/helpers/component_helper.rb
app/views/layouts/admin_layout.html.erb
config/locales/devise.en.yml
test/integration/manage_api_users_test.rb
test/integration/session_timeout_test.rb
test/integration/sign_in_test.rb
test/integration/sign_out_test.rb

Tweaks to microcopy

---

test/test_helper.rb

`require mocha/mini_test` has been deprecated.

Use `require 'mocha/minitest'

---

app/models/api_user.rb

https://trello.com/c/pvSF3FTe/5-rotate-gds-sso-tokens
This follows-on from the addition of a new healthcheck to monitor tokens
that are close to expire, so that we replace them in good time.

Lower default token expiry for API tokens

---

lib/tasks/users.rake

The task now grants permission for suspended users as well.

Amend rake task description

---

app/views/suspensions/edit.html.erb

If the user is unsuspended, this lets you set the reason.  If the user
is suspended, this lets you see the reason.

Display the reason for suspension in all cases

---

app/controllers/suspensions_controller.rb
app/views/suspensions/edit.html.erb
test/integration/event_log_creation_test.rb
test/integration/manage_api_users_test.rb

Changing forms without talking to users is dangerous.

Revert suspensions form to how it was and add the password reset note

---

db/migrate/20190417111131_clone_trade_tariff_admin.rb
db/migrate/20190417130540_clone_trade_tariff_backend.rb
db/schema.rb

We will clone the applications and allow users to use the new one
then change the URI on the new application to the new service.
Once this works, we can retire the old applications
Zendesk: https://govuk.zendesk.com/agent/tickets/3634856

Clones Trade Tariff Admin and Trade Tariff Backend apps and user permissions

---

db/migrate/20190712160951_add_apha_as_child_of_defra.rb

Otherwise the migration won't run

Add version to migration

---

db/migrate/20190903120837_set_default_event_log_uid.rb

https://stackoverflow.com/questions/10900778/rails-migration-to-make-a-column-null-true
Worked for me locally, didn't work on deploy 🤷‍♂

Use change_column_null, not change_column

---

lib/tasks/user_application_permissions.rake

This PR makes two changes:
1. Write an event to audit log when we grant permissions
2. Re-work permissions granting for 2i users in Collections Publisher (some users would gain the 2i permission, but be unable to login after running this rake task)
One of the lines in 8cc8f18b83b34cd711981916c52f577326716f48 is rather long, but I plan on deleting this code once we've run it once.
Trello card: https://trello.com/c/lPYBEJzc/40-create-a-new-2i-reviewer-permission

Update rake task for granting 2i permission to Collections Publisher users

---

.rubocop.yml
app/controllers/api_users_controller.rb
app/controllers/invitations_controller.rb
app/controllers/passwords_controller.rb
app/helpers/root_helper.rb
app/views/root/signin_required.html.erb
test/helpers/root_helper_test.rb
test/lib/organisations_fetcher_test.rb

https://github.com/alphagov/rubocop-govuk/issues/73

Remove redundant RuboCop config

---

docs/troubleshooting.md

Zendesk ticket: https://govuk.zendesk.com/agent/tickets/4127064
Add what to do if the user can't receive the password reset email

Add troubleshooting docs

---

Gemfile
Gemfile.lock
app/assets/javascripts/modules/dropdown_filter.js
app/assets/stylesheets/_filters.scss
app/controllers/users_controller.rb
app/helpers/user_filter_helper.rb
app/models/user.rb
app/views/users/_user_filter.html.erb
app/views/users/_user_filter_group.html.erb
config/environments/development.rb
db/schema.rb
spec/javascripts/dropdown_filter.spec.js
test/controllers/users_controller_test.rb
test/factories/user_application_permission.rb
test/integration/admin_user_index_test.rb
test/models/user_test.rb

See individual commit messages.
Trello card: https://trello.com/c/kuKk7npQ/2051-5-enable-filtering-of-managing-editors-in-signon

Filter users by permission

---

app/views/user_mailer/reset_password_instructions.text.erb

This is already being added at another step.
https://trello.com/c/ZB29y9Y0/2050-signon-use-notify-instead-of-amazon-ses-%F0%9F%8D%90

Remove duplicate greeting in email template

---

Gemfile
Gemfile.lock
test/test_helper.rb

https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
We should always monitor the amount of code that is exercised when
we run our tests.

Use SimpleCov to monitor code coverage

---

test/integration/api/applications_test.rb
test/integration/api/authorisations_test.rb

See https://github.com/alphagov/signon/pull/1642#discussion_r631132871

Fix test expectations for API

---

app/views/devise/two_step_verification_session/new.html.erb

Missed a full stop in text changes :-)

Fix missing full stop

---

app/presenters/event_log_presenter.rb
test/presenters/event_log_presenter_test.rb
test/signin_permission_granter_test.rb

Adding tests for a couple of classes/modules that weren't tested. Part of increasing test coverage ahead of switching this application to CD.
This gets us from ~94% coverage to 96.77% 🥳 
[Trello](https://trello.com/c/jBtHWHBh/14-enable-continuous-deployment-for-signon)

Increase test coverage

---

config/initializers/sso_push.rb
test/lib/healthcheck/api_tokens_test.rb

https://trello.com/c/CkRb8XcT/3003-audit-usage-of-alphagovcouk-domain-2

Remove references of old alphagov domain

---

README.md
app/controllers/two_step_verification_exemptions_controller.rb
app/helpers/user_filter_helper.rb
app/models/user.rb
app/views/organisations/edit.html.erb
app/views/two_step_verification_exemptions/edit.html.erb
app/views/users/_form_fields.html.erb
test/integration/admin_user_index_test.rb
test/integration/change_user_role_test.rb
test/integration/managing_two_step_verification_test.rb
test/models/user_test.rb
test/support/managing_two_sv_helpers.rb

This makes a number of small tweaks and fixes, following product review.  The changes are detailed in each commit message.
[Trello card](https://trello.com/c/bx60OxDu)

Tweaks to 2-step verification (2SV) following product review

---

app/controllers/invitations_controller.rb
app/models/user.rb
test/controllers/invitations_controller_test.rb
test/models/user_test.rb

Mandate 2sv for new and promoted org admins and org super admins

---

test/integration/authorise_application_test.rb

I've made a number of small changes in an attempt to make the test easier to understand and work with.

Improve Authorise Application integration test

---

app/views/users/index.html.erb

Trello: https://trello.com/c/zNFNt7Oj
This button matches the designs we wanted to use for this page, I picked the wrong one in 7c9864f49b.

Fix "Upload a batch of users" button type

---

docs/troubleshooting.md

Updating the command as we are now on EKS.

Update Troubleshooting docs

---

app/controllers/users/emails_controller.rb
app/controllers/users/names_controller.rb
app/controllers/users/organisations_controller.rb
app/controllers/users/roles_controller.rb
app/models/user.rb
config/brakeman.ignore
test/controllers/users/organisations_controller_test.rb
test/controllers/users/roles_controller_test.rb
test/models/user_test.rb

Just a few small tidying up commits for controllers under the `Users` namespace. See individual commit notes for details.

Tidy up users controllers

---

app/views/user_mailer/suspension_notification.text.erb

[Trello](https://trello.com/c/f8X6DxbK/315-update-suspension-emails-to-cover-local-authority-users)

Update suspension notification email

---

docs/oauth.md

https://trello.com/c/HAEH2bVF/4-rename-imminence

Remove Imminence reference

---

app/controllers/users/permissions_controller.rb
docs/access_and_permissions.md
test/controllers/account/permissions_controller_test.rb
test/controllers/users/permissions_controller_test.rb

[Trello](https://trello.com/c/XTHrweif/1291-refactor-permissions-controller-test-specs)
The users and account permissions controllers are quite large, particularly the former, which combined with various inconsistencies and other issues made them a little unwieldy and challenging to revise/extend. This tidies both up quite substantially
---

Refactor permissions controller tests

---

app/views/doorkeeper_applications/monthly_access_stats.html.erb

Again, with credit to Jade Fryer for pointing these out.

Add limitation notes to monthly access stats

---

test/controllers/account/permissions_controller_test.rb
test/controllers/users/permissions_controller_test.rb

Looks like there were a few errors in the groupings added in 3457ca1 and de2d24a, so this fixes that
---

Fix permissions test contexts

---

db/schema.rb

Another thing I forgot to do when I supposedly upgraded this app to Rails 8
https://trello.com/c/QS6pLnQq/1550-dump-the-database-schemas-for-the-apps-that-were-upgraded-to-rails-8

Update database schema for Rails 8

---

docs/arch/adr-001-pass-anonymised-user-ids-to-publishing-apps-and-analytics.md

✨ [Rendered](https://github.com/alphagov/signon/blob/anonymised-user-id/docs/arch/adr-001-pass-anonymised-user-ids-to-publishing-apps-and-analytics.md) ✨

[PP-7302] Add decision record for anonymised user ids
